// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mxm_execute_ursa_mxm_execute_ursa_Pipeline_LOAD_B (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_bi_AWVALID,
        m_axi_bi_AWREADY,
        m_axi_bi_AWADDR,
        m_axi_bi_AWID,
        m_axi_bi_AWLEN,
        m_axi_bi_AWSIZE,
        m_axi_bi_AWBURST,
        m_axi_bi_AWLOCK,
        m_axi_bi_AWCACHE,
        m_axi_bi_AWPROT,
        m_axi_bi_AWQOS,
        m_axi_bi_AWREGION,
        m_axi_bi_AWUSER,
        m_axi_bi_WVALID,
        m_axi_bi_WREADY,
        m_axi_bi_WDATA,
        m_axi_bi_WSTRB,
        m_axi_bi_WLAST,
        m_axi_bi_WID,
        m_axi_bi_WUSER,
        m_axi_bi_ARVALID,
        m_axi_bi_ARREADY,
        m_axi_bi_ARADDR,
        m_axi_bi_ARID,
        m_axi_bi_ARLEN,
        m_axi_bi_ARSIZE,
        m_axi_bi_ARBURST,
        m_axi_bi_ARLOCK,
        m_axi_bi_ARCACHE,
        m_axi_bi_ARPROT,
        m_axi_bi_ARQOS,
        m_axi_bi_ARREGION,
        m_axi_bi_ARUSER,
        m_axi_bi_RVALID,
        m_axi_bi_RREADY,
        m_axi_bi_RDATA,
        m_axi_bi_RLAST,
        m_axi_bi_RID,
        m_axi_bi_RFIFONUM,
        m_axi_bi_RUSER,
        m_axi_bi_RRESP,
        m_axi_bi_BVALID,
        m_axi_bi_BREADY,
        m_axi_bi_BRESP,
        m_axi_bi_BID,
        m_axi_bi_BUSER,
        zext_ln214,
        select_ln123,
        b_buf_7_address0,
        b_buf_7_ce0,
        b_buf_7_we0,
        b_buf_7_d0,
        b_buf_6_address0,
        b_buf_6_ce0,
        b_buf_6_we0,
        b_buf_6_d0,
        b_buf_5_address0,
        b_buf_5_ce0,
        b_buf_5_we0,
        b_buf_5_d0,
        b_buf_4_address0,
        b_buf_4_ce0,
        b_buf_4_we0,
        b_buf_4_d0,
        b_buf_3_address0,
        b_buf_3_ce0,
        b_buf_3_we0,
        b_buf_3_d0,
        b_buf_2_address0,
        b_buf_2_ce0,
        b_buf_2_we0,
        b_buf_2_d0,
        b_buf_1_address0,
        b_buf_1_ce0,
        b_buf_1_we0,
        b_buf_1_d0,
        b_buf_address0,
        b_buf_ce0,
        b_buf_we0,
        b_buf_d0,
        addr_b0,
        zext_ln196
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_bi_AWVALID;
input   m_axi_bi_AWREADY;
output  [31:0] m_axi_bi_AWADDR;
output  [0:0] m_axi_bi_AWID;
output  [31:0] m_axi_bi_AWLEN;
output  [2:0] m_axi_bi_AWSIZE;
output  [1:0] m_axi_bi_AWBURST;
output  [1:0] m_axi_bi_AWLOCK;
output  [3:0] m_axi_bi_AWCACHE;
output  [2:0] m_axi_bi_AWPROT;
output  [3:0] m_axi_bi_AWQOS;
output  [3:0] m_axi_bi_AWREGION;
output  [0:0] m_axi_bi_AWUSER;
output   m_axi_bi_WVALID;
input   m_axi_bi_WREADY;
output  [63:0] m_axi_bi_WDATA;
output  [7:0] m_axi_bi_WSTRB;
output   m_axi_bi_WLAST;
output  [0:0] m_axi_bi_WID;
output  [0:0] m_axi_bi_WUSER;
output   m_axi_bi_ARVALID;
input   m_axi_bi_ARREADY;
output  [31:0] m_axi_bi_ARADDR;
output  [0:0] m_axi_bi_ARID;
output  [31:0] m_axi_bi_ARLEN;
output  [2:0] m_axi_bi_ARSIZE;
output  [1:0] m_axi_bi_ARBURST;
output  [1:0] m_axi_bi_ARLOCK;
output  [3:0] m_axi_bi_ARCACHE;
output  [2:0] m_axi_bi_ARPROT;
output  [3:0] m_axi_bi_ARQOS;
output  [3:0] m_axi_bi_ARREGION;
output  [0:0] m_axi_bi_ARUSER;
input   m_axi_bi_RVALID;
output   m_axi_bi_RREADY;
input  [63:0] m_axi_bi_RDATA;
input   m_axi_bi_RLAST;
input  [0:0] m_axi_bi_RID;
input  [9:0] m_axi_bi_RFIFONUM;
input  [0:0] m_axi_bi_RUSER;
input  [1:0] m_axi_bi_RRESP;
input   m_axi_bi_BVALID;
output   m_axi_bi_BREADY;
input  [1:0] m_axi_bi_BRESP;
input  [0:0] m_axi_bi_BID;
input  [0:0] m_axi_bi_BUSER;
input  [12:0] zext_ln214;
input  [15:0] select_ln123;
output  [7:0] b_buf_7_address0;
output   b_buf_7_ce0;
output   b_buf_7_we0;
output  [7:0] b_buf_7_d0;
output  [7:0] b_buf_6_address0;
output   b_buf_6_ce0;
output   b_buf_6_we0;
output  [7:0] b_buf_6_d0;
output  [7:0] b_buf_5_address0;
output   b_buf_5_ce0;
output   b_buf_5_we0;
output  [7:0] b_buf_5_d0;
output  [7:0] b_buf_4_address0;
output   b_buf_4_ce0;
output   b_buf_4_we0;
output  [7:0] b_buf_4_d0;
output  [7:0] b_buf_3_address0;
output   b_buf_3_ce0;
output   b_buf_3_we0;
output  [7:0] b_buf_3_d0;
output  [7:0] b_buf_2_address0;
output   b_buf_2_ce0;
output   b_buf_2_we0;
output  [7:0] b_buf_2_d0;
output  [7:0] b_buf_1_address0;
output   b_buf_1_ce0;
output   b_buf_1_we0;
output  [7:0] b_buf_1_d0;
output  [7:0] b_buf_address0;
output   b_buf_ce0;
output   b_buf_we0;
output  [7:0] b_buf_d0;
input  [31:0] addr_b0;
input  [12:0] zext_ln196;

reg ap_idle;
reg m_axi_bi_ARVALID;
reg m_axi_bi_RREADY;
reg b_buf_7_ce0;
reg b_buf_7_we0;
reg b_buf_6_ce0;
reg b_buf_6_we0;
reg b_buf_5_ce0;
reg b_buf_5_we0;
reg b_buf_4_ce0;
reg b_buf_4_we0;
reg b_buf_3_ce0;
reg b_buf_3_we0;
reg b_buf_2_ce0;
reg b_buf_2_we0;
reg b_buf_1_ce0;
reg b_buf_1_we0;
reg b_buf_ce0;
reg b_buf_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln123_fu_281_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    bi_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    bi_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [28:0] zext_ln196_cast_fu_260_p1;
reg   [28:0] zext_ln196_cast_reg_456;
reg   [28:0] trunc_ln4_reg_465;
wire   [7:0] trunc_ln129_1_fu_318_p1;
reg   [7:0] trunc_ln129_1_reg_470;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter2_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter3_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter4_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter5_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter6_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter7_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter8_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter9_reg;
reg   [7:0] trunc_ln129_1_reg_470_pp0_iter10_reg;
wire   [7:0] trunc_ln129_fu_347_p1;
reg   [7:0] trunc_ln129_reg_481;
reg   [7:0] tmp_s_reg_486;
reg   [7:0] tmp_1_reg_491;
reg   [7:0] tmp_2_reg_496;
reg   [7:0] tmp_3_reg_501;
reg   [7:0] tmp_4_reg_506;
reg   [7:0] tmp_5_reg_511;
reg   [7:0] tmp_6_reg_516;
wire   [31:0] zext_ln129_fu_421_p1;
wire  signed [31:0] sext_ln126_fu_337_p1;
reg   [28:0] idx_fu_112;
wire   [28:0] idx_1_fu_322_p2;
wire   [28:0] zext_ln214_cast_fu_264_p1;
wire    ap_loop_init;
reg   [15:0] k_fu_116;
wire   [15:0] add_ln123_fu_286_p2;
wire   [31:0] shl_ln1_fu_295_p3;
wire   [31:0] add_ln126_fu_303_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 idx_fu_112 = 29'd0;
#0 k_fu_116 = 16'd0;
#0 ap_done_reg = 1'b0;
end

mxm_execute_ursa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_fu_112 <= zext_ln214_cast_fu_264_p1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln123_fu_281_p2 == 1'd0))) begin
            idx_fu_112 <= idx_1_fu_322_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_116 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln123_fu_281_p2 == 1'd0))) begin
            k_fu_116 <= add_ln123_fu_286_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        tmp_1_reg_491 <= {{m_axi_bi_RDATA[23:16]}};
        tmp_2_reg_496 <= {{m_axi_bi_RDATA[31:24]}};
        tmp_3_reg_501 <= {{m_axi_bi_RDATA[39:32]}};
        tmp_4_reg_506 <= {{m_axi_bi_RDATA[47:40]}};
        tmp_5_reg_511 <= {{m_axi_bi_RDATA[55:48]}};
        tmp_6_reg_516 <= {{m_axi_bi_RDATA[63:56]}};
        tmp_s_reg_486 <= {{m_axi_bi_RDATA[15:8]}};
        trunc_ln129_1_reg_470_pp0_iter10_reg <= trunc_ln129_1_reg_470_pp0_iter9_reg;
        trunc_ln129_1_reg_470_pp0_iter2_reg <= trunc_ln129_1_reg_470;
        trunc_ln129_1_reg_470_pp0_iter3_reg <= trunc_ln129_1_reg_470_pp0_iter2_reg;
        trunc_ln129_1_reg_470_pp0_iter4_reg <= trunc_ln129_1_reg_470_pp0_iter3_reg;
        trunc_ln129_1_reg_470_pp0_iter5_reg <= trunc_ln129_1_reg_470_pp0_iter4_reg;
        trunc_ln129_1_reg_470_pp0_iter6_reg <= trunc_ln129_1_reg_470_pp0_iter5_reg;
        trunc_ln129_1_reg_470_pp0_iter7_reg <= trunc_ln129_1_reg_470_pp0_iter6_reg;
        trunc_ln129_1_reg_470_pp0_iter8_reg <= trunc_ln129_1_reg_470_pp0_iter7_reg;
        trunc_ln129_1_reg_470_pp0_iter9_reg <= trunc_ln129_1_reg_470_pp0_iter8_reg;
        trunc_ln129_reg_481 <= trunc_ln129_fu_347_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        trunc_ln129_1_reg_470 <= trunc_ln129_1_fu_318_p1;
        trunc_ln4_reg_465 <= {{add_ln126_fu_303_p2[31:3]}};
        zext_ln196_cast_reg_456[12 : 0] <= zext_ln196_cast_fu_260_p1[12 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln123_fu_281_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_1_ce0 = 1'b1;
    end else begin
        b_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_1_we0 = 1'b1;
    end else begin
        b_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_2_ce0 = 1'b1;
    end else begin
        b_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_2_we0 = 1'b1;
    end else begin
        b_buf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_3_ce0 = 1'b1;
    end else begin
        b_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_3_we0 = 1'b1;
    end else begin
        b_buf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_4_ce0 = 1'b1;
    end else begin
        b_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_4_we0 = 1'b1;
    end else begin
        b_buf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_5_ce0 = 1'b1;
    end else begin
        b_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_5_we0 = 1'b1;
    end else begin
        b_buf_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_6_ce0 = 1'b1;
    end else begin
        b_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_6_we0 = 1'b1;
    end else begin
        b_buf_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_7_ce0 = 1'b1;
    end else begin
        b_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_7_we0 = 1'b1;
    end else begin
        b_buf_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_ce0 = 1'b1;
    end else begin
        b_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_buf_we0 = 1'b1;
    end else begin
        b_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        bi_blk_n_AR = m_axi_bi_ARREADY;
    end else begin
        bi_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        bi_blk_n_R = m_axi_bi_RVALID;
    end else begin
        bi_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_bi_ARVALID = 1'b1;
    end else begin
        m_axi_bi_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_bi_RREADY = 1'b1;
    end else begin
        m_axi_bi_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_fu_286_p2 = (k_fu_116 + 16'd1);

assign add_ln126_fu_303_p2 = (shl_ln1_fu_295_p3 + addr_b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10)) | ((m_axi_bi_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10)) | ((m_axi_bi_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10 = (m_axi_bi_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign b_buf_1_address0 = zext_ln129_fu_421_p1;

assign b_buf_1_d0 = tmp_s_reg_486;

assign b_buf_2_address0 = zext_ln129_fu_421_p1;

assign b_buf_2_d0 = tmp_1_reg_491;

assign b_buf_3_address0 = zext_ln129_fu_421_p1;

assign b_buf_3_d0 = tmp_2_reg_496;

assign b_buf_4_address0 = zext_ln129_fu_421_p1;

assign b_buf_4_d0 = tmp_3_reg_501;

assign b_buf_5_address0 = zext_ln129_fu_421_p1;

assign b_buf_5_d0 = tmp_4_reg_506;

assign b_buf_6_address0 = zext_ln129_fu_421_p1;

assign b_buf_6_d0 = tmp_5_reg_511;

assign b_buf_7_address0 = zext_ln129_fu_421_p1;

assign b_buf_7_d0 = tmp_6_reg_516;

assign b_buf_address0 = zext_ln129_fu_421_p1;

assign b_buf_d0 = trunc_ln129_reg_481;

assign icmp_ln123_fu_281_p2 = ((k_fu_116 == select_ln123) ? 1'b1 : 1'b0);

assign idx_1_fu_322_p2 = (zext_ln196_cast_reg_456 + idx_fu_112);

assign m_axi_bi_ARADDR = sext_ln126_fu_337_p1;

assign m_axi_bi_ARBURST = 2'd0;

assign m_axi_bi_ARCACHE = 4'd0;

assign m_axi_bi_ARID = 1'd0;

assign m_axi_bi_ARLEN = 32'd1;

assign m_axi_bi_ARLOCK = 2'd0;

assign m_axi_bi_ARPROT = 3'd0;

assign m_axi_bi_ARQOS = 4'd0;

assign m_axi_bi_ARREGION = 4'd0;

assign m_axi_bi_ARSIZE = 3'd0;

assign m_axi_bi_ARUSER = 1'd0;

assign m_axi_bi_AWADDR = 32'd0;

assign m_axi_bi_AWBURST = 2'd0;

assign m_axi_bi_AWCACHE = 4'd0;

assign m_axi_bi_AWID = 1'd0;

assign m_axi_bi_AWLEN = 32'd0;

assign m_axi_bi_AWLOCK = 2'd0;

assign m_axi_bi_AWPROT = 3'd0;

assign m_axi_bi_AWQOS = 4'd0;

assign m_axi_bi_AWREGION = 4'd0;

assign m_axi_bi_AWSIZE = 3'd0;

assign m_axi_bi_AWUSER = 1'd0;

assign m_axi_bi_AWVALID = 1'b0;

assign m_axi_bi_BREADY = 1'b0;

assign m_axi_bi_WDATA = 64'd0;

assign m_axi_bi_WID = 1'd0;

assign m_axi_bi_WLAST = 1'b0;

assign m_axi_bi_WSTRB = 8'd0;

assign m_axi_bi_WUSER = 1'd0;

assign m_axi_bi_WVALID = 1'b0;

assign sext_ln126_fu_337_p1 = $signed(trunc_ln4_reg_465);

assign shl_ln1_fu_295_p3 = {{idx_fu_112}, {3'd0}};

assign trunc_ln129_1_fu_318_p1 = k_fu_116[7:0];

assign trunc_ln129_fu_347_p1 = m_axi_bi_RDATA[7:0];

assign zext_ln129_fu_421_p1 = trunc_ln129_1_reg_470_pp0_iter10_reg;

assign zext_ln196_cast_fu_260_p1 = zext_ln196;

assign zext_ln214_cast_fu_264_p1 = zext_ln214;

always @ (posedge ap_clk) begin
    zext_ln196_cast_reg_456[28:13] <= 16'b0000000000000000;
end

endmodule //mxm_execute_ursa_mxm_execute_ursa_Pipeline_LOAD_B
