// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="shell_top_shell_top,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=8872,HLS_SYN_LUT=10664,HLS_VERSION=2023_2}" *)

module shell_top (
        s_axi_ap_AWVALID,
        s_axi_ap_AWREADY,
        s_axi_ap_AWADDR,
        s_axi_ap_WVALID,
        s_axi_ap_WREADY,
        s_axi_ap_WDATA,
        s_axi_ap_WSTRB,
        s_axi_ap_ARVALID,
        s_axi_ap_ARREADY,
        s_axi_ap_ARADDR,
        s_axi_ap_RVALID,
        s_axi_ap_RREADY,
        s_axi_ap_RDATA,
        s_axi_ap_RRESP,
        s_axi_ap_BVALID,
        s_axi_ap_BREADY,
        s_axi_ap_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        m_axi_aw_AWVALID,
        m_axi_aw_AWREADY,
        m_axi_aw_AWADDR,
        m_axi_aw_AWID,
        m_axi_aw_AWLEN,
        m_axi_aw_AWSIZE,
        m_axi_aw_AWBURST,
        m_axi_aw_AWLOCK,
        m_axi_aw_AWCACHE,
        m_axi_aw_AWPROT,
        m_axi_aw_AWQOS,
        m_axi_aw_AWREGION,
        m_axi_aw_AWUSER,
        m_axi_aw_WVALID,
        m_axi_aw_WREADY,
        m_axi_aw_WDATA,
        m_axi_aw_WSTRB,
        m_axi_aw_WLAST,
        m_axi_aw_WID,
        m_axi_aw_WUSER,
        m_axi_aw_ARVALID,
        m_axi_aw_ARREADY,
        m_axi_aw_ARADDR,
        m_axi_aw_ARID,
        m_axi_aw_ARLEN,
        m_axi_aw_ARSIZE,
        m_axi_aw_ARBURST,
        m_axi_aw_ARLOCK,
        m_axi_aw_ARCACHE,
        m_axi_aw_ARPROT,
        m_axi_aw_ARQOS,
        m_axi_aw_ARREGION,
        m_axi_aw_ARUSER,
        m_axi_aw_RVALID,
        m_axi_aw_RREADY,
        m_axi_aw_RDATA,
        m_axi_aw_RLAST,
        m_axi_aw_RID,
        m_axi_aw_RUSER,
        m_axi_aw_RRESP,
        m_axi_aw_BVALID,
        m_axi_aw_BREADY,
        m_axi_aw_BRESP,
        m_axi_aw_BID,
        m_axi_aw_BUSER,
        m_axi_bi_AWVALID,
        m_axi_bi_AWREADY,
        m_axi_bi_AWADDR,
        m_axi_bi_AWID,
        m_axi_bi_AWLEN,
        m_axi_bi_AWSIZE,
        m_axi_bi_AWBURST,
        m_axi_bi_AWLOCK,
        m_axi_bi_AWCACHE,
        m_axi_bi_AWPROT,
        m_axi_bi_AWQOS,
        m_axi_bi_AWREGION,
        m_axi_bi_AWUSER,
        m_axi_bi_WVALID,
        m_axi_bi_WREADY,
        m_axi_bi_WDATA,
        m_axi_bi_WSTRB,
        m_axi_bi_WLAST,
        m_axi_bi_WID,
        m_axi_bi_WUSER,
        m_axi_bi_ARVALID,
        m_axi_bi_ARREADY,
        m_axi_bi_ARADDR,
        m_axi_bi_ARID,
        m_axi_bi_ARLEN,
        m_axi_bi_ARSIZE,
        m_axi_bi_ARBURST,
        m_axi_bi_ARLOCK,
        m_axi_bi_ARCACHE,
        m_axi_bi_ARPROT,
        m_axi_bi_ARQOS,
        m_axi_bi_ARREGION,
        m_axi_bi_ARUSER,
        m_axi_bi_RVALID,
        m_axi_bi_RREADY,
        m_axi_bi_RDATA,
        m_axi_bi_RLAST,
        m_axi_bi_RID,
        m_axi_bi_RUSER,
        m_axi_bi_RRESP,
        m_axi_bi_BVALID,
        m_axi_bi_BREADY,
        m_axi_bi_BRESP,
        m_axi_bi_BID,
        m_axi_bi_BUSER,
        m_axi_ca_AWVALID,
        m_axi_ca_AWREADY,
        m_axi_ca_AWADDR,
        m_axi_ca_AWID,
        m_axi_ca_AWLEN,
        m_axi_ca_AWSIZE,
        m_axi_ca_AWBURST,
        m_axi_ca_AWLOCK,
        m_axi_ca_AWCACHE,
        m_axi_ca_AWPROT,
        m_axi_ca_AWQOS,
        m_axi_ca_AWREGION,
        m_axi_ca_AWUSER,
        m_axi_ca_WVALID,
        m_axi_ca_WREADY,
        m_axi_ca_WDATA,
        m_axi_ca_WSTRB,
        m_axi_ca_WLAST,
        m_axi_ca_WID,
        m_axi_ca_WUSER,
        m_axi_ca_ARVALID,
        m_axi_ca_ARREADY,
        m_axi_ca_ARADDR,
        m_axi_ca_ARID,
        m_axi_ca_ARLEN,
        m_axi_ca_ARSIZE,
        m_axi_ca_ARBURST,
        m_axi_ca_ARLOCK,
        m_axi_ca_ARCACHE,
        m_axi_ca_ARPROT,
        m_axi_ca_ARQOS,
        m_axi_ca_ARREGION,
        m_axi_ca_ARUSER,
        m_axi_ca_RVALID,
        m_axi_ca_RREADY,
        m_axi_ca_RDATA,
        m_axi_ca_RLAST,
        m_axi_ca_RID,
        m_axi_ca_RUSER,
        m_axi_ca_RRESP,
        m_axi_ca_BVALID,
        m_axi_ca_BREADY,
        m_axi_ca_BRESP,
        m_axi_ca_BID,
        m_axi_ca_BUSER
);

parameter    C_S_AXI_AP_DATA_WIDTH = 32;
parameter    C_S_AXI_AP_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_M_AXI_AW_ID_WIDTH = 1;
parameter    C_M_AXI_AW_ADDR_WIDTH = 32;
parameter    C_M_AXI_AW_DATA_WIDTH = 32;
parameter    C_M_AXI_AW_AWUSER_WIDTH = 1;
parameter    C_M_AXI_AW_ARUSER_WIDTH = 1;
parameter    C_M_AXI_AW_WUSER_WIDTH = 1;
parameter    C_M_AXI_AW_RUSER_WIDTH = 1;
parameter    C_M_AXI_AW_BUSER_WIDTH = 1;
parameter    C_M_AXI_AW_USER_VALUE = 0;
parameter    C_M_AXI_AW_PROT_VALUE = 0;
parameter    C_M_AXI_AW_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BI_ID_WIDTH = 1;
parameter    C_M_AXI_BI_ADDR_WIDTH = 32;
parameter    C_M_AXI_BI_DATA_WIDTH = 32;
parameter    C_M_AXI_BI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BI_WUSER_WIDTH = 1;
parameter    C_M_AXI_BI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BI_BUSER_WIDTH = 1;
parameter    C_M_AXI_BI_USER_VALUE = 0;
parameter    C_M_AXI_BI_PROT_VALUE = 0;
parameter    C_M_AXI_BI_CACHE_VALUE = 3;
parameter    C_M_AXI_CA_ID_WIDTH = 1;
parameter    C_M_AXI_CA_ADDR_WIDTH = 32;
parameter    C_M_AXI_CA_DATA_WIDTH = 32;
parameter    C_M_AXI_CA_AWUSER_WIDTH = 1;
parameter    C_M_AXI_CA_ARUSER_WIDTH = 1;
parameter    C_M_AXI_CA_WUSER_WIDTH = 1;
parameter    C_M_AXI_CA_RUSER_WIDTH = 1;
parameter    C_M_AXI_CA_BUSER_WIDTH = 1;
parameter    C_M_AXI_CA_USER_VALUE = 0;
parameter    C_M_AXI_CA_PROT_VALUE = 0;
parameter    C_M_AXI_CA_CACHE_VALUE = 3;

parameter C_S_AXI_AP_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_AW_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_CA_WSTRB_WIDTH = (32 / 8);

input   s_axi_ap_AWVALID;
output   s_axi_ap_AWREADY;
input  [C_S_AXI_AP_ADDR_WIDTH - 1:0] s_axi_ap_AWADDR;
input   s_axi_ap_WVALID;
output   s_axi_ap_WREADY;
input  [C_S_AXI_AP_DATA_WIDTH - 1:0] s_axi_ap_WDATA;
input  [C_S_AXI_AP_WSTRB_WIDTH - 1:0] s_axi_ap_WSTRB;
input   s_axi_ap_ARVALID;
output   s_axi_ap_ARREADY;
input  [C_S_AXI_AP_ADDR_WIDTH - 1:0] s_axi_ap_ARADDR;
output   s_axi_ap_RVALID;
input   s_axi_ap_RREADY;
output  [C_S_AXI_AP_DATA_WIDTH - 1:0] s_axi_ap_RDATA;
output  [1:0] s_axi_ap_RRESP;
output   s_axi_ap_BVALID;
input   s_axi_ap_BREADY;
output  [1:0] s_axi_ap_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   m_axi_aw_AWVALID;
input   m_axi_aw_AWREADY;
output  [C_M_AXI_AW_ADDR_WIDTH - 1:0] m_axi_aw_AWADDR;
output  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_AWID;
output  [7:0] m_axi_aw_AWLEN;
output  [2:0] m_axi_aw_AWSIZE;
output  [1:0] m_axi_aw_AWBURST;
output  [1:0] m_axi_aw_AWLOCK;
output  [3:0] m_axi_aw_AWCACHE;
output  [2:0] m_axi_aw_AWPROT;
output  [3:0] m_axi_aw_AWQOS;
output  [3:0] m_axi_aw_AWREGION;
output  [C_M_AXI_AW_AWUSER_WIDTH - 1:0] m_axi_aw_AWUSER;
output   m_axi_aw_WVALID;
input   m_axi_aw_WREADY;
output  [C_M_AXI_AW_DATA_WIDTH - 1:0] m_axi_aw_WDATA;
output  [C_M_AXI_AW_WSTRB_WIDTH - 1:0] m_axi_aw_WSTRB;
output   m_axi_aw_WLAST;
output  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_WID;
output  [C_M_AXI_AW_WUSER_WIDTH - 1:0] m_axi_aw_WUSER;
output   m_axi_aw_ARVALID;
input   m_axi_aw_ARREADY;
output  [C_M_AXI_AW_ADDR_WIDTH - 1:0] m_axi_aw_ARADDR;
output  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_ARID;
output  [7:0] m_axi_aw_ARLEN;
output  [2:0] m_axi_aw_ARSIZE;
output  [1:0] m_axi_aw_ARBURST;
output  [1:0] m_axi_aw_ARLOCK;
output  [3:0] m_axi_aw_ARCACHE;
output  [2:0] m_axi_aw_ARPROT;
output  [3:0] m_axi_aw_ARQOS;
output  [3:0] m_axi_aw_ARREGION;
output  [C_M_AXI_AW_ARUSER_WIDTH - 1:0] m_axi_aw_ARUSER;
input   m_axi_aw_RVALID;
output   m_axi_aw_RREADY;
input  [C_M_AXI_AW_DATA_WIDTH - 1:0] m_axi_aw_RDATA;
input   m_axi_aw_RLAST;
input  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_RID;
input  [C_M_AXI_AW_RUSER_WIDTH - 1:0] m_axi_aw_RUSER;
input  [1:0] m_axi_aw_RRESP;
input   m_axi_aw_BVALID;
output   m_axi_aw_BREADY;
input  [1:0] m_axi_aw_BRESP;
input  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_BID;
input  [C_M_AXI_AW_BUSER_WIDTH - 1:0] m_axi_aw_BUSER;
output   m_axi_bi_AWVALID;
input   m_axi_bi_AWREADY;
output  [C_M_AXI_BI_ADDR_WIDTH - 1:0] m_axi_bi_AWADDR;
output  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_AWID;
output  [7:0] m_axi_bi_AWLEN;
output  [2:0] m_axi_bi_AWSIZE;
output  [1:0] m_axi_bi_AWBURST;
output  [1:0] m_axi_bi_AWLOCK;
output  [3:0] m_axi_bi_AWCACHE;
output  [2:0] m_axi_bi_AWPROT;
output  [3:0] m_axi_bi_AWQOS;
output  [3:0] m_axi_bi_AWREGION;
output  [C_M_AXI_BI_AWUSER_WIDTH - 1:0] m_axi_bi_AWUSER;
output   m_axi_bi_WVALID;
input   m_axi_bi_WREADY;
output  [C_M_AXI_BI_DATA_WIDTH - 1:0] m_axi_bi_WDATA;
output  [C_M_AXI_BI_WSTRB_WIDTH - 1:0] m_axi_bi_WSTRB;
output   m_axi_bi_WLAST;
output  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_WID;
output  [C_M_AXI_BI_WUSER_WIDTH - 1:0] m_axi_bi_WUSER;
output   m_axi_bi_ARVALID;
input   m_axi_bi_ARREADY;
output  [C_M_AXI_BI_ADDR_WIDTH - 1:0] m_axi_bi_ARADDR;
output  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_ARID;
output  [7:0] m_axi_bi_ARLEN;
output  [2:0] m_axi_bi_ARSIZE;
output  [1:0] m_axi_bi_ARBURST;
output  [1:0] m_axi_bi_ARLOCK;
output  [3:0] m_axi_bi_ARCACHE;
output  [2:0] m_axi_bi_ARPROT;
output  [3:0] m_axi_bi_ARQOS;
output  [3:0] m_axi_bi_ARREGION;
output  [C_M_AXI_BI_ARUSER_WIDTH - 1:0] m_axi_bi_ARUSER;
input   m_axi_bi_RVALID;
output   m_axi_bi_RREADY;
input  [C_M_AXI_BI_DATA_WIDTH - 1:0] m_axi_bi_RDATA;
input   m_axi_bi_RLAST;
input  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_RID;
input  [C_M_AXI_BI_RUSER_WIDTH - 1:0] m_axi_bi_RUSER;
input  [1:0] m_axi_bi_RRESP;
input   m_axi_bi_BVALID;
output   m_axi_bi_BREADY;
input  [1:0] m_axi_bi_BRESP;
input  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_BID;
input  [C_M_AXI_BI_BUSER_WIDTH - 1:0] m_axi_bi_BUSER;
output   m_axi_ca_AWVALID;
input   m_axi_ca_AWREADY;
output  [C_M_AXI_CA_ADDR_WIDTH - 1:0] m_axi_ca_AWADDR;
output  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_AWID;
output  [7:0] m_axi_ca_AWLEN;
output  [2:0] m_axi_ca_AWSIZE;
output  [1:0] m_axi_ca_AWBURST;
output  [1:0] m_axi_ca_AWLOCK;
output  [3:0] m_axi_ca_AWCACHE;
output  [2:0] m_axi_ca_AWPROT;
output  [3:0] m_axi_ca_AWQOS;
output  [3:0] m_axi_ca_AWREGION;
output  [C_M_AXI_CA_AWUSER_WIDTH - 1:0] m_axi_ca_AWUSER;
output   m_axi_ca_WVALID;
input   m_axi_ca_WREADY;
output  [C_M_AXI_CA_DATA_WIDTH - 1:0] m_axi_ca_WDATA;
output  [C_M_AXI_CA_WSTRB_WIDTH - 1:0] m_axi_ca_WSTRB;
output   m_axi_ca_WLAST;
output  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_WID;
output  [C_M_AXI_CA_WUSER_WIDTH - 1:0] m_axi_ca_WUSER;
output   m_axi_ca_ARVALID;
input   m_axi_ca_ARREADY;
output  [C_M_AXI_CA_ADDR_WIDTH - 1:0] m_axi_ca_ARADDR;
output  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_ARID;
output  [7:0] m_axi_ca_ARLEN;
output  [2:0] m_axi_ca_ARSIZE;
output  [1:0] m_axi_ca_ARBURST;
output  [1:0] m_axi_ca_ARLOCK;
output  [3:0] m_axi_ca_ARCACHE;
output  [2:0] m_axi_ca_ARPROT;
output  [3:0] m_axi_ca_ARQOS;
output  [3:0] m_axi_ca_ARREGION;
output  [C_M_AXI_CA_ARUSER_WIDTH - 1:0] m_axi_ca_ARUSER;
input   m_axi_ca_RVALID;
output   m_axi_ca_RREADY;
input  [C_M_AXI_CA_DATA_WIDTH - 1:0] m_axi_ca_RDATA;
input   m_axi_ca_RLAST;
input  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_RID;
input  [C_M_AXI_CA_RUSER_WIDTH - 1:0] m_axi_ca_RUSER;
input  [1:0] m_axi_ca_RRESP;
input   m_axi_ca_BVALID;
output   m_axi_ca_BREADY;
input  [1:0] m_axi_ca_BRESP;
input  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_BID;
input  [C_M_AXI_CA_BUSER_WIDTH - 1:0] m_axi_ca_BUSER;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [15:0] a0_p;
wire   [15:0] b0_q;
wire   [15:0] m;
wire   [31:0] addr_a0;
wire   [31:0] addr_b0;
wire   [31:0] addr_c0;
wire    aw_AWREADY;
wire    aw_WREADY;
wire    aw_ARREADY;
wire    aw_RVALID;
wire   [7:0] aw_RDATA;
wire    aw_RLAST;
wire   [0:0] aw_RID;
wire   [9:0] aw_RFIFONUM;
wire   [0:0] aw_RUSER;
wire   [1:0] aw_RRESP;
wire    aw_BVALID;
wire    bi_AWREADY;
wire    bi_WREADY;
wire    bi_ARREADY;
wire    bi_RVALID;
wire   [7:0] bi_RDATA;
wire    bi_RLAST;
wire   [0:0] bi_RID;
wire   [9:0] bi_RFIFONUM;
wire   [0:0] bi_RUSER;
wire   [1:0] bi_RRESP;
wire    bi_BVALID;
wire    ca_AWREADY;
wire    ca_WREADY;
wire    ca_ARREADY;
wire    ca_RVALID;
wire   [31:0] ca_RDATA;
wire   [7:0] ca_RFIFONUM;
wire    ca_BVALID;
wire   [1:0] ca_BRESP;
wire   [0:0] ca_BID;
wire   [0:0] ca_BUSER;
wire    Block_entry61_proc_U0_ap_start;
wire    Block_entry61_proc_U0_ap_done;
wire    Block_entry61_proc_U0_ap_continue;
wire    Block_entry61_proc_U0_ap_idle;
wire    Block_entry61_proc_U0_ap_ready;
wire   [12:0] Block_entry61_proc_U0_ap_return_0;
wire   [31:0] Block_entry61_proc_U0_ap_return_1;
wire   [12:0] Block_entry61_proc_U0_ap_return_2;
wire   [18:0] Block_entry61_proc_U0_ap_return_3;
wire   [17:0] Block_entry61_proc_U0_ap_return_4;
wire   [16:0] Block_entry61_proc_U0_ap_return_5;
wire   [16:0] Block_entry61_proc_U0_ap_return_6;
wire    ap_channel_done_sub24_loc_channel;
wire    sub24_loc_channel_full_n;
reg    ap_sync_reg_channel_write_sub24_loc_channel;
wire    ap_sync_channel_write_sub24_loc_channel;
wire    ap_channel_done_m_cast_loc_channel;
wire    m_cast_loc_channel_full_n;
reg    ap_sync_reg_channel_write_m_cast_loc_channel;
wire    ap_sync_channel_write_m_cast_loc_channel;
wire    ap_channel_done_m_cast8_loc_channel;
wire    m_cast8_loc_channel_full_n;
reg    ap_sync_reg_channel_write_m_cast8_loc_channel;
wire    ap_sync_channel_write_m_cast8_loc_channel;
wire    ap_channel_done_m_cast10_loc_channel;
wire    m_cast10_loc_channel_full_n;
reg    ap_sync_reg_channel_write_m_cast10_loc_channel;
wire    ap_sync_channel_write_m_cast10_loc_channel;
wire    ap_channel_done_call_b_cast_loc_channel;
wire    call_b_cast_loc_channel_full_n;
reg    ap_sync_reg_channel_write_call_b_cast_loc_channel;
wire    ap_sync_channel_write_call_b_cast_loc_channel;
wire    ap_channel_done_zext_ln142_loc_channel;
wire    zext_ln142_loc_channel_full_n;
reg    ap_sync_reg_channel_write_zext_ln142_loc_channel;
wire    ap_sync_channel_write_zext_ln142_loc_channel;
wire    ap_channel_done_call_a_cast_loc_channel;
wire    call_a_cast_loc_channel_full_n;
reg    ap_sync_reg_channel_write_call_a_cast_loc_channel;
wire    ap_sync_channel_write_call_a_cast_loc_channel;
wire    Loop_VITIS_LOOP_144_1_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_144_1_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_144_1_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_144_1_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_144_1_proc_U0_ap_ready;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWVALID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WVALID;
wire   [7:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WDATA;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WSTRB;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WLAST;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WID;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARVALID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_RREADY;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_BREADY;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWVALID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WVALID;
wire   [7:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WDATA;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WSTRB;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WLAST;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WID;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARVALID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_RREADY;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_BREADY;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWVALID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WVALID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WDATA;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WSTRB;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WLAST;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WID;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARVALID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARID;
wire   [31:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARUSER;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_RREADY;
wire    Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_BREADY;
wire   [12:0] call_a_cast_loc_channel_dout;
wire   [2:0] call_a_cast_loc_channel_num_data_valid;
wire   [2:0] call_a_cast_loc_channel_fifo_cap;
wire    call_a_cast_loc_channel_empty_n;
wire   [31:0] zext_ln142_loc_channel_dout;
wire   [2:0] zext_ln142_loc_channel_num_data_valid;
wire   [2:0] zext_ln142_loc_channel_fifo_cap;
wire    zext_ln142_loc_channel_empty_n;
wire   [12:0] call_b_cast_loc_channel_dout;
wire   [2:0] call_b_cast_loc_channel_num_data_valid;
wire   [2:0] call_b_cast_loc_channel_fifo_cap;
wire    call_b_cast_loc_channel_empty_n;
wire   [18:0] m_cast10_loc_channel_dout;
wire   [2:0] m_cast10_loc_channel_num_data_valid;
wire   [2:0] m_cast10_loc_channel_fifo_cap;
wire    m_cast10_loc_channel_empty_n;
wire   [17:0] m_cast8_loc_channel_dout;
wire   [2:0] m_cast8_loc_channel_num_data_valid;
wire   [2:0] m_cast8_loc_channel_fifo_cap;
wire    m_cast8_loc_channel_empty_n;
wire   [16:0] m_cast_loc_channel_dout;
wire   [2:0] m_cast_loc_channel_num_data_valid;
wire   [2:0] m_cast_loc_channel_fifo_cap;
wire    m_cast_loc_channel_empty_n;
wire   [16:0] sub24_loc_channel_dout;
wire   [2:0] sub24_loc_channel_num_data_valid;
wire   [2:0] sub24_loc_channel_fifo_cap;
wire    sub24_loc_channel_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_entry61_proc_U0_ap_ready;
wire    ap_sync_Block_entry61_proc_U0_ap_ready;
reg    ap_sync_reg_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready;
wire    ap_sync_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready;
wire    ap_ce_reg;
wire   [7:0] ap_return;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_sub24_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_m_cast_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_m_cast8_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_m_cast10_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_call_b_cast_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_zext_ln142_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_call_a_cast_loc_channel = 1'b0;
#0 ap_sync_reg_Block_entry61_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready = 1'b0;
end

shell_top_ap_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AP_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AP_DATA_WIDTH ))
ap_s_axi_U(
    .AWVALID(s_axi_ap_AWVALID),
    .AWREADY(s_axi_ap_AWREADY),
    .AWADDR(s_axi_ap_AWADDR),
    .WVALID(s_axi_ap_WVALID),
    .WREADY(s_axi_ap_WREADY),
    .WDATA(s_axi_ap_WDATA),
    .WSTRB(s_axi_ap_WSTRB),
    .ARVALID(s_axi_ap_ARVALID),
    .ARREADY(s_axi_ap_ARREADY),
    .ARADDR(s_axi_ap_ARADDR),
    .RVALID(s_axi_ap_RVALID),
    .RREADY(s_axi_ap_RREADY),
    .RDATA(s_axi_ap_RDATA),
    .RRESP(s_axi_ap_RRESP),
    .BVALID(s_axi_ap_BVALID),
    .BREADY(s_axi_ap_BREADY),
    .BRESP(s_axi_ap_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(8'd0),
    .a0_p(a0_p),
    .b0_q(b0_q),
    .m(m)
);

shell_top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .addr_a0(addr_a0),
    .addr_b0(addr_b0),
    .addr_c0(addr_c0)
);

shell_top_aw_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_AW_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_AW_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_AW_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_AW_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_AW_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_AW_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_AW_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_AW_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_AW_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_AW_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_AW_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 8 ),
    .NUM_WRITE_OUTSTANDING( 8 ))
aw_m_axi_U(
    .AWVALID(m_axi_aw_AWVALID),
    .AWREADY(m_axi_aw_AWREADY),
    .AWADDR(m_axi_aw_AWADDR),
    .AWID(m_axi_aw_AWID),
    .AWLEN(m_axi_aw_AWLEN),
    .AWSIZE(m_axi_aw_AWSIZE),
    .AWBURST(m_axi_aw_AWBURST),
    .AWLOCK(m_axi_aw_AWLOCK),
    .AWCACHE(m_axi_aw_AWCACHE),
    .AWPROT(m_axi_aw_AWPROT),
    .AWQOS(m_axi_aw_AWQOS),
    .AWREGION(m_axi_aw_AWREGION),
    .AWUSER(m_axi_aw_AWUSER),
    .WVALID(m_axi_aw_WVALID),
    .WREADY(m_axi_aw_WREADY),
    .WDATA(m_axi_aw_WDATA),
    .WSTRB(m_axi_aw_WSTRB),
    .WLAST(m_axi_aw_WLAST),
    .WID(m_axi_aw_WID),
    .WUSER(m_axi_aw_WUSER),
    .ARVALID(m_axi_aw_ARVALID),
    .ARREADY(m_axi_aw_ARREADY),
    .ARADDR(m_axi_aw_ARADDR),
    .ARID(m_axi_aw_ARID),
    .ARLEN(m_axi_aw_ARLEN),
    .ARSIZE(m_axi_aw_ARSIZE),
    .ARBURST(m_axi_aw_ARBURST),
    .ARLOCK(m_axi_aw_ARLOCK),
    .ARCACHE(m_axi_aw_ARCACHE),
    .ARPROT(m_axi_aw_ARPROT),
    .ARQOS(m_axi_aw_ARQOS),
    .ARREGION(m_axi_aw_ARREGION),
    .ARUSER(m_axi_aw_ARUSER),
    .RVALID(m_axi_aw_RVALID),
    .RREADY(m_axi_aw_RREADY),
    .RDATA(m_axi_aw_RDATA),
    .RLAST(m_axi_aw_RLAST),
    .RID(m_axi_aw_RID),
    .RUSER(m_axi_aw_RUSER),
    .RRESP(m_axi_aw_RRESP),
    .BVALID(m_axi_aw_BVALID),
    .BREADY(m_axi_aw_BREADY),
    .BRESP(m_axi_aw_BRESP),
    .BID(m_axi_aw_BID),
    .BUSER(m_axi_aw_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARVALID),
    .I_ARREADY(aw_ARREADY),
    .I_ARADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARADDR),
    .I_ARLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARLEN),
    .I_RVALID(aw_RVALID),
    .I_RREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_RREADY),
    .I_RDATA(aw_RDATA),
    .I_RFIFONUM(aw_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(aw_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(aw_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(aw_BVALID),
    .I_BREADY(1'b0)
);

shell_top_bi_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BI_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BI_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BI_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BI_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BI_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BI_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BI_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BI_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BI_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BI_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BI_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 8 ),
    .NUM_WRITE_OUTSTANDING( 8 ))
bi_m_axi_U(
    .AWVALID(m_axi_bi_AWVALID),
    .AWREADY(m_axi_bi_AWREADY),
    .AWADDR(m_axi_bi_AWADDR),
    .AWID(m_axi_bi_AWID),
    .AWLEN(m_axi_bi_AWLEN),
    .AWSIZE(m_axi_bi_AWSIZE),
    .AWBURST(m_axi_bi_AWBURST),
    .AWLOCK(m_axi_bi_AWLOCK),
    .AWCACHE(m_axi_bi_AWCACHE),
    .AWPROT(m_axi_bi_AWPROT),
    .AWQOS(m_axi_bi_AWQOS),
    .AWREGION(m_axi_bi_AWREGION),
    .AWUSER(m_axi_bi_AWUSER),
    .WVALID(m_axi_bi_WVALID),
    .WREADY(m_axi_bi_WREADY),
    .WDATA(m_axi_bi_WDATA),
    .WSTRB(m_axi_bi_WSTRB),
    .WLAST(m_axi_bi_WLAST),
    .WID(m_axi_bi_WID),
    .WUSER(m_axi_bi_WUSER),
    .ARVALID(m_axi_bi_ARVALID),
    .ARREADY(m_axi_bi_ARREADY),
    .ARADDR(m_axi_bi_ARADDR),
    .ARID(m_axi_bi_ARID),
    .ARLEN(m_axi_bi_ARLEN),
    .ARSIZE(m_axi_bi_ARSIZE),
    .ARBURST(m_axi_bi_ARBURST),
    .ARLOCK(m_axi_bi_ARLOCK),
    .ARCACHE(m_axi_bi_ARCACHE),
    .ARPROT(m_axi_bi_ARPROT),
    .ARQOS(m_axi_bi_ARQOS),
    .ARREGION(m_axi_bi_ARREGION),
    .ARUSER(m_axi_bi_ARUSER),
    .RVALID(m_axi_bi_RVALID),
    .RREADY(m_axi_bi_RREADY),
    .RDATA(m_axi_bi_RDATA),
    .RLAST(m_axi_bi_RLAST),
    .RID(m_axi_bi_RID),
    .RUSER(m_axi_bi_RUSER),
    .RRESP(m_axi_bi_RRESP),
    .BVALID(m_axi_bi_BVALID),
    .BREADY(m_axi_bi_BREADY),
    .BRESP(m_axi_bi_BRESP),
    .BID(m_axi_bi_BID),
    .BUSER(m_axi_bi_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARVALID),
    .I_ARREADY(bi_ARREADY),
    .I_ARADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARADDR),
    .I_ARLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARLEN),
    .I_RVALID(bi_RVALID),
    .I_RREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_RREADY),
    .I_RDATA(bi_RDATA),
    .I_RFIFONUM(bi_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(bi_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bi_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(bi_BVALID),
    .I_BREADY(1'b0)
);

shell_top_ca_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_CA_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_CA_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_CA_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_CA_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_CA_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_CA_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_CA_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_CA_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_CA_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_CA_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_CA_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 8 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 8 ),
    .NUM_WRITE_OUTSTANDING( 8 ))
ca_m_axi_U(
    .AWVALID(m_axi_ca_AWVALID),
    .AWREADY(m_axi_ca_AWREADY),
    .AWADDR(m_axi_ca_AWADDR),
    .AWID(m_axi_ca_AWID),
    .AWLEN(m_axi_ca_AWLEN),
    .AWSIZE(m_axi_ca_AWSIZE),
    .AWBURST(m_axi_ca_AWBURST),
    .AWLOCK(m_axi_ca_AWLOCK),
    .AWCACHE(m_axi_ca_AWCACHE),
    .AWPROT(m_axi_ca_AWPROT),
    .AWQOS(m_axi_ca_AWQOS),
    .AWREGION(m_axi_ca_AWREGION),
    .AWUSER(m_axi_ca_AWUSER),
    .WVALID(m_axi_ca_WVALID),
    .WREADY(m_axi_ca_WREADY),
    .WDATA(m_axi_ca_WDATA),
    .WSTRB(m_axi_ca_WSTRB),
    .WLAST(m_axi_ca_WLAST),
    .WID(m_axi_ca_WID),
    .WUSER(m_axi_ca_WUSER),
    .ARVALID(m_axi_ca_ARVALID),
    .ARREADY(m_axi_ca_ARREADY),
    .ARADDR(m_axi_ca_ARADDR),
    .ARID(m_axi_ca_ARID),
    .ARLEN(m_axi_ca_ARLEN),
    .ARSIZE(m_axi_ca_ARSIZE),
    .ARBURST(m_axi_ca_ARBURST),
    .ARLOCK(m_axi_ca_ARLOCK),
    .ARCACHE(m_axi_ca_ARCACHE),
    .ARPROT(m_axi_ca_ARPROT),
    .ARQOS(m_axi_ca_ARQOS),
    .ARREGION(m_axi_ca_ARREGION),
    .ARUSER(m_axi_ca_ARUSER),
    .RVALID(m_axi_ca_RVALID),
    .RREADY(m_axi_ca_RREADY),
    .RDATA(m_axi_ca_RDATA),
    .RLAST(m_axi_ca_RLAST),
    .RID(m_axi_ca_RID),
    .RUSER(m_axi_ca_RUSER),
    .RRESP(m_axi_ca_RRESP),
    .BVALID(m_axi_ca_BVALID),
    .BREADY(m_axi_ca_BREADY),
    .BRESP(m_axi_ca_BRESP),
    .BID(m_axi_ca_BID),
    .BUSER(m_axi_ca_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(ca_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(ca_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(ca_RDATA),
    .I_RFIFONUM(ca_RFIFONUM),
    .I_AWVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWVALID),
    .I_AWREADY(ca_AWREADY),
    .I_AWADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWADDR),
    .I_AWLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWLEN),
    .I_WVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WVALID),
    .I_WREADY(ca_WREADY),
    .I_WDATA(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WDATA),
    .I_WSTRB(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WSTRB),
    .I_BVALID(ca_BVALID),
    .I_BREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_BREADY)
);

shell_top_Block_entry61_proc Block_entry61_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry61_proc_U0_ap_start),
    .ap_done(Block_entry61_proc_U0_ap_done),
    .ap_continue(Block_entry61_proc_U0_ap_continue),
    .ap_idle(Block_entry61_proc_U0_ap_idle),
    .ap_ready(Block_entry61_proc_U0_ap_ready),
    .a0_p(a0_p),
    .b0_q(b0_q),
    .m(m),
    .ap_return_0(Block_entry61_proc_U0_ap_return_0),
    .ap_return_1(Block_entry61_proc_U0_ap_return_1),
    .ap_return_2(Block_entry61_proc_U0_ap_return_2),
    .ap_return_3(Block_entry61_proc_U0_ap_return_3),
    .ap_return_4(Block_entry61_proc_U0_ap_return_4),
    .ap_return_5(Block_entry61_proc_U0_ap_return_5),
    .ap_return_6(Block_entry61_proc_U0_ap_return_6)
);

shell_top_Loop_VITIS_LOOP_144_1_proc Loop_VITIS_LOOP_144_1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_144_1_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_144_1_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_144_1_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_144_1_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready),
    .p_read(call_a_cast_loc_channel_dout),
    .p_read1(call_b_cast_loc_channel_dout),
    .m(m),
    .b0_q(b0_q),
    .addr_c0(addr_c0),
    .p_read2(sub24_loc_channel_dout),
    .p_read3(zext_ln142_loc_channel_dout),
    .p_read4(m_cast_loc_channel_dout),
    .p_read5(m_cast10_loc_channel_dout),
    .p_read6(m_cast8_loc_channel_dout),
    .addr_a0(addr_a0),
    .m_axi_aw_AWVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWVALID),
    .m_axi_aw_AWREADY(1'b0),
    .m_axi_aw_AWADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWADDR),
    .m_axi_aw_AWID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWID),
    .m_axi_aw_AWLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWLEN),
    .m_axi_aw_AWSIZE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWSIZE),
    .m_axi_aw_AWBURST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWBURST),
    .m_axi_aw_AWLOCK(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWLOCK),
    .m_axi_aw_AWCACHE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWCACHE),
    .m_axi_aw_AWPROT(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWPROT),
    .m_axi_aw_AWQOS(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWQOS),
    .m_axi_aw_AWREGION(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWREGION),
    .m_axi_aw_AWUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_AWUSER),
    .m_axi_aw_WVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WVALID),
    .m_axi_aw_WREADY(1'b0),
    .m_axi_aw_WDATA(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WDATA),
    .m_axi_aw_WSTRB(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WSTRB),
    .m_axi_aw_WLAST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WLAST),
    .m_axi_aw_WID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WID),
    .m_axi_aw_WUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_WUSER),
    .m_axi_aw_ARVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARVALID),
    .m_axi_aw_ARREADY(aw_ARREADY),
    .m_axi_aw_ARADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARADDR),
    .m_axi_aw_ARID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARID),
    .m_axi_aw_ARLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARLEN),
    .m_axi_aw_ARSIZE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARSIZE),
    .m_axi_aw_ARBURST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARBURST),
    .m_axi_aw_ARLOCK(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARLOCK),
    .m_axi_aw_ARCACHE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARCACHE),
    .m_axi_aw_ARPROT(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARPROT),
    .m_axi_aw_ARQOS(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARQOS),
    .m_axi_aw_ARREGION(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARREGION),
    .m_axi_aw_ARUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_ARUSER),
    .m_axi_aw_RVALID(aw_RVALID),
    .m_axi_aw_RREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_RREADY),
    .m_axi_aw_RDATA(aw_RDATA),
    .m_axi_aw_RLAST(aw_RLAST),
    .m_axi_aw_RID(aw_RID),
    .m_axi_aw_RFIFONUM(aw_RFIFONUM),
    .m_axi_aw_RUSER(aw_RUSER),
    .m_axi_aw_RRESP(aw_RRESP),
    .m_axi_aw_BVALID(1'b0),
    .m_axi_aw_BREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_aw_BREADY),
    .m_axi_aw_BRESP(2'd0),
    .m_axi_aw_BID(1'd0),
    .m_axi_aw_BUSER(1'd0),
    .addr_b0(addr_b0),
    .m_axi_bi_AWVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWVALID),
    .m_axi_bi_AWREADY(1'b0),
    .m_axi_bi_AWADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWADDR),
    .m_axi_bi_AWID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWID),
    .m_axi_bi_AWLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWLEN),
    .m_axi_bi_AWSIZE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWSIZE),
    .m_axi_bi_AWBURST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWBURST),
    .m_axi_bi_AWLOCK(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWLOCK),
    .m_axi_bi_AWCACHE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWCACHE),
    .m_axi_bi_AWPROT(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWPROT),
    .m_axi_bi_AWQOS(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWQOS),
    .m_axi_bi_AWREGION(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWREGION),
    .m_axi_bi_AWUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_AWUSER),
    .m_axi_bi_WVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WVALID),
    .m_axi_bi_WREADY(1'b0),
    .m_axi_bi_WDATA(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WDATA),
    .m_axi_bi_WSTRB(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WSTRB),
    .m_axi_bi_WLAST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WLAST),
    .m_axi_bi_WID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WID),
    .m_axi_bi_WUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_WUSER),
    .m_axi_bi_ARVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARVALID),
    .m_axi_bi_ARREADY(bi_ARREADY),
    .m_axi_bi_ARADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARADDR),
    .m_axi_bi_ARID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARID),
    .m_axi_bi_ARLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARLEN),
    .m_axi_bi_ARSIZE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARSIZE),
    .m_axi_bi_ARBURST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARBURST),
    .m_axi_bi_ARLOCK(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARLOCK),
    .m_axi_bi_ARCACHE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARCACHE),
    .m_axi_bi_ARPROT(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARPROT),
    .m_axi_bi_ARQOS(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARQOS),
    .m_axi_bi_ARREGION(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARREGION),
    .m_axi_bi_ARUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_ARUSER),
    .m_axi_bi_RVALID(bi_RVALID),
    .m_axi_bi_RREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_RREADY),
    .m_axi_bi_RDATA(bi_RDATA),
    .m_axi_bi_RLAST(bi_RLAST),
    .m_axi_bi_RID(bi_RID),
    .m_axi_bi_RFIFONUM(bi_RFIFONUM),
    .m_axi_bi_RUSER(bi_RUSER),
    .m_axi_bi_RRESP(bi_RRESP),
    .m_axi_bi_BVALID(1'b0),
    .m_axi_bi_BREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_bi_BREADY),
    .m_axi_bi_BRESP(2'd0),
    .m_axi_bi_BID(1'd0),
    .m_axi_bi_BUSER(1'd0),
    .m_axi_ca_AWVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWVALID),
    .m_axi_ca_AWREADY(ca_AWREADY),
    .m_axi_ca_AWADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWADDR),
    .m_axi_ca_AWID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWID),
    .m_axi_ca_AWLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWLEN),
    .m_axi_ca_AWSIZE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWSIZE),
    .m_axi_ca_AWBURST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWBURST),
    .m_axi_ca_AWLOCK(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWLOCK),
    .m_axi_ca_AWCACHE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWCACHE),
    .m_axi_ca_AWPROT(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWPROT),
    .m_axi_ca_AWQOS(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWQOS),
    .m_axi_ca_AWREGION(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWREGION),
    .m_axi_ca_AWUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_AWUSER),
    .m_axi_ca_WVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WVALID),
    .m_axi_ca_WREADY(ca_WREADY),
    .m_axi_ca_WDATA(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WDATA),
    .m_axi_ca_WSTRB(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WSTRB),
    .m_axi_ca_WLAST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WLAST),
    .m_axi_ca_WID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WID),
    .m_axi_ca_WUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_WUSER),
    .m_axi_ca_ARVALID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARVALID),
    .m_axi_ca_ARREADY(1'b0),
    .m_axi_ca_ARADDR(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARADDR),
    .m_axi_ca_ARID(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARID),
    .m_axi_ca_ARLEN(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARLEN),
    .m_axi_ca_ARSIZE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARSIZE),
    .m_axi_ca_ARBURST(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARBURST),
    .m_axi_ca_ARLOCK(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARLOCK),
    .m_axi_ca_ARCACHE(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARCACHE),
    .m_axi_ca_ARPROT(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARPROT),
    .m_axi_ca_ARQOS(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARQOS),
    .m_axi_ca_ARREGION(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARREGION),
    .m_axi_ca_ARUSER(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_ARUSER),
    .m_axi_ca_RVALID(1'b0),
    .m_axi_ca_RREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_RREADY),
    .m_axi_ca_RDATA(32'd0),
    .m_axi_ca_RLAST(1'b0),
    .m_axi_ca_RID(1'd0),
    .m_axi_ca_RFIFONUM(8'd0),
    .m_axi_ca_RUSER(1'd0),
    .m_axi_ca_RRESP(2'd0),
    .m_axi_ca_BVALID(ca_BVALID),
    .m_axi_ca_BREADY(Loop_VITIS_LOOP_144_1_proc_U0_m_axi_ca_BREADY),
    .m_axi_ca_BRESP(ca_BRESP),
    .m_axi_ca_BID(ca_BID),
    .m_axi_ca_BUSER(ca_BUSER)
);

shell_top_fifo_w13_d2_S call_a_cast_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry61_proc_U0_ap_return_0),
    .if_full_n(call_a_cast_loc_channel_full_n),
    .if_write(ap_channel_done_call_a_cast_loc_channel),
    .if_dout(call_a_cast_loc_channel_dout),
    .if_num_data_valid(call_a_cast_loc_channel_num_data_valid),
    .if_fifo_cap(call_a_cast_loc_channel_fifo_cap),
    .if_empty_n(call_a_cast_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready)
);

shell_top_fifo_w32_d2_S zext_ln142_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry61_proc_U0_ap_return_1),
    .if_full_n(zext_ln142_loc_channel_full_n),
    .if_write(ap_channel_done_zext_ln142_loc_channel),
    .if_dout(zext_ln142_loc_channel_dout),
    .if_num_data_valid(zext_ln142_loc_channel_num_data_valid),
    .if_fifo_cap(zext_ln142_loc_channel_fifo_cap),
    .if_empty_n(zext_ln142_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready)
);

shell_top_fifo_w13_d2_S call_b_cast_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry61_proc_U0_ap_return_2),
    .if_full_n(call_b_cast_loc_channel_full_n),
    .if_write(ap_channel_done_call_b_cast_loc_channel),
    .if_dout(call_b_cast_loc_channel_dout),
    .if_num_data_valid(call_b_cast_loc_channel_num_data_valid),
    .if_fifo_cap(call_b_cast_loc_channel_fifo_cap),
    .if_empty_n(call_b_cast_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready)
);

shell_top_fifo_w19_d2_S m_cast10_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry61_proc_U0_ap_return_3),
    .if_full_n(m_cast10_loc_channel_full_n),
    .if_write(ap_channel_done_m_cast10_loc_channel),
    .if_dout(m_cast10_loc_channel_dout),
    .if_num_data_valid(m_cast10_loc_channel_num_data_valid),
    .if_fifo_cap(m_cast10_loc_channel_fifo_cap),
    .if_empty_n(m_cast10_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready)
);

shell_top_fifo_w18_d2_S m_cast8_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry61_proc_U0_ap_return_4),
    .if_full_n(m_cast8_loc_channel_full_n),
    .if_write(ap_channel_done_m_cast8_loc_channel),
    .if_dout(m_cast8_loc_channel_dout),
    .if_num_data_valid(m_cast8_loc_channel_num_data_valid),
    .if_fifo_cap(m_cast8_loc_channel_fifo_cap),
    .if_empty_n(m_cast8_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready)
);

shell_top_fifo_w17_d2_S m_cast_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry61_proc_U0_ap_return_5),
    .if_full_n(m_cast_loc_channel_full_n),
    .if_write(ap_channel_done_m_cast_loc_channel),
    .if_dout(m_cast_loc_channel_dout),
    .if_num_data_valid(m_cast_loc_channel_num_data_valid),
    .if_fifo_cap(m_cast_loc_channel_fifo_cap),
    .if_empty_n(m_cast_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready)
);

shell_top_fifo_w17_d2_S sub24_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry61_proc_U0_ap_return_6),
    .if_full_n(sub24_loc_channel_full_n),
    .if_write(ap_channel_done_sub24_loc_channel),
    .if_dout(sub24_loc_channel_dout),
    .if_num_data_valid(sub24_loc_channel_num_data_valid),
    .if_fifo_cap(sub24_loc_channel_fifo_cap),
    .if_empty_n(sub24_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_144_1_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_entry61_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_entry61_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_entry61_proc_U0_ap_ready <= ap_sync_Block_entry61_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_call_a_cast_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry61_proc_U0_ap_done & Block_entry61_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_call_a_cast_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_call_a_cast_loc_channel <= ap_sync_channel_write_call_a_cast_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_call_b_cast_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry61_proc_U0_ap_done & Block_entry61_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_call_b_cast_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_call_b_cast_loc_channel <= ap_sync_channel_write_call_b_cast_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_m_cast10_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry61_proc_U0_ap_done & Block_entry61_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_m_cast10_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_m_cast10_loc_channel <= ap_sync_channel_write_m_cast10_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_m_cast8_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry61_proc_U0_ap_done & Block_entry61_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_m_cast8_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_m_cast8_loc_channel <= ap_sync_channel_write_m_cast8_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_m_cast_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry61_proc_U0_ap_done & Block_entry61_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_m_cast_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_m_cast_loc_channel <= ap_sync_channel_write_m_cast_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_sub24_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry61_proc_U0_ap_done & Block_entry61_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_sub24_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_sub24_loc_channel <= ap_sync_channel_write_sub24_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_zext_ln142_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry61_proc_U0_ap_done & Block_entry61_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_zext_ln142_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_zext_ln142_loc_channel <= ap_sync_channel_write_zext_ln142_loc_channel;
        end
    end
end

assign Block_entry61_proc_U0_ap_continue = (ap_sync_channel_write_zext_ln142_loc_channel & ap_sync_channel_write_sub24_loc_channel & ap_sync_channel_write_m_cast_loc_channel & ap_sync_channel_write_m_cast8_loc_channel & ap_sync_channel_write_m_cast10_loc_channel & ap_sync_channel_write_call_b_cast_loc_channel & ap_sync_channel_write_call_a_cast_loc_channel);

assign Block_entry61_proc_U0_ap_start = ((ap_sync_reg_Block_entry61_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_VITIS_LOOP_144_1_proc_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_144_1_proc_U0_ap_start = (zext_ln142_loc_channel_empty_n & sub24_loc_channel_empty_n & m_cast_loc_channel_empty_n & m_cast8_loc_channel_empty_n & m_cast10_loc_channel_empty_n & (ap_sync_reg_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready ^ 1'b1) & call_b_cast_loc_channel_empty_n & call_a_cast_loc_channel_empty_n & ap_start);

assign ap_channel_done_call_a_cast_loc_channel = ((ap_sync_reg_channel_write_call_a_cast_loc_channel ^ 1'b1) & Block_entry61_proc_U0_ap_done);

assign ap_channel_done_call_b_cast_loc_channel = ((ap_sync_reg_channel_write_call_b_cast_loc_channel ^ 1'b1) & Block_entry61_proc_U0_ap_done);

assign ap_channel_done_m_cast10_loc_channel = ((ap_sync_reg_channel_write_m_cast10_loc_channel ^ 1'b1) & Block_entry61_proc_U0_ap_done);

assign ap_channel_done_m_cast8_loc_channel = ((ap_sync_reg_channel_write_m_cast8_loc_channel ^ 1'b1) & Block_entry61_proc_U0_ap_done);

assign ap_channel_done_m_cast_loc_channel = ((ap_sync_reg_channel_write_m_cast_loc_channel ^ 1'b1) & Block_entry61_proc_U0_ap_done);

assign ap_channel_done_sub24_loc_channel = ((ap_sync_reg_channel_write_sub24_loc_channel ^ 1'b1) & Block_entry61_proc_U0_ap_done);

assign ap_channel_done_zext_ln142_loc_channel = ((ap_sync_reg_channel_write_zext_ln142_loc_channel ^ 1'b1) & Block_entry61_proc_U0_ap_done);

assign ap_done = Loop_VITIS_LOOP_144_1_proc_U0_ap_done;

assign ap_idle = ((sub24_loc_channel_empty_n ^ 1'b1) & (m_cast_loc_channel_empty_n ^ 1'b1) & (m_cast8_loc_channel_empty_n ^ 1'b1) & (m_cast10_loc_channel_empty_n ^ 1'b1) & (call_b_cast_loc_channel_empty_n ^ 1'b1) & (zext_ln142_loc_channel_empty_n ^ 1'b1) & (call_a_cast_loc_channel_empty_n ^ 1'b1) & Loop_VITIS_LOOP_144_1_proc_U0_ap_idle & Block_entry61_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_entry61_proc_U0_ap_ready = (ap_sync_reg_Block_entry61_proc_U0_ap_ready | Block_entry61_proc_U0_ap_ready);

assign ap_sync_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready = (ap_sync_reg_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready | Loop_VITIS_LOOP_144_1_proc_U0_ap_ready);

assign ap_sync_channel_write_call_a_cast_loc_channel = ((call_a_cast_loc_channel_full_n & ap_channel_done_call_a_cast_loc_channel) | ap_sync_reg_channel_write_call_a_cast_loc_channel);

assign ap_sync_channel_write_call_b_cast_loc_channel = ((call_b_cast_loc_channel_full_n & ap_channel_done_call_b_cast_loc_channel) | ap_sync_reg_channel_write_call_b_cast_loc_channel);

assign ap_sync_channel_write_m_cast10_loc_channel = ((m_cast10_loc_channel_full_n & ap_channel_done_m_cast10_loc_channel) | ap_sync_reg_channel_write_m_cast10_loc_channel);

assign ap_sync_channel_write_m_cast8_loc_channel = ((m_cast8_loc_channel_full_n & ap_channel_done_m_cast8_loc_channel) | ap_sync_reg_channel_write_m_cast8_loc_channel);

assign ap_sync_channel_write_m_cast_loc_channel = ((m_cast_loc_channel_full_n & ap_channel_done_m_cast_loc_channel) | ap_sync_reg_channel_write_m_cast_loc_channel);

assign ap_sync_channel_write_sub24_loc_channel = ((sub24_loc_channel_full_n & ap_channel_done_sub24_loc_channel) | ap_sync_reg_channel_write_sub24_loc_channel);

assign ap_sync_channel_write_zext_ln142_loc_channel = ((zext_ln142_loc_channel_full_n & ap_channel_done_zext_ln142_loc_channel) | ap_sync_reg_channel_write_zext_ln142_loc_channel);

assign ap_sync_ready = (ap_sync_Loop_VITIS_LOOP_144_1_proc_U0_ap_ready & ap_sync_Block_entry61_proc_U0_ap_ready);

assign aw_RID = 1'd0;

assign aw_RLAST = 1'b0;

assign aw_RRESP = 2'd0;

assign aw_RUSER = 1'd0;

assign bi_RID = 1'd0;

assign bi_RLAST = 1'b0;

assign bi_RRESP = 2'd0;

assign bi_RUSER = 1'd0;

assign ca_BID = 1'd0;

assign ca_BRESP = 2'd0;

assign ca_BUSER = 1'd0;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "shell_top_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //shell_top

