domain_path: /home/ulisses/Projects/ursa/exp/output-stationary/vitis/platform-ursa-vanilla-ocm/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /opt/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
