-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mxm_execute_ursa_mxm_execute_ursa_Pipeline_LOAD_B is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_bi_AWVALID : OUT STD_LOGIC;
    m_axi_bi_AWREADY : IN STD_LOGIC;
    m_axi_bi_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bi_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bi_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bi_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bi_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bi_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bi_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bi_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bi_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bi_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_WVALID : OUT STD_LOGIC;
    m_axi_bi_WREADY : IN STD_LOGIC;
    m_axi_bi_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bi_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bi_WLAST : OUT STD_LOGIC;
    m_axi_bi_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_ARVALID : OUT STD_LOGIC;
    m_axi_bi_ARREADY : IN STD_LOGIC;
    m_axi_bi_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bi_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bi_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bi_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bi_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bi_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bi_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_bi_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bi_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_bi_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_RVALID : IN STD_LOGIC;
    m_axi_bi_RREADY : OUT STD_LOGIC;
    m_axi_bi_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_bi_RLAST : IN STD_LOGIC;
    m_axi_bi_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_bi_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bi_BVALID : IN STD_LOGIC;
    m_axi_bi_BREADY : OUT STD_LOGIC;
    m_axi_bi_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_bi_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_bi_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln155 : IN STD_LOGIC_VECTOR (15 downto 0);
    select_ln160 : IN STD_LOGIC_VECTOR (15 downto 0);
    b_buf_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    b_buf_1_ce0 : OUT STD_LOGIC;
    b_buf_1_we0 : OUT STD_LOGIC;
    b_buf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    b_buf_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    b_buf_ce0 : OUT STD_LOGIC;
    b_buf_we0 : OUT STD_LOGIC;
    b_buf_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    addr_b0 : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln243 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of mxm_execute_ursa_mxm_execute_ursa_Pipeline_LOAD_B is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln160_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal bi_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bi_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln243_cast_fu_168_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln243_cast_reg_358 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln4_reg_367 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_372_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln168_1_fu_244_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln168_1_reg_378_pp0_iter10_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal w_reg_389 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln168_1_fu_301_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln163_fu_263_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal off_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal off_1_fu_248_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln155_cast_fu_172_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_fu_102 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln160_fu_194_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_203_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal and_ln_fu_213_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln163_fu_221_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1_fu_280_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln168_fu_287_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln168_fu_291_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal by_fu_273_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal by_1_fu_306_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln168_1_fu_312_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln168_2_fu_320_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln168_1_fu_324_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mxm_execute_ursa_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mxm_execute_ursa_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    k_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_102 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln160_fu_189_p2 = ap_const_lv1_0))) then 
                    k_fu_102 <= add_ln160_fu_194_p2;
                end if;
            end if; 
        end if;
    end process;

    off_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    off_fu_98 <= zext_ln155_cast_fu_172_p1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln160_fu_189_p2 = ap_const_lv1_0))) then 
                    off_fu_98 <= off_1_fu_248_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                tmp_reg_372_pp0_iter10_reg <= tmp_reg_372_pp0_iter9_reg;
                tmp_reg_372_pp0_iter2_reg <= tmp_reg_372;
                tmp_reg_372_pp0_iter3_reg <= tmp_reg_372_pp0_iter2_reg;
                tmp_reg_372_pp0_iter4_reg <= tmp_reg_372_pp0_iter3_reg;
                tmp_reg_372_pp0_iter5_reg <= tmp_reg_372_pp0_iter4_reg;
                tmp_reg_372_pp0_iter6_reg <= tmp_reg_372_pp0_iter5_reg;
                tmp_reg_372_pp0_iter7_reg <= tmp_reg_372_pp0_iter6_reg;
                tmp_reg_372_pp0_iter8_reg <= tmp_reg_372_pp0_iter7_reg;
                tmp_reg_372_pp0_iter9_reg <= tmp_reg_372_pp0_iter8_reg;
                trunc_ln168_1_reg_378_pp0_iter10_reg <= trunc_ln168_1_reg_378_pp0_iter9_reg;
                trunc_ln168_1_reg_378_pp0_iter2_reg <= trunc_ln168_1_reg_378;
                trunc_ln168_1_reg_378_pp0_iter3_reg <= trunc_ln168_1_reg_378_pp0_iter2_reg;
                trunc_ln168_1_reg_378_pp0_iter4_reg <= trunc_ln168_1_reg_378_pp0_iter3_reg;
                trunc_ln168_1_reg_378_pp0_iter5_reg <= trunc_ln168_1_reg_378_pp0_iter4_reg;
                trunc_ln168_1_reg_378_pp0_iter6_reg <= trunc_ln168_1_reg_378_pp0_iter5_reg;
                trunc_ln168_1_reg_378_pp0_iter7_reg <= trunc_ln168_1_reg_378_pp0_iter6_reg;
                trunc_ln168_1_reg_378_pp0_iter8_reg <= trunc_ln168_1_reg_378_pp0_iter7_reg;
                trunc_ln168_1_reg_378_pp0_iter9_reg <= trunc_ln168_1_reg_378_pp0_iter8_reg;
                w_reg_389 <= m_axi_bi_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                tmp_reg_372 <= off_fu_98(1 downto 1);
                trunc_ln168_1_reg_378 <= trunc_ln168_1_fu_244_p1;
                trunc_ln4_reg_367 <= add_ln163_fu_221_p2(31 downto 2);
                    zext_ln243_cast_reg_358(15 downto 0) <= zext_ln243_cast_fu_168_p1(15 downto 0);
            end if;
        end if;
    end process;
    zext_ln243_cast_reg_358(31 downto 16) <= "0000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln160_fu_194_p2 <= std_logic_vector(unsigned(k_fu_102) + unsigned(ap_const_lv16_1));
    add_ln163_fu_221_p2 <= std_logic_vector(unsigned(and_ln_fu_213_p3) + unsigned(addr_b0));
    and_ln_fu_213_p3 <= (tmp_5_fu_203_p4 & ap_const_lv2_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter10, m_axi_bi_ARREADY, ap_block_state11_pp0_stage0_iter10)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10)) or ((m_axi_bi_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter10, m_axi_bi_ARREADY, ap_block_state11_pp0_stage0_iter10)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state11_pp0_stage0_iter10)) or ((m_axi_bi_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_state11_pp0_stage0_iter10_assign_proc : process(m_axi_bi_RVALID)
    begin
                ap_block_state11_pp0_stage0_iter10 <= (m_axi_bi_RVALID = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln160_fu_189_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln160_fu_189_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    b_buf_1_address0 <= zext_ln168_1_fu_301_p1(8 - 1 downto 0);

    b_buf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            b_buf_1_ce0 <= ap_const_logic_1;
        else 
            b_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    b_buf_1_d0 <= lshr_ln168_1_fu_324_p2(8 - 1 downto 0);

    b_buf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            b_buf_1_we0 <= ap_const_logic_1;
        else 
            b_buf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    b_buf_address0 <= zext_ln168_1_fu_301_p1(8 - 1 downto 0);

    b_buf_ce0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            b_buf_ce0 <= ap_const_logic_1;
        else 
            b_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    b_buf_d0 <= lshr_ln168_fu_291_p2(8 - 1 downto 0);

    b_buf_we0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            b_buf_we0 <= ap_const_logic_1;
        else 
            b_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    bi_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_bi_ARREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            bi_blk_n_AR <= m_axi_bi_ARREADY;
        else 
            bi_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    bi_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter10, m_axi_bi_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            bi_blk_n_R <= m_axi_bi_RVALID;
        else 
            bi_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    by_1_fu_306_p2 <= (by_fu_273_p3 or ap_const_lv2_1);
    by_fu_273_p3 <= (tmp_reg_372_pp0_iter10_reg & ap_const_lv1_0);
    icmp_ln160_fu_189_p2 <= "1" when (k_fu_102 = select_ln160) else "0";
    lshr_ln168_1_fu_324_p2 <= std_logic_vector(shift_right(unsigned(w_reg_389),to_integer(unsigned('0' & zext_ln168_2_fu_320_p1(31-1 downto 0)))));
    lshr_ln168_fu_291_p2 <= std_logic_vector(shift_right(unsigned(w_reg_389),to_integer(unsigned('0' & zext_ln168_fu_287_p1(31-1 downto 0)))));
    m_axi_bi_ARADDR <= sext_ln163_fu_263_p1;
    m_axi_bi_ARBURST <= ap_const_lv2_0;
    m_axi_bi_ARCACHE <= ap_const_lv4_0;
    m_axi_bi_ARID <= ap_const_lv1_0;
    m_axi_bi_ARLEN <= ap_const_lv32_1;
    m_axi_bi_ARLOCK <= ap_const_lv2_0;
    m_axi_bi_ARPROT <= ap_const_lv3_0;
    m_axi_bi_ARQOS <= ap_const_lv4_0;
    m_axi_bi_ARREGION <= ap_const_lv4_0;
    m_axi_bi_ARSIZE <= ap_const_lv3_0;
    m_axi_bi_ARUSER <= ap_const_lv1_0;

    m_axi_bi_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_bi_ARVALID <= ap_const_logic_1;
        else 
            m_axi_bi_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_bi_AWADDR <= ap_const_lv32_0;
    m_axi_bi_AWBURST <= ap_const_lv2_0;
    m_axi_bi_AWCACHE <= ap_const_lv4_0;
    m_axi_bi_AWID <= ap_const_lv1_0;
    m_axi_bi_AWLEN <= ap_const_lv32_0;
    m_axi_bi_AWLOCK <= ap_const_lv2_0;
    m_axi_bi_AWPROT <= ap_const_lv3_0;
    m_axi_bi_AWQOS <= ap_const_lv4_0;
    m_axi_bi_AWREGION <= ap_const_lv4_0;
    m_axi_bi_AWSIZE <= ap_const_lv3_0;
    m_axi_bi_AWUSER <= ap_const_lv1_0;
    m_axi_bi_AWVALID <= ap_const_logic_0;
    m_axi_bi_BREADY <= ap_const_logic_0;

    m_axi_bi_RREADY_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_bi_RREADY <= ap_const_logic_1;
        else 
            m_axi_bi_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_bi_WDATA <= ap_const_lv32_0;
    m_axi_bi_WID <= ap_const_lv1_0;
    m_axi_bi_WLAST <= ap_const_logic_0;
    m_axi_bi_WSTRB <= ap_const_lv4_0;
    m_axi_bi_WUSER <= ap_const_lv1_0;
    m_axi_bi_WVALID <= ap_const_logic_0;
    off_1_fu_248_p2 <= std_logic_vector(unsigned(zext_ln243_cast_reg_358) + unsigned(off_fu_98));
        sext_ln163_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln4_reg_367),32));

    shl_ln168_1_fu_312_p3 <= (by_1_fu_306_p2 & ap_const_lv3_0);
    shl_ln1_fu_280_p3 <= (tmp_reg_372_pp0_iter10_reg & ap_const_lv4_0);
    tmp_5_fu_203_p4 <= off_fu_98(31 downto 2);
    trunc_ln168_1_fu_244_p1 <= k_fu_102(8 - 1 downto 0);
    zext_ln155_cast_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln155),32));
    zext_ln168_1_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln168_1_reg_378_pp0_iter10_reg),32));
    zext_ln168_2_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln168_1_fu_312_p3),32));
    zext_ln168_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_280_p3),32));
    zext_ln243_cast_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln243),32));
end behav;
