# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_vanilla/ursa_vanilla.srcs/sources_1/bd/ursa_vanilla/ip/ursa_vanilla_blk_mem_gen_2_0/ursa_vanilla_blk_mem_gen_2_0.xci
# IP: The module: 'ursa_vanilla_blk_mem_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_vanilla/ursa_vanilla.gen/sources_1/bd/ursa_vanilla/ip/ursa_vanilla_blk_mem_gen_2_0/ursa_vanilla_blk_mem_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ursa_vanilla_blk_mem_gen_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_vanilla/ursa_vanilla.srcs/sources_1/bd/ursa_vanilla/ip/ursa_vanilla_blk_mem_gen_2_0/ursa_vanilla_blk_mem_gen_2_0.xci
# IP: The module: 'ursa_vanilla_blk_mem_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_vanilla/ursa_vanilla.gen/sources_1/bd/ursa_vanilla/ip/ursa_vanilla_blk_mem_gen_2_0/ursa_vanilla_blk_mem_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ursa_vanilla_blk_mem_gen_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
