# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_8x8/ursa_8x8.srcs/sources_1/bd/ursa_8x8/ip/ursa_8x8_s01_mmu_1/ursa_8x8_s01_mmu_1.xci
# IP: The module: 'ursa_8x8_s01_mmu_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_8x8/ursa_8x8.gen/sources_1/bd/ursa_8x8/ip/ursa_8x8_s01_mmu_1/ursa_8x8_s01_mmu_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ursa_8x8_s01_mmu_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_8x8/ursa_8x8.srcs/sources_1/bd/ursa_8x8/ip/ursa_8x8_s01_mmu_1/ursa_8x8_s01_mmu_1.xci
# IP: The module: 'ursa_8x8_s01_mmu_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fi/Documents/GitHub/ursa/exp/vivado/ursa_8x8/ursa_8x8.gen/sources_1/bd/ursa_8x8/ip/ursa_8x8_s01_mmu_1/ursa_8x8_s01_mmu_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ursa_8x8_s01_mmu_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
