# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_1/bd_8x8_bram_xbar_1.xci
# IP: The module: 'bd_8x8_bram_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.gen/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_1/bd_8x8_bram_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8x8_bram_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_1/bd_8x8_bram_xbar_1.xci
# IP: The module: 'bd_8x8_bram_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.gen/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_1/bd_8x8_bram_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8x8_bram_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
