// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mxm_execute_ursa_mxm_execute_ursa_Pipeline_VITIS_LOOP_382_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_ca_AWVALID,
        m_axi_ca_AWREADY,
        m_axi_ca_AWADDR,
        m_axi_ca_AWID,
        m_axi_ca_AWLEN,
        m_axi_ca_AWSIZE,
        m_axi_ca_AWBURST,
        m_axi_ca_AWLOCK,
        m_axi_ca_AWCACHE,
        m_axi_ca_AWPROT,
        m_axi_ca_AWQOS,
        m_axi_ca_AWREGION,
        m_axi_ca_AWUSER,
        m_axi_ca_WVALID,
        m_axi_ca_WREADY,
        m_axi_ca_WDATA,
        m_axi_ca_WSTRB,
        m_axi_ca_WLAST,
        m_axi_ca_WID,
        m_axi_ca_WUSER,
        m_axi_ca_ARVALID,
        m_axi_ca_ARREADY,
        m_axi_ca_ARADDR,
        m_axi_ca_ARID,
        m_axi_ca_ARLEN,
        m_axi_ca_ARSIZE,
        m_axi_ca_ARBURST,
        m_axi_ca_ARLOCK,
        m_axi_ca_ARCACHE,
        m_axi_ca_ARPROT,
        m_axi_ca_ARQOS,
        m_axi_ca_ARREGION,
        m_axi_ca_ARUSER,
        m_axi_ca_RVALID,
        m_axi_ca_RREADY,
        m_axi_ca_RDATA,
        m_axi_ca_RLAST,
        m_axi_ca_RID,
        m_axi_ca_RFIFONUM,
        m_axi_ca_RUSER,
        m_axi_ca_RRESP,
        m_axi_ca_BVALID,
        m_axi_ca_BREADY,
        m_axi_ca_BRESP,
        m_axi_ca_BID,
        m_axi_ca_BUSER,
        cmp124_7,
        cmp124_6,
        cmp124_5,
        cmp124_4,
        cmp124_3,
        cmp124_2,
        cmp124_1,
        c_tile_acc_address0,
        c_tile_acc_ce0,
        c_tile_acc_q0,
        c_tile_acc_address1,
        c_tile_acc_ce1,
        c_tile_acc_q1,
        empty,
        a0_p,
        zext_ln309,
        cmp124,
        base_col_B_cast,
        addr_c0,
        zext_ln391,
        zext_ln391_1,
        zext_ln391_2,
        zext_ln391_3,
        zext_ln391_4,
        zext_ln391_5,
        zext_ln382
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_ca_AWVALID;
input   m_axi_ca_AWREADY;
output  [63:0] m_axi_ca_AWADDR;
output  [0:0] m_axi_ca_AWID;
output  [31:0] m_axi_ca_AWLEN;
output  [2:0] m_axi_ca_AWSIZE;
output  [1:0] m_axi_ca_AWBURST;
output  [1:0] m_axi_ca_AWLOCK;
output  [3:0] m_axi_ca_AWCACHE;
output  [2:0] m_axi_ca_AWPROT;
output  [3:0] m_axi_ca_AWQOS;
output  [3:0] m_axi_ca_AWREGION;
output  [0:0] m_axi_ca_AWUSER;
output   m_axi_ca_WVALID;
input   m_axi_ca_WREADY;
output  [31:0] m_axi_ca_WDATA;
output  [3:0] m_axi_ca_WSTRB;
output   m_axi_ca_WLAST;
output  [0:0] m_axi_ca_WID;
output  [0:0] m_axi_ca_WUSER;
output   m_axi_ca_ARVALID;
input   m_axi_ca_ARREADY;
output  [63:0] m_axi_ca_ARADDR;
output  [0:0] m_axi_ca_ARID;
output  [31:0] m_axi_ca_ARLEN;
output  [2:0] m_axi_ca_ARSIZE;
output  [1:0] m_axi_ca_ARBURST;
output  [1:0] m_axi_ca_ARLOCK;
output  [3:0] m_axi_ca_ARCACHE;
output  [2:0] m_axi_ca_ARPROT;
output  [3:0] m_axi_ca_ARQOS;
output  [3:0] m_axi_ca_ARREGION;
output  [0:0] m_axi_ca_ARUSER;
input   m_axi_ca_RVALID;
output   m_axi_ca_RREADY;
input  [31:0] m_axi_ca_RDATA;
input   m_axi_ca_RLAST;
input  [0:0] m_axi_ca_RID;
input  [9:0] m_axi_ca_RFIFONUM;
input  [0:0] m_axi_ca_RUSER;
input  [1:0] m_axi_ca_RRESP;
input   m_axi_ca_BVALID;
output   m_axi_ca_BREADY;
input  [1:0] m_axi_ca_BRESP;
input  [0:0] m_axi_ca_BID;
input  [0:0] m_axi_ca_BUSER;
input  [0:0] cmp124_7;
input  [0:0] cmp124_6;
input  [0:0] cmp124_5;
input  [0:0] cmp124_4;
input  [0:0] cmp124_3;
input  [0:0] cmp124_2;
input  [0:0] cmp124_1;
output  [5:0] c_tile_acc_address0;
output   c_tile_acc_ce0;
input  [31:0] c_tile_acc_q0;
output  [5:0] c_tile_acc_address1;
output   c_tile_acc_ce1;
input  [31:0] c_tile_acc_q1;
input  [12:0] empty;
input  [15:0] a0_p;
input  [15:0] zext_ln309;
input  [0:0] cmp124;
input  [15:0] base_col_B_cast;
input  [63:0] addr_c0;
input  [15:0] zext_ln391;
input  [15:0] zext_ln391_1;
input  [15:0] zext_ln391_2;
input  [15:0] zext_ln391_3;
input  [15:0] zext_ln391_4;
input  [15:0] zext_ln391_5;
input  [15:0] zext_ln382;

reg ap_idle;
reg m_axi_ca_AWVALID;
reg[63:0] m_axi_ca_AWADDR;
reg m_axi_ca_WVALID;
reg[31:0] m_axi_ca_WDATA;
reg m_axi_ca_BREADY;
reg[5:0] c_tile_acc_address0;
reg c_tile_acc_ce0;
reg[5:0] c_tile_acc_address1;
reg c_tile_acc_ce1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
reg   [0:0] icmp_ln382_reg_1080;
reg   [0:0] and_ln390_4_reg_1132;
reg    ap_predicate_op198_write_state8;
reg   [0:0] and_ln390_5_reg_1136;
reg    ap_predicate_op199_writereq_state8;
reg    ap_block_state8_io;
reg   [0:0] and_ln390_7_reg_1144;
reg   [0:0] and_ln390_7_reg_1144_pp0_iter1_reg;
reg    ap_block_state16_pp0_stage7_iter1;
reg    ap_block_pp0_stage7_subdone;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ca_blk_n_AW;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] and_ln390_reg_1116;
reg    ca_blk_n_W;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg    ca_blk_n_B;
wire    ap_block_pp0_stage0;
reg   [0:0] and_ln390_1_reg_1120;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] and_ln390_1_reg_1120_pp0_iter1_reg;
reg   [0:0] and_ln390_2_reg_1124;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] and_ln390_2_reg_1124_pp0_iter1_reg;
reg   [0:0] and_ln390_3_reg_1128;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] and_ln390_3_reg_1128_pp0_iter1_reg;
wire    ap_block_pp0_stage7;
reg   [0:0] and_ln390_4_reg_1132_pp0_iter1_reg;
reg   [0:0] and_ln390_5_reg_1136_pp0_iter1_reg;
reg   [0:0] and_ln390_6_reg_1140;
reg   [0:0] and_ln390_6_reg_1140_pp0_iter1_reg;
reg   [31:0] reg_459;
reg    ap_block_state10_pp0_stage1_iter1;
reg    ap_block_state10_io;
reg    ap_block_pp0_stage1_11001;
reg    ap_predicate_op132_write_state4;
reg    ap_predicate_op133_writereq_state4;
reg    ap_block_state4_io;
reg    ap_block_state12_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
reg   [31:0] reg_465;
reg    ap_predicate_op146_write_state5;
reg    ap_predicate_op147_writereq_state5;
reg    ap_block_state5_io;
reg    ap_block_state13_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_state9_io;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln382_cast_fu_472_p1;
reg   [31:0] zext_ln382_cast_reg_1040;
wire   [31:0] zext_ln391_5_cast_fu_476_p1;
reg   [31:0] zext_ln391_5_cast_reg_1045;
wire   [31:0] zext_ln391_4_cast_fu_480_p1;
reg   [31:0] zext_ln391_4_cast_reg_1050;
wire   [31:0] zext_ln391_3_cast_fu_484_p1;
reg   [31:0] zext_ln391_3_cast_reg_1055;
wire   [31:0] zext_ln391_2_cast_fu_488_p1;
reg   [31:0] zext_ln391_2_cast_reg_1060;
wire   [31:0] zext_ln391_1_cast_fu_492_p1;
reg   [31:0] zext_ln391_1_cast_reg_1065;
wire   [31:0] zext_ln391_cast_fu_496_p1;
reg   [31:0] zext_ln391_cast_reg_1070;
wire   [31:0] base_col_B_cast_cast_fu_500_p1;
reg   [31:0] base_col_B_cast_cast_reg_1075;
wire   [0:0] icmp_ln382_fu_520_p2;
wire   [5:0] tmp_2_fu_532_p3;
reg   [5:0] tmp_2_reg_1084;
wire   [31:0] mul131_fu_574_p2;
reg   [31:0] mul131_reg_1104;
wire   [0:0] and_ln390_fu_580_p2;
wire   [0:0] and_ln390_1_fu_586_p2;
wire   [0:0] and_ln390_2_fu_592_p2;
wire   [0:0] and_ln390_3_fu_598_p2;
wire   [0:0] and_ln390_4_fu_604_p2;
wire   [0:0] and_ln390_5_fu_610_p2;
wire   [0:0] and_ln390_6_fu_616_p2;
wire   [0:0] and_ln390_7_fu_622_p2;
reg   [63:0] ca_addr_reg_1158;
reg    ap_predicate_op111_writereq_state3;
reg    ap_block_state3_io;
reg    ap_block_state11_pp0_stage2_iter1;
reg    ap_block_state11_io;
reg    ap_block_pp0_stage2_11001;
reg   [63:0] ca_addr_1_reg_1174;
reg   [31:0] c_tile_acc_load_2_reg_1180;
reg   [31:0] c_tile_acc_load_3_reg_1185;
reg   [63:0] ca_addr_2_reg_1200;
reg   [31:0] c_tile_acc_load_5_reg_1206;
reg   [63:0] ca_addr_3_reg_1211;
reg   [31:0] c_tile_acc_load_7_reg_1217;
reg   [63:0] ca_addr_4_reg_1222;
reg    ap_predicate_op159_write_state6;
reg    ap_predicate_op160_writereq_state6;
reg    ap_block_state6_io;
reg    ap_block_state14_pp0_stage5_iter1;
reg    ap_block_pp0_stage5_11001;
reg   [63:0] ca_addr_5_reg_1228;
reg   [63:0] ca_addr_6_reg_1234;
reg   [63:0] ca_addr_7_reg_1240;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln391_6_fu_540_p1;
wire   [63:0] zext_ln391_15_fu_551_p1;
wire   [63:0] zext_ln391_16_fu_638_p1;
wire   [63:0] zext_ln391_17_fu_648_p1;
wire   [63:0] zext_ln391_18_fu_699_p1;
wire   [63:0] zext_ln391_19_fu_709_p1;
wire   [63:0] zext_ln391_20_fu_760_p1;
wire   [63:0] zext_ln391_21_fu_770_p1;
wire  signed [63:0] sext_ln391_fu_684_p1;
wire  signed [63:0] sext_ln391_1_fu_745_p1;
wire  signed [63:0] sext_ln391_2_fu_806_p1;
wire  signed [63:0] sext_ln391_3_fu_847_p1;
wire  signed [63:0] sext_ln391_4_fu_888_p1;
wire  signed [63:0] sext_ln391_5_fu_929_p1;
wire  signed [63:0] sext_ln391_6_fu_970_p1;
wire  signed [63:0] sext_ln391_7_fu_1011_p1;
reg    ap_block_pp0_stage3_01001;
reg    ap_block_pp0_stage4_01001;
reg    ap_block_pp0_stage5_01001;
reg    ap_predicate_op192_write_state7;
reg    ap_predicate_op193_writereq_state7;
reg    ap_block_state7_io;
reg    ap_block_state15_pp0_stage6_iter1;
reg    ap_block_pp0_stage6_11001;
reg    ap_block_pp0_stage6_01001;
reg    ap_block_pp0_stage7_11001;
reg    ap_block_pp0_stage7_01001;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp0_stage2_01001;
reg   [3:0] r_fu_134;
wire   [3:0] add_ln382_fu_526_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_r_1;
wire   [2:0] empty_30_fu_516_p1;
wire   [5:0] or_ln391_fu_545_p2;
wire   [15:0] global_row_fu_556_p3;
wire   [15:0] mul131_fu_574_p0;
wire   [15:0] mul131_fu_574_p1;
wire   [0:0] cmp121_fu_564_p2;
wire   [5:0] or_ln391_1_fu_633_p2;
wire   [5:0] or_ln391_2_fu_643_p2;
wire   [31:0] add_ln391_fu_653_p2;
wire   [33:0] shl_ln1_fu_657_p3;
wire   [63:0] zext_ln391_7_fu_665_p1;
wire   [63:0] add_ln391_1_fu_669_p2;
wire   [61:0] trunc_ln3_fu_674_p4;
wire   [5:0] or_ln391_3_fu_694_p2;
wire   [5:0] or_ln391_4_fu_704_p2;
wire   [31:0] add_ln391_2_fu_714_p2;
wire   [33:0] shl_ln391_1_fu_718_p3;
wire   [63:0] zext_ln391_8_fu_726_p1;
wire   [63:0] add_ln391_3_fu_730_p2;
wire   [61:0] trunc_ln391_1_fu_735_p4;
wire   [5:0] or_ln391_5_fu_755_p2;
wire   [5:0] or_ln391_6_fu_765_p2;
wire   [31:0] add_ln391_4_fu_775_p2;
wire   [33:0] shl_ln391_2_fu_779_p3;
wire   [63:0] zext_ln391_9_fu_787_p1;
wire   [63:0] add_ln391_5_fu_791_p2;
wire   [61:0] trunc_ln391_2_fu_796_p4;
wire   [31:0] add_ln391_6_fu_816_p2;
wire   [33:0] shl_ln391_3_fu_820_p3;
wire   [63:0] zext_ln391_10_fu_828_p1;
wire   [63:0] add_ln391_7_fu_832_p2;
wire   [61:0] trunc_ln391_3_fu_837_p4;
wire   [31:0] add_ln391_8_fu_857_p2;
wire   [33:0] shl_ln391_4_fu_861_p3;
wire   [63:0] zext_ln391_11_fu_869_p1;
wire   [63:0] add_ln391_9_fu_873_p2;
wire   [61:0] trunc_ln391_4_fu_878_p4;
wire   [31:0] add_ln391_10_fu_898_p2;
wire   [33:0] shl_ln391_5_fu_902_p3;
wire   [63:0] zext_ln391_12_fu_910_p1;
wire   [63:0] add_ln391_11_fu_914_p2;
wire   [61:0] trunc_ln391_5_fu_919_p4;
wire   [31:0] add_ln391_12_fu_939_p2;
wire   [33:0] shl_ln391_6_fu_943_p3;
wire   [63:0] zext_ln391_13_fu_951_p1;
wire   [63:0] add_ln391_13_fu_955_p2;
wire   [61:0] trunc_ln391_6_fu_960_p4;
wire   [31:0] add_ln391_14_fu_980_p2;
wire   [33:0] shl_ln391_7_fu_984_p3;
wire   [63:0] zext_ln391_14_fu_992_p1;
wire   [63:0] add_ln391_15_fu_996_p2;
wire   [61:0] trunc_ln391_7_fu_1001_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [31:0] mul131_fu_574_p00;
wire   [31:0] mul131_fu_574_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 r_fu_134 = 4'd0;
#0 ap_done_reg = 1'b0;
end

mxm_execute_ursa_mul_16ns_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16ns_16ns_32_1_1_U566(
    .din0(mul131_fu_574_p0),
    .din1(mul131_fu_574_p1),
    .dout(mul131_fu_574_p2)
);

mxm_execute_ursa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln382_fu_520_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_134 <= add_ln382_fu_526_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_134 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
            reg_465 <= c_tile_acc_q1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
            reg_465 <= c_tile_acc_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln390_1_reg_1120 <= and_ln390_1_fu_586_p2;
        and_ln390_1_reg_1120_pp0_iter1_reg <= and_ln390_1_reg_1120;
        and_ln390_2_reg_1124 <= and_ln390_2_fu_592_p2;
        and_ln390_2_reg_1124_pp0_iter1_reg <= and_ln390_2_reg_1124;
        and_ln390_3_reg_1128 <= and_ln390_3_fu_598_p2;
        and_ln390_3_reg_1128_pp0_iter1_reg <= and_ln390_3_reg_1128;
        and_ln390_4_reg_1132 <= and_ln390_4_fu_604_p2;
        and_ln390_4_reg_1132_pp0_iter1_reg <= and_ln390_4_reg_1132;
        and_ln390_5_reg_1136 <= and_ln390_5_fu_610_p2;
        and_ln390_5_reg_1136_pp0_iter1_reg <= and_ln390_5_reg_1136;
        and_ln390_6_reg_1140 <= and_ln390_6_fu_616_p2;
        and_ln390_6_reg_1140_pp0_iter1_reg <= and_ln390_6_reg_1140;
        and_ln390_7_reg_1144 <= and_ln390_7_fu_622_p2;
        and_ln390_7_reg_1144_pp0_iter1_reg <= and_ln390_7_reg_1144;
        and_ln390_reg_1116 <= and_ln390_fu_580_p2;
        base_col_B_cast_cast_reg_1075[15 : 0] <= base_col_B_cast_cast_fu_500_p1[15 : 0];
        icmp_ln382_reg_1080 <= icmp_ln382_fu_520_p2;
        mul131_reg_1104 <= mul131_fu_574_p2;
        tmp_2_reg_1084[5 : 3] <= tmp_2_fu_532_p3[5 : 3];
        zext_ln382_cast_reg_1040[15 : 0] <= zext_ln382_cast_fu_472_p1[15 : 0];
        zext_ln391_1_cast_reg_1065[15 : 0] <= zext_ln391_1_cast_fu_492_p1[15 : 0];
        zext_ln391_2_cast_reg_1060[15 : 0] <= zext_ln391_2_cast_fu_488_p1[15 : 0];
        zext_ln391_3_cast_reg_1055[15 : 0] <= zext_ln391_3_cast_fu_484_p1[15 : 0];
        zext_ln391_4_cast_reg_1050[15 : 0] <= zext_ln391_4_cast_fu_480_p1[15 : 0];
        zext_ln391_5_cast_reg_1045[15 : 0] <= zext_ln391_5_cast_fu_476_p1[15 : 0];
        zext_ln391_cast_reg_1070[15 : 0] <= zext_ln391_cast_fu_496_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        c_tile_acc_load_2_reg_1180 <= c_tile_acc_q1;
        c_tile_acc_load_3_reg_1185 <= c_tile_acc_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        c_tile_acc_load_5_reg_1206 <= c_tile_acc_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        c_tile_acc_load_7_reg_1217 <= c_tile_acc_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ca_addr_1_reg_1174 <= sext_ln391_1_fu_745_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ca_addr_2_reg_1200 <= sext_ln391_2_fu_806_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ca_addr_3_reg_1211 <= sext_ln391_3_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        ca_addr_4_reg_1222 <= sext_ln391_4_fu_888_p1;
        ca_addr_5_reg_1228 <= sext_ln391_5_fu_929_p1;
        ca_addr_6_reg_1234 <= sext_ln391_6_fu_970_p1;
        ca_addr_7_reg_1240 <= sext_ln391_7_fu_1011_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ca_addr_reg_1158 <= sext_ln391_fu_684_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        reg_459 <= c_tile_acc_q1;
    end
end

always @ (*) begin
    if (((icmp_ln382_reg_1080 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_r_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_r_1 = r_fu_134;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
            c_tile_acc_address0 = zext_ln391_21_fu_770_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2))) begin
            c_tile_acc_address0 = zext_ln391_19_fu_709_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            c_tile_acc_address0 = zext_ln391_17_fu_648_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            c_tile_acc_address0 = zext_ln391_15_fu_551_p1;
        end else begin
            c_tile_acc_address0 = 'bx;
        end
    end else begin
        c_tile_acc_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
            c_tile_acc_address1 = zext_ln391_20_fu_760_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2))) begin
            c_tile_acc_address1 = zext_ln391_18_fu_699_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            c_tile_acc_address1 = zext_ln391_16_fu_638_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            c_tile_acc_address1 = zext_ln391_6_fu_540_p1;
        end else begin
            c_tile_acc_address1 = 'bx;
        end
    end else begin
        c_tile_acc_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)))) begin
        c_tile_acc_ce0 = 1'b1;
    end else begin
        c_tile_acc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)))) begin
        c_tile_acc_ce1 = 1'b1;
    end else begin
        c_tile_acc_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln390_4_reg_1132) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((1'd1 == and_ln390_6_reg_1140) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((1'd1 == and_ln390_3_reg_1128) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((1'd1 == and_ln390_2_reg_1124) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((1'd1 == and_ln390_1_reg_1120) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((1'd1 == and_ln390_reg_1116) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7) & (ap_predicate_op199_writereq_state8 == 1'b1)))) begin
        ca_blk_n_AW = m_axi_ca_AWREADY;
    end else begin
        ca_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln390_6_reg_1140_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((1'd1 == and_ln390_5_reg_1136_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((1'd1 == and_ln390_4_reg_1132_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((1'd1 == and_ln390_3_reg_1128_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((1'd1 == and_ln390_2_reg_1124_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((1'd1 == and_ln390_1_reg_1120_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((1'd1 == and_ln390_reg_1116) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) 
    | ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)))) begin
        ca_blk_n_B = m_axi_ca_BVALID;
    end else begin
        ca_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln390_6_reg_1140_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((1'd1 == and_ln390_3_reg_1128) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((1'd1 == and_ln390_2_reg_1124) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((1'd1 == and_ln390_1_reg_1120) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((1'd1 == and_ln390_reg_1116) & (icmp_ln382_reg_1080 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) 
    & (1'b0 == ap_block_pp0_stage7) & (ap_predicate_op198_write_state8 == 1'b1)) | ((1'd1 == and_ln390_5_reg_1136) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        ca_blk_n_W = m_axi_ca_WREADY;
    end else begin
        ca_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_ca_AWADDR = ca_addr_7_reg_1240;
    end else if (((1'd1 == and_ln390_6_reg_1140) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_ca_AWADDR = ca_addr_6_reg_1234;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op199_writereq_state8 == 1'b1))) begin
        m_axi_ca_AWADDR = ca_addr_5_reg_1228;
    end else if (((ap_predicate_op193_writereq_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        m_axi_ca_AWADDR = ca_addr_4_reg_1222;
    end else if (((ap_predicate_op160_writereq_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        m_axi_ca_AWADDR = ca_addr_3_reg_1211;
    end else if (((ap_predicate_op147_writereq_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        m_axi_ca_AWADDR = ca_addr_2_reg_1200;
    end else if (((ap_predicate_op133_writereq_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_ca_AWADDR = ca_addr_1_reg_1174;
    end else if (((ap_predicate_op111_writereq_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        m_axi_ca_AWADDR = ca_addr_reg_1158;
    end else begin
        m_axi_ca_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op193_writereq_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_predicate_op160_writereq_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_predicate_op111_writereq_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_predicate_op147_writereq_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_predicate_op133_writereq_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'd1 == and_ln390_6_reg_1140) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) 
    & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op199_writereq_state8 == 1'b1)))) begin
        m_axi_ca_AWVALID = 1'b1;
    end else begin
        m_axi_ca_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln390_6_reg_1140_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'd1 == and_ln390_5_reg_1136_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'd1 == and_ln390_4_reg_1132_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'd1 == and_ln390_3_reg_1128_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'd1 == and_ln390_2_reg_1124_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'd1 == and_ln390_1_reg_1120_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'd1 == and_ln390_reg_1116) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) 
    & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)))) begin
        m_axi_ca_BREADY = 1'b1;
    end else begin
        m_axi_ca_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        m_axi_ca_WDATA = c_tile_acc_load_7_reg_1217;
    end else if (((1'd1 == and_ln390_5_reg_1136) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        m_axi_ca_WDATA = c_tile_acc_load_5_reg_1206;
    end else if (((ap_predicate_op192_write_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        m_axi_ca_WDATA = c_tile_acc_load_3_reg_1185;
    end else if (((ap_predicate_op159_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        m_axi_ca_WDATA = c_tile_acc_load_2_reg_1180;
    end else if ((((ap_predicate_op146_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001)) | ((1'd1 == and_ln390_6_reg_1140_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001)))) begin
        m_axi_ca_WDATA = reg_465;
    end else if ((((ap_predicate_op132_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op198_write_state8 == 1'b1)))) begin
        m_axi_ca_WDATA = reg_459;
    end else begin
        m_axi_ca_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op192_write_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_predicate_op159_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_predicate_op146_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_predicate_op132_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'd1 == and_ln390_6_reg_1140_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001) 
    & (ap_predicate_op198_write_state8 == 1'b1)) | ((1'd1 == and_ln390_5_reg_1136) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        m_axi_ca_WVALID = 1'b1;
    end else begin
        m_axi_ca_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln382_fu_526_p2 = (ap_sig_allocacmp_r_1 + 4'd1);

assign add_ln391_10_fu_898_p2 = (mul131_reg_1104 + zext_ln391_4_cast_reg_1050);

assign add_ln391_11_fu_914_p2 = (zext_ln391_12_fu_910_p1 + addr_c0);

assign add_ln391_12_fu_939_p2 = (mul131_reg_1104 + zext_ln391_5_cast_reg_1045);

assign add_ln391_13_fu_955_p2 = (zext_ln391_13_fu_951_p1 + addr_c0);

assign add_ln391_14_fu_980_p2 = (mul131_reg_1104 + zext_ln382_cast_reg_1040);

assign add_ln391_15_fu_996_p2 = (zext_ln391_14_fu_992_p1 + addr_c0);

assign add_ln391_1_fu_669_p2 = (zext_ln391_7_fu_665_p1 + addr_c0);

assign add_ln391_2_fu_714_p2 = (mul131_reg_1104 + zext_ln391_cast_reg_1070);

assign add_ln391_3_fu_730_p2 = (zext_ln391_8_fu_726_p1 + addr_c0);

assign add_ln391_4_fu_775_p2 = (mul131_reg_1104 + zext_ln391_1_cast_reg_1065);

assign add_ln391_5_fu_791_p2 = (zext_ln391_9_fu_787_p1 + addr_c0);

assign add_ln391_6_fu_816_p2 = (mul131_reg_1104 + zext_ln391_2_cast_reg_1060);

assign add_ln391_7_fu_832_p2 = (zext_ln391_10_fu_828_p1 + addr_c0);

assign add_ln391_8_fu_857_p2 = (mul131_reg_1104 + zext_ln391_3_cast_reg_1055);

assign add_ln391_9_fu_873_p2 = (zext_ln391_11_fu_869_p1 + addr_c0);

assign add_ln391_fu_653_p2 = (mul131_reg_1104 + base_col_B_cast_cast_reg_1075);

assign and_ln390_1_fu_586_p2 = (cmp124_1 & cmp121_fu_564_p2);

assign and_ln390_2_fu_592_p2 = (cmp124_2 & cmp121_fu_564_p2);

assign and_ln390_3_fu_598_p2 = (cmp124_3 & cmp121_fu_564_p2);

assign and_ln390_4_fu_604_p2 = (cmp124_4 & cmp121_fu_564_p2);

assign and_ln390_5_fu_610_p2 = (cmp124_5 & cmp121_fu_564_p2);

assign and_ln390_6_fu_616_p2 = (cmp124_6 & cmp121_fu_564_p2);

assign and_ln390_7_fu_622_p2 = (cmp124_7 & cmp121_fu_564_p2);

assign and_ln390_fu_580_p2 = (cmp124 & cmp121_fu_564_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state9_io) | (1'b1 == ap_block_state9_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state10_io) | (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state10_io) | (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage2_iter1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state11_io) | (1'b1 == ap_block_state11_pp0_stage2_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state11_io) | (1'b1 == ap_block_state11_pp0_stage2_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage4_iter1));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage4_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage4_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage5_iter1));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage5_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage5_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage6_iter1));
end

always @ (*) begin
    ap_block_pp0_stage6_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage6_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage6_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage7_iter1));
end

always @ (*) begin
    ap_block_pp0_stage7_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage7_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage7_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

always @ (*) begin
    ap_block_state10_io = (((1'd1 == and_ln390_6_reg_1140_pp0_iter1_reg) & (m_axi_ca_WREADY == 1'b0)) | ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (m_axi_ca_AWREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter1 = ((1'd1 == and_ln390_1_reg_1120_pp0_iter1_reg) & (m_axi_ca_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state11_io = ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (m_axi_ca_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state11_pp0_stage2_iter1 = ((1'd1 == and_ln390_2_reg_1124_pp0_iter1_reg) & (m_axi_ca_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state12_pp0_stage3_iter1 = ((1'd1 == and_ln390_3_reg_1128_pp0_iter1_reg) & (m_axi_ca_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp0_stage4_iter1 = ((1'd1 == and_ln390_4_reg_1132_pp0_iter1_reg) & (m_axi_ca_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state14_pp0_stage5_iter1 = ((1'd1 == and_ln390_5_reg_1136_pp0_iter1_reg) & (m_axi_ca_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state15_pp0_stage6_iter1 = ((1'd1 == and_ln390_6_reg_1140_pp0_iter1_reg) & (m_axi_ca_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state16_pp0_stage7_iter1 = ((1'd1 == and_ln390_7_reg_1144_pp0_iter1_reg) & (m_axi_ca_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op111_writereq_state3 == 1'b1) & (m_axi_ca_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = (((m_axi_ca_WREADY == 1'b0) & (ap_predicate_op132_write_state4 == 1'b1)) | ((m_axi_ca_AWREADY == 1'b0) & (ap_predicate_op133_writereq_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_io = (((m_axi_ca_WREADY == 1'b0) & (ap_predicate_op146_write_state5 == 1'b1)) | ((m_axi_ca_AWREADY == 1'b0) & (ap_predicate_op147_writereq_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_io = (((m_axi_ca_WREADY == 1'b0) & (ap_predicate_op159_write_state6 == 1'b1)) | ((ap_predicate_op160_writereq_state6 == 1'b1) & (m_axi_ca_AWREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state7_io = (((ap_predicate_op193_writereq_state7 == 1'b1) & (m_axi_ca_AWREADY == 1'b0)) | ((ap_predicate_op192_write_state7 == 1'b1) & (m_axi_ca_WREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state8_io = (((m_axi_ca_WREADY == 1'b0) & (ap_predicate_op198_write_state8 == 1'b1)) | ((m_axi_ca_AWREADY == 1'b0) & (ap_predicate_op199_writereq_state8 == 1'b1)));
end

always @ (*) begin
    ap_block_state9_io = (((1'd1 == and_ln390_6_reg_1140) & (m_axi_ca_AWREADY == 1'b0)) | ((1'd1 == and_ln390_5_reg_1136) & (m_axi_ca_WREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = ((1'd1 == and_ln390_reg_1116) & (m_axi_ca_BVALID == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

always @ (*) begin
    ap_predicate_op111_writereq_state3 = ((1'd1 == and_ln390_reg_1116) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op132_write_state4 = ((1'd1 == and_ln390_reg_1116) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op133_writereq_state4 = ((1'd1 == and_ln390_1_reg_1120) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op146_write_state5 = ((1'd1 == and_ln390_1_reg_1120) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op147_writereq_state5 = ((1'd1 == and_ln390_2_reg_1124) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op159_write_state6 = ((1'd1 == and_ln390_2_reg_1124) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op160_writereq_state6 = ((1'd1 == and_ln390_3_reg_1128) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op192_write_state7 = ((1'd1 == and_ln390_3_reg_1128) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op193_writereq_state7 = ((1'd1 == and_ln390_4_reg_1132) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op198_write_state8 = ((1'd1 == and_ln390_4_reg_1132) & (icmp_ln382_reg_1080 == 1'd0));
end

always @ (*) begin
    ap_predicate_op199_writereq_state8 = ((1'd1 == and_ln390_5_reg_1136) & (icmp_ln382_reg_1080 == 1'd0));
end

assign base_col_B_cast_cast_fu_500_p1 = base_col_B_cast;

assign cmp121_fu_564_p2 = ((global_row_fu_556_p3 < a0_p) ? 1'b1 : 1'b0);

assign empty_30_fu_516_p1 = ap_sig_allocacmp_r_1[2:0];

assign global_row_fu_556_p3 = {{empty}, {empty_30_fu_516_p1}};

assign icmp_ln382_fu_520_p2 = ((ap_sig_allocacmp_r_1 == 4'd8) ? 1'b1 : 1'b0);

assign m_axi_ca_ARADDR = 64'd0;

assign m_axi_ca_ARBURST = 2'd0;

assign m_axi_ca_ARCACHE = 4'd0;

assign m_axi_ca_ARID = 1'd0;

assign m_axi_ca_ARLEN = 32'd0;

assign m_axi_ca_ARLOCK = 2'd0;

assign m_axi_ca_ARPROT = 3'd0;

assign m_axi_ca_ARQOS = 4'd0;

assign m_axi_ca_ARREGION = 4'd0;

assign m_axi_ca_ARSIZE = 3'd0;

assign m_axi_ca_ARUSER = 1'd0;

assign m_axi_ca_ARVALID = 1'b0;

assign m_axi_ca_AWBURST = 2'd0;

assign m_axi_ca_AWCACHE = 4'd0;

assign m_axi_ca_AWID = 1'd0;

assign m_axi_ca_AWLEN = 32'd1;

assign m_axi_ca_AWLOCK = 2'd0;

assign m_axi_ca_AWPROT = 3'd0;

assign m_axi_ca_AWQOS = 4'd0;

assign m_axi_ca_AWREGION = 4'd0;

assign m_axi_ca_AWSIZE = 3'd0;

assign m_axi_ca_AWUSER = 1'd0;

assign m_axi_ca_RREADY = 1'b0;

assign m_axi_ca_WID = 1'd0;

assign m_axi_ca_WLAST = 1'b0;

assign m_axi_ca_WSTRB = 4'd15;

assign m_axi_ca_WUSER = 1'd0;

assign mul131_fu_574_p0 = mul131_fu_574_p00;

assign mul131_fu_574_p00 = global_row_fu_556_p3;

assign mul131_fu_574_p1 = mul131_fu_574_p10;

assign mul131_fu_574_p10 = zext_ln309;

assign or_ln391_1_fu_633_p2 = (tmp_2_reg_1084 | 6'd2);

assign or_ln391_2_fu_643_p2 = (tmp_2_reg_1084 | 6'd3);

assign or_ln391_3_fu_694_p2 = (tmp_2_reg_1084 | 6'd4);

assign or_ln391_4_fu_704_p2 = (tmp_2_reg_1084 | 6'd5);

assign or_ln391_5_fu_755_p2 = (tmp_2_reg_1084 | 6'd6);

assign or_ln391_6_fu_765_p2 = (tmp_2_reg_1084 | 6'd7);

assign or_ln391_fu_545_p2 = (tmp_2_fu_532_p3 | 6'd1);

assign sext_ln391_1_fu_745_p1 = $signed(trunc_ln391_1_fu_735_p4);

assign sext_ln391_2_fu_806_p1 = $signed(trunc_ln391_2_fu_796_p4);

assign sext_ln391_3_fu_847_p1 = $signed(trunc_ln391_3_fu_837_p4);

assign sext_ln391_4_fu_888_p1 = $signed(trunc_ln391_4_fu_878_p4);

assign sext_ln391_5_fu_929_p1 = $signed(trunc_ln391_5_fu_919_p4);

assign sext_ln391_6_fu_970_p1 = $signed(trunc_ln391_6_fu_960_p4);

assign sext_ln391_7_fu_1011_p1 = $signed(trunc_ln391_7_fu_1001_p4);

assign sext_ln391_fu_684_p1 = $signed(trunc_ln3_fu_674_p4);

assign shl_ln1_fu_657_p3 = {{add_ln391_fu_653_p2}, {2'd0}};

assign shl_ln391_1_fu_718_p3 = {{add_ln391_2_fu_714_p2}, {2'd0}};

assign shl_ln391_2_fu_779_p3 = {{add_ln391_4_fu_775_p2}, {2'd0}};

assign shl_ln391_3_fu_820_p3 = {{add_ln391_6_fu_816_p2}, {2'd0}};

assign shl_ln391_4_fu_861_p3 = {{add_ln391_8_fu_857_p2}, {2'd0}};

assign shl_ln391_5_fu_902_p3 = {{add_ln391_10_fu_898_p2}, {2'd0}};

assign shl_ln391_6_fu_943_p3 = {{add_ln391_12_fu_939_p2}, {2'd0}};

assign shl_ln391_7_fu_984_p3 = {{add_ln391_14_fu_980_p2}, {2'd0}};

assign tmp_2_fu_532_p3 = {{empty_30_fu_516_p1}, {3'd0}};

assign trunc_ln391_1_fu_735_p4 = {{add_ln391_3_fu_730_p2[63:2]}};

assign trunc_ln391_2_fu_796_p4 = {{add_ln391_5_fu_791_p2[63:2]}};

assign trunc_ln391_3_fu_837_p4 = {{add_ln391_7_fu_832_p2[63:2]}};

assign trunc_ln391_4_fu_878_p4 = {{add_ln391_9_fu_873_p2[63:2]}};

assign trunc_ln391_5_fu_919_p4 = {{add_ln391_11_fu_914_p2[63:2]}};

assign trunc_ln391_6_fu_960_p4 = {{add_ln391_13_fu_955_p2[63:2]}};

assign trunc_ln391_7_fu_1001_p4 = {{add_ln391_15_fu_996_p2[63:2]}};

assign trunc_ln3_fu_674_p4 = {{add_ln391_1_fu_669_p2[63:2]}};

assign zext_ln382_cast_fu_472_p1 = zext_ln382;

assign zext_ln391_10_fu_828_p1 = shl_ln391_3_fu_820_p3;

assign zext_ln391_11_fu_869_p1 = shl_ln391_4_fu_861_p3;

assign zext_ln391_12_fu_910_p1 = shl_ln391_5_fu_902_p3;

assign zext_ln391_13_fu_951_p1 = shl_ln391_6_fu_943_p3;

assign zext_ln391_14_fu_992_p1 = shl_ln391_7_fu_984_p3;

assign zext_ln391_15_fu_551_p1 = or_ln391_fu_545_p2;

assign zext_ln391_16_fu_638_p1 = or_ln391_1_fu_633_p2;

assign zext_ln391_17_fu_648_p1 = or_ln391_2_fu_643_p2;

assign zext_ln391_18_fu_699_p1 = or_ln391_3_fu_694_p2;

assign zext_ln391_19_fu_709_p1 = or_ln391_4_fu_704_p2;

assign zext_ln391_1_cast_fu_492_p1 = zext_ln391_1;

assign zext_ln391_20_fu_760_p1 = or_ln391_5_fu_755_p2;

assign zext_ln391_21_fu_770_p1 = or_ln391_6_fu_765_p2;

assign zext_ln391_2_cast_fu_488_p1 = zext_ln391_2;

assign zext_ln391_3_cast_fu_484_p1 = zext_ln391_3;

assign zext_ln391_4_cast_fu_480_p1 = zext_ln391_4;

assign zext_ln391_5_cast_fu_476_p1 = zext_ln391_5;

assign zext_ln391_6_fu_540_p1 = tmp_2_fu_532_p3;

assign zext_ln391_7_fu_665_p1 = shl_ln1_fu_657_p3;

assign zext_ln391_8_fu_726_p1 = shl_ln391_1_fu_718_p3;

assign zext_ln391_9_fu_787_p1 = shl_ln391_2_fu_779_p3;

assign zext_ln391_cast_fu_496_p1 = zext_ln391;

always @ (posedge ap_clk) begin
    zext_ln382_cast_reg_1040[31:16] <= 16'b0000000000000000;
    zext_ln391_5_cast_reg_1045[31:16] <= 16'b0000000000000000;
    zext_ln391_4_cast_reg_1050[31:16] <= 16'b0000000000000000;
    zext_ln391_3_cast_reg_1055[31:16] <= 16'b0000000000000000;
    zext_ln391_2_cast_reg_1060[31:16] <= 16'b0000000000000000;
    zext_ln391_1_cast_reg_1065[31:16] <= 16'b0000000000000000;
    zext_ln391_cast_reg_1070[31:16] <= 16'b0000000000000000;
    base_col_B_cast_cast_reg_1075[31:16] <= 16'b0000000000000000;
    tmp_2_reg_1084[2:0] <= 3'b000;
end

endmodule //mxm_execute_ursa_mxm_execute_ursa_Pipeline_VITIS_LOOP_382_7
