// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mxm_execute_ursa_mxm_execute_ursa_Pipeline_STREAM_K (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_aw_AWVALID,
        m_axi_aw_AWREADY,
        m_axi_aw_AWADDR,
        m_axi_aw_AWID,
        m_axi_aw_AWLEN,
        m_axi_aw_AWSIZE,
        m_axi_aw_AWBURST,
        m_axi_aw_AWLOCK,
        m_axi_aw_AWCACHE,
        m_axi_aw_AWPROT,
        m_axi_aw_AWQOS,
        m_axi_aw_AWREGION,
        m_axi_aw_AWUSER,
        m_axi_aw_WVALID,
        m_axi_aw_WREADY,
        m_axi_aw_WDATA,
        m_axi_aw_WSTRB,
        m_axi_aw_WLAST,
        m_axi_aw_WID,
        m_axi_aw_WUSER,
        m_axi_aw_ARVALID,
        m_axi_aw_ARREADY,
        m_axi_aw_ARADDR,
        m_axi_aw_ARID,
        m_axi_aw_ARLEN,
        m_axi_aw_ARSIZE,
        m_axi_aw_ARBURST,
        m_axi_aw_ARLOCK,
        m_axi_aw_ARCACHE,
        m_axi_aw_ARPROT,
        m_axi_aw_ARQOS,
        m_axi_aw_ARREGION,
        m_axi_aw_ARUSER,
        m_axi_aw_RVALID,
        m_axi_aw_RREADY,
        m_axi_aw_RDATA,
        m_axi_aw_RLAST,
        m_axi_aw_RID,
        m_axi_aw_RFIFONUM,
        m_axi_aw_RUSER,
        m_axi_aw_RRESP,
        m_axi_aw_BVALID,
        m_axi_aw_BREADY,
        m_axi_aw_BRESP,
        m_axi_aw_BID,
        m_axi_aw_BUSER,
        m_axi_bi_AWVALID,
        m_axi_bi_AWREADY,
        m_axi_bi_AWADDR,
        m_axi_bi_AWID,
        m_axi_bi_AWLEN,
        m_axi_bi_AWSIZE,
        m_axi_bi_AWBURST,
        m_axi_bi_AWLOCK,
        m_axi_bi_AWCACHE,
        m_axi_bi_AWPROT,
        m_axi_bi_AWQOS,
        m_axi_bi_AWREGION,
        m_axi_bi_AWUSER,
        m_axi_bi_WVALID,
        m_axi_bi_WREADY,
        m_axi_bi_WDATA,
        m_axi_bi_WSTRB,
        m_axi_bi_WLAST,
        m_axi_bi_WID,
        m_axi_bi_WUSER,
        m_axi_bi_ARVALID,
        m_axi_bi_ARREADY,
        m_axi_bi_ARADDR,
        m_axi_bi_ARID,
        m_axi_bi_ARLEN,
        m_axi_bi_ARSIZE,
        m_axi_bi_ARBURST,
        m_axi_bi_ARLOCK,
        m_axi_bi_ARCACHE,
        m_axi_bi_ARPROT,
        m_axi_bi_ARQOS,
        m_axi_bi_ARREGION,
        m_axi_bi_ARUSER,
        m_axi_bi_RVALID,
        m_axi_bi_RREADY,
        m_axi_bi_RDATA,
        m_axi_bi_RLAST,
        m_axi_bi_RID,
        m_axi_bi_RFIFONUM,
        m_axi_bi_RUSER,
        m_axi_bi_RRESP,
        m_axi_bi_BVALID,
        m_axi_bi_BREADY,
        m_axi_bi_BRESP,
        m_axi_bi_BID,
        m_axi_bi_BUSER,
        sub22,
        zext_ln186,
        zext_ln183,
        m,
        select_ln192_1,
        addr_a0,
        zext_ln186_1,
        addr_b0,
        zext_ln76,
        zext_ln183_1,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_i,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o_ap_vld,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_i,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o_ap_vld,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_i,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o_ap_vld,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_i,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_aw_AWVALID;
input   m_axi_aw_AWREADY;
output  [31:0] m_axi_aw_AWADDR;
output  [0:0] m_axi_aw_AWID;
output  [31:0] m_axi_aw_AWLEN;
output  [2:0] m_axi_aw_AWSIZE;
output  [1:0] m_axi_aw_AWBURST;
output  [1:0] m_axi_aw_AWLOCK;
output  [3:0] m_axi_aw_AWCACHE;
output  [2:0] m_axi_aw_AWPROT;
output  [3:0] m_axi_aw_AWQOS;
output  [3:0] m_axi_aw_AWREGION;
output  [0:0] m_axi_aw_AWUSER;
output   m_axi_aw_WVALID;
input   m_axi_aw_WREADY;
output  [7:0] m_axi_aw_WDATA;
output  [0:0] m_axi_aw_WSTRB;
output   m_axi_aw_WLAST;
output  [0:0] m_axi_aw_WID;
output  [0:0] m_axi_aw_WUSER;
output   m_axi_aw_ARVALID;
input   m_axi_aw_ARREADY;
output  [31:0] m_axi_aw_ARADDR;
output  [0:0] m_axi_aw_ARID;
output  [31:0] m_axi_aw_ARLEN;
output  [2:0] m_axi_aw_ARSIZE;
output  [1:0] m_axi_aw_ARBURST;
output  [1:0] m_axi_aw_ARLOCK;
output  [3:0] m_axi_aw_ARCACHE;
output  [2:0] m_axi_aw_ARPROT;
output  [3:0] m_axi_aw_ARQOS;
output  [3:0] m_axi_aw_ARREGION;
output  [0:0] m_axi_aw_ARUSER;
input   m_axi_aw_RVALID;
output   m_axi_aw_RREADY;
input  [7:0] m_axi_aw_RDATA;
input   m_axi_aw_RLAST;
input  [0:0] m_axi_aw_RID;
input  [11:0] m_axi_aw_RFIFONUM;
input  [0:0] m_axi_aw_RUSER;
input  [1:0] m_axi_aw_RRESP;
input   m_axi_aw_BVALID;
output   m_axi_aw_BREADY;
input  [1:0] m_axi_aw_BRESP;
input  [0:0] m_axi_aw_BID;
input  [0:0] m_axi_aw_BUSER;
output   m_axi_bi_AWVALID;
input   m_axi_bi_AWREADY;
output  [31:0] m_axi_bi_AWADDR;
output  [0:0] m_axi_bi_AWID;
output  [31:0] m_axi_bi_AWLEN;
output  [2:0] m_axi_bi_AWSIZE;
output  [1:0] m_axi_bi_AWBURST;
output  [1:0] m_axi_bi_AWLOCK;
output  [3:0] m_axi_bi_AWCACHE;
output  [2:0] m_axi_bi_AWPROT;
output  [3:0] m_axi_bi_AWQOS;
output  [3:0] m_axi_bi_AWREGION;
output  [0:0] m_axi_bi_AWUSER;
output   m_axi_bi_WVALID;
input   m_axi_bi_WREADY;
output  [7:0] m_axi_bi_WDATA;
output  [0:0] m_axi_bi_WSTRB;
output   m_axi_bi_WLAST;
output  [0:0] m_axi_bi_WID;
output  [0:0] m_axi_bi_WUSER;
output   m_axi_bi_ARVALID;
input   m_axi_bi_ARREADY;
output  [31:0] m_axi_bi_ARADDR;
output  [0:0] m_axi_bi_ARID;
output  [31:0] m_axi_bi_ARLEN;
output  [2:0] m_axi_bi_ARSIZE;
output  [1:0] m_axi_bi_ARBURST;
output  [1:0] m_axi_bi_ARLOCK;
output  [3:0] m_axi_bi_ARCACHE;
output  [2:0] m_axi_bi_ARPROT;
output  [3:0] m_axi_bi_ARQOS;
output  [3:0] m_axi_bi_ARREGION;
output  [0:0] m_axi_bi_ARUSER;
input   m_axi_bi_RVALID;
output   m_axi_bi_RREADY;
input  [7:0] m_axi_bi_RDATA;
input   m_axi_bi_RLAST;
input  [0:0] m_axi_bi_RID;
input  [11:0] m_axi_bi_RFIFONUM;
input  [0:0] m_axi_bi_RUSER;
input  [1:0] m_axi_bi_RRESP;
input   m_axi_bi_BVALID;
output   m_axi_bi_BREADY;
input  [1:0] m_axi_bi_BRESP;
input  [0:0] m_axi_bi_BID;
input  [0:0] m_axi_bi_BUSER;
input  [16:0] sub22;
input  [15:0] zext_ln186;
input  [15:0] zext_ln183;
input  [15:0] m;
input  [31:0] select_ln192_1;
input  [31:0] addr_a0;
input  [16:0] zext_ln186_1;
input  [31:0] addr_b0;
input  [15:0] zext_ln76;
input  [15:0] zext_ln183_1;
input  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_i;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o_ap_vld;
input  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_i;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o_ap_vld;
input  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_i;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o_ap_vld;
input  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_i;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o_ap_vld;

reg ap_idle;
reg m_axi_aw_ARVALID;
reg[31:0] m_axi_aw_ARADDR;
reg m_axi_aw_RREADY;
reg m_axi_bi_ARVALID;
reg[31:0] m_axi_bi_ARADDR;
reg m_axi_bi_RREADY;
reg[19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o;
reg mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o_ap_vld;
reg[19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o;
reg mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o_ap_vld;
reg[19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o;
reg mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o_ap_vld;
reg[19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o;
reg mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln207_reg_636;
reg   [0:0] icmp_ln22_reg_640;
reg    ap_predicate_op73_readreq_state2;
reg    ap_block_state2_io;
reg   [0:0] icmp_ln207_reg_636_pp0_iter1_reg;
reg   [0:0] icmp_ln22_reg_640_pp0_iter1_reg;
reg    ap_predicate_op89_readreq_state4;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln207_reg_636_pp0_iter4_reg;
reg   [0:0] icmp_ln22_reg_640_pp0_iter4_reg;
reg    ap_predicate_op110_read_state10;
reg    ap_block_state10_pp0_stage1_iter4;
reg   [0:0] icmp_ln207_reg_636_pp0_iter5_reg;
reg   [0:0] icmp_ln22_reg_640_pp0_iter5_reg;
reg    ap_predicate_op121_read_state12;
reg    ap_block_state12_pp0_stage1_iter5;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg  signed [7:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_7;
reg  signed [7:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_6;
reg   [7:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_5;
reg   [7:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_4;
reg    bi_blk_n_AR;
wire    ap_block_pp0_stage1;
reg    bi_blk_n_R;
wire    ap_block_pp0_stage0;
reg   [0:0] and_ln18_reg_650;
reg   [0:0] and_ln18_reg_650_pp0_iter1_reg;
reg   [0:0] and_ln18_reg_650_pp0_iter5_reg;
reg    aw_blk_n_AR;
reg    aw_blk_n_R;
reg   [0:0] and_ln18_reg_650_pp0_iter4_reg;
reg  signed [7:0] in_a_reg_212;
reg  signed [7:0] in_a_1_reg_224;
reg    ap_predicate_op78_readreq_state3;
reg    ap_block_state3_io;
reg    ap_predicate_op93_readreq_state5;
reg    ap_block_state5_io;
reg    ap_predicate_op115_read_state11;
reg    ap_block_state11_pp0_stage0_iter5;
reg    ap_predicate_op129_read_state13;
reg    ap_block_state13_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_11001;
wire   [16:0] zext_ln183_1_cast_fu_258_p1;
reg   [16:0] zext_ln183_1_cast_reg_620;
wire   [31:0] zext_ln76_cast_fu_262_p1;
reg   [31:0] zext_ln76_cast_reg_625;
wire   [31:0] zext_ln183_cast_fu_270_p1;
reg   [31:0] zext_ln183_cast_reg_631;
wire   [0:0] icmp_ln207_fu_290_p2;
reg   [0:0] icmp_ln207_reg_636_pp0_iter2_reg;
reg   [0:0] icmp_ln207_reg_636_pp0_iter3_reg;
reg   [0:0] icmp_ln207_reg_636_pp0_iter6_reg;
wire   [0:0] icmp_ln22_fu_306_p2;
reg   [0:0] icmp_ln22_reg_640_pp0_iter2_reg;
reg   [0:0] icmp_ln22_reg_640_pp0_iter3_reg;
reg   [31:0] aw_addr_reg_644;
wire   [0:0] and_ln18_fu_364_p2;
reg   [0:0] and_ln18_reg_650_pp0_iter2_reg;
reg   [0:0] and_ln18_reg_650_pp0_iter3_reg;
reg   [0:0] and_ln18_reg_650_pp0_iter6_reg;
reg   [31:0] aw_addr_1_reg_654;
wire   [16:0] sub_ln60_fu_400_p2;
reg  signed [16:0] sub_ln60_reg_660;
wire   [31:0] row_off_fu_414_p2;
reg   [31:0] row_off_reg_665;
reg    ap_block_pp0_stage1_11001;
wire   [16:0] add_ln76_3_fu_419_p2;
reg   [16:0] add_ln76_3_reg_671;
reg   [31:0] bi_addr_reg_676;
reg   [31:0] bi_addr_1_reg_682;
reg   [7:0] aw_addr_read_reg_688;
reg   [7:0] aw_addr_1_read_reg_693;
reg   [7:0] bi_addr_read_reg_698;
reg   [7:0] bi_addr_1_read_reg_713;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire  signed [7:0] ap_phi_reg_pp0_iter4_in_a_reg_212;
reg  signed [7:0] ap_phi_reg_pp0_iter5_in_a_reg_212;
reg  signed [7:0] ap_phi_mux_in_a_1_phi_fu_228_p4;
wire  signed [7:0] ap_phi_reg_pp0_iter5_in_a_1_reg_224;
reg   [7:0] ap_phi_mux_in_b_phi_fu_240_p4;
reg   [7:0] ap_phi_mux_value_b_phi_fu_251_p4;
wire   [31:0] sub_ln23_fu_334_p2;
wire   [31:0] sub_ln23_1_fu_382_p2;
wire   [31:0] add_ln76_1_fu_428_p2;
wire   [31:0] add_ln76_4_fu_451_p2;
wire  signed [19:0] grp_fu_580_p3;
wire  signed [19:0] grp_fu_598_p3;
wire  signed [19:0] grp_fu_571_p3;
wire  signed [19:0] grp_fu_589_p3;
reg   [15:0] t_fu_100;
wire   [15:0] k_fu_296_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_t_2;
wire   [16:0] zext_ln207_1_fu_286_p1;
wire   [16:0] zext_ln186_cast_fu_274_p1;
wire   [16:0] add_ln23_1_fu_318_p2;
wire  signed [31:0] sext_ln23_fu_324_p1;
wire   [31:0] add_ln23_fu_312_p2;
wire   [31:0] add_ln23_2_fu_328_p2;
wire   [31:0] zext_ln207_fu_302_p1;
wire   [16:0] add_ln22_fu_352_p2;
wire   [0:0] icmp_ln18_fu_346_p2;
wire   [0:0] icmp_ln22_1_fu_358_p2;
wire   [31:0] add_ln23_3_fu_370_p2;
wire   [31:0] zext_ln186_1_cast_fu_266_p1;
wire   [31:0] add_ln23_4_fu_376_p2;
wire   [16:0] add_ln60_fu_394_p2;
wire   [15:0] row_off_fu_414_p1;
wire   [31:0] add_ln76_fu_424_p2;
wire   [31:0] zext_ln76_1_fu_443_p1;
wire   [31:0] add_ln76_5_fu_446_p2;
wire   [31:0] add_ln76_2_fu_439_p2;
wire   [7:0] grp_fu_571_p0;
wire   [7:0] grp_fu_580_p0;
wire   [7:0] grp_fu_589_p0;
wire   [7:0] grp_fu_598_p1;
reg    grp_fu_571_ce;
reg    grp_fu_580_ce;
reg    grp_fu_589_ce;
reg    grp_fu_598_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter7_stage0;
reg    ap_idle_pp0_0to6;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to8;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_571_p00;
wire   [15:0] grp_fu_580_p00;
wire   [15:0] grp_fu_589_p00;
wire   [15:0] grp_fu_598_p10;
reg    ap_condition_476;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_7 = 8'd0;
#0 mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_6 = 8'd0;
#0 mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_5 = 8'd0;
#0 mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_4 = 8'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 t_fu_100 = 16'd0;
#0 ap_done_reg = 1'b0;
end

mxm_execute_ursa_mul_17s_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_17s_16ns_32_1_1_U1(
    .din0(sub_ln60_reg_660),
    .din1(row_off_fu_414_p1),
    .dout(row_off_fu_414_p2)
);

mxm_execute_ursa_mac_muladd_8ns_8s_20s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 20 ))
mac_muladd_8ns_8s_20s_20_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_571_p0),
    .din1(ap_phi_mux_in_a_1_phi_fu_228_p4),
    .din2(mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_i),
    .ce(grp_fu_571_ce),
    .dout(grp_fu_571_p3)
);

mxm_execute_ursa_mac_muladd_8ns_8s_20s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 20 ))
mac_muladd_8ns_8s_20s_20_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_580_p0),
    .din1(in_a_reg_212),
    .din2(mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_i),
    .ce(grp_fu_580_ce),
    .dout(grp_fu_580_p3)
);

mxm_execute_ursa_mac_muladd_8ns_8s_20s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 20 ))
mac_muladd_8ns_8s_20s_20_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_589_p0),
    .din1(mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_6),
    .din2(mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_i),
    .ce(grp_fu_589_ce),
    .dout(grp_fu_589_p3)
);

mxm_execute_ursa_mac_muladd_8s_8ns_20s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 20 ),
    .dout_WIDTH( 20 ))
mac_muladd_8s_8ns_20s_20_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_7),
    .din1(grp_fu_598_p1),
    .din2(mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_i),
    .ce(grp_fu_598_ce),
    .dout(grp_fu_598_p3)
);

mxm_execute_ursa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter8 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln22_reg_640_pp0_iter4_reg == 1'd1) & (icmp_ln207_reg_636_pp0_iter4_reg == 1'd1))) begin
        ap_phi_reg_pp0_iter5_in_a_reg_212 <= aw_addr_read_reg_688;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_phi_reg_pp0_iter5_in_a_reg_212 <= ap_phi_reg_pp0_iter4_in_a_reg_212;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_476)) begin
        if (((icmp_ln207_reg_636_pp0_iter5_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter5_reg))) begin
            in_a_1_reg_224 <= aw_addr_1_read_reg_693;
        end else if ((1'b1 == 1'b1)) begin
            in_a_1_reg_224 <= ap_phi_reg_pp0_iter5_in_a_1_reg_224;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln207_fu_290_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_100 <= k_fu_296_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_100 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln76_3_reg_671 <= add_ln76_3_fu_419_p2;
        aw_addr_read_reg_688 <= m_axi_aw_RDATA;
        bi_addr_read_reg_698 <= m_axi_bi_RDATA;
        row_off_reg_665 <= row_off_fu_414_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln18_reg_650 <= and_ln18_fu_364_p2;
        and_ln18_reg_650_pp0_iter1_reg <= and_ln18_reg_650;
        and_ln18_reg_650_pp0_iter2_reg <= and_ln18_reg_650_pp0_iter1_reg;
        and_ln18_reg_650_pp0_iter3_reg <= and_ln18_reg_650_pp0_iter2_reg;
        and_ln18_reg_650_pp0_iter4_reg <= and_ln18_reg_650_pp0_iter3_reg;
        and_ln18_reg_650_pp0_iter5_reg <= and_ln18_reg_650_pp0_iter4_reg;
        and_ln18_reg_650_pp0_iter6_reg <= and_ln18_reg_650_pp0_iter5_reg;
        aw_addr_1_read_reg_693 <= m_axi_aw_RDATA;
        aw_addr_1_reg_654 <= sub_ln23_1_fu_382_p2;
        aw_addr_reg_644 <= sub_ln23_fu_334_p2;
        bi_addr_1_read_reg_713 <= m_axi_bi_RDATA;
        bi_addr_1_reg_682 <= add_ln76_4_fu_451_p2;
        bi_addr_reg_676 <= add_ln76_1_fu_428_p2;
        icmp_ln207_reg_636 <= icmp_ln207_fu_290_p2;
        icmp_ln207_reg_636_pp0_iter1_reg <= icmp_ln207_reg_636;
        icmp_ln207_reg_636_pp0_iter2_reg <= icmp_ln207_reg_636_pp0_iter1_reg;
        icmp_ln207_reg_636_pp0_iter3_reg <= icmp_ln207_reg_636_pp0_iter2_reg;
        icmp_ln207_reg_636_pp0_iter4_reg <= icmp_ln207_reg_636_pp0_iter3_reg;
        icmp_ln207_reg_636_pp0_iter5_reg <= icmp_ln207_reg_636_pp0_iter4_reg;
        icmp_ln207_reg_636_pp0_iter6_reg <= icmp_ln207_reg_636_pp0_iter5_reg;
        icmp_ln22_reg_640 <= icmp_ln22_fu_306_p2;
        icmp_ln22_reg_640_pp0_iter1_reg <= icmp_ln22_reg_640;
        icmp_ln22_reg_640_pp0_iter2_reg <= icmp_ln22_reg_640_pp0_iter1_reg;
        icmp_ln22_reg_640_pp0_iter3_reg <= icmp_ln22_reg_640_pp0_iter2_reg;
        icmp_ln22_reg_640_pp0_iter4_reg <= icmp_ln22_reg_640_pp0_iter3_reg;
        icmp_ln22_reg_640_pp0_iter5_reg <= icmp_ln22_reg_640_pp0_iter4_reg;
        sub_ln60_reg_660 <= sub_ln60_fu_400_p2;
        zext_ln183_1_cast_reg_620[15 : 0] <= zext_ln183_1_cast_fu_258_p1[15 : 0];
        zext_ln183_cast_reg_631[15 : 0] <= zext_ln183_cast_fu_270_p1[15 : 0];
        zext_ln76_cast_reg_625[15 : 0] <= zext_ln76_cast_fu_262_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        in_a_reg_212 <= ap_phi_reg_pp0_iter5_in_a_reg_212;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_4 <= ap_phi_mux_value_b_phi_fu_251_p4;
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_7 <= in_a_reg_212;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_5 <= ap_phi_mux_in_b_phi_fu_240_p4;
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_6 <= in_a_1_reg_224;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln207_reg_636 == 1'd0))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln207_reg_636_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter7_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter7_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to6 = 1'b1;
    end else begin
        ap_idle_pp0_0to6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to8 = 1'b1;
    end else begin
        ap_idle_pp0_1to8 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln207_reg_636_pp0_iter5_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter5_reg))) begin
        ap_phi_mux_in_a_1_phi_fu_228_p4 = aw_addr_1_read_reg_693;
    end else begin
        ap_phi_mux_in_a_1_phi_fu_228_p4 = 8'd0;
    end
end

always @ (*) begin
    if (((icmp_ln22_reg_640_pp0_iter5_reg == 1'd1) & (icmp_ln207_reg_636_pp0_iter5_reg == 1'd1))) begin
        ap_phi_mux_in_b_phi_fu_240_p4 = bi_addr_read_reg_698;
    end else begin
        ap_phi_mux_in_b_phi_fu_240_p4 = 8'd0;
    end
end

always @ (*) begin
    if (((icmp_ln207_reg_636_pp0_iter6_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter6_reg))) begin
        ap_phi_mux_value_b_phi_fu_251_p4 = bi_addr_1_read_reg_713;
    end else begin
        ap_phi_mux_value_b_phi_fu_251_p4 = 8'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_t_2 = 16'd0;
    end else begin
        ap_sig_allocacmp_t_2 = t_fu_100;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln18_reg_650) & (icmp_ln207_reg_636 == 1'd1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (ap_predicate_op73_readreq_state2 == 1'b1)))) begin
        aw_blk_n_AR = m_axi_aw_ARREADY;
    end else begin
        aw_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln207_reg_636_pp0_iter4_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter4_reg)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (ap_predicate_op110_read_state10 == 1'b1)))) begin
        aw_blk_n_R = m_axi_aw_RVALID;
    end else begin
        aw_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln207_reg_636_pp0_iter1_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter1_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (ap_predicate_op89_readreq_state4 == 1'b1)))) begin
        bi_blk_n_AR = m_axi_bi_ARREADY;
    end else begin
        bi_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln207_reg_636_pp0_iter5_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln18_reg_650_pp0_iter5_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op121_read_state12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        bi_blk_n_R = m_axi_bi_RVALID;
    end else begin
        bi_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_571_ce = 1'b1;
    end else begin
        grp_fu_571_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_580_ce = 1'b1;
    end else begin
        grp_fu_580_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_589_ce = 1'b1;
    end else begin
        grp_fu_589_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_598_ce = 1'b1;
    end else begin
        grp_fu_598_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op78_readreq_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_aw_ARADDR = aw_addr_1_reg_654;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op73_readreq_state2 == 1'b1))) begin
        m_axi_aw_ARADDR = aw_addr_reg_644;
    end else begin
        m_axi_aw_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op78_readreq_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op73_readreq_state2 == 1'b1)))) begin
        m_axi_aw_ARVALID = 1'b1;
    end else begin
        m_axi_aw_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op115_read_state11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op110_read_state10 == 1'b1)))) begin
        m_axi_aw_RREADY = 1'b1;
    end else begin
        m_axi_aw_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op93_readreq_state5 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_bi_ARADDR = bi_addr_1_reg_682;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op89_readreq_state4 == 1'b1))) begin
        m_axi_bi_ARADDR = bi_addr_reg_676;
    end else begin
        m_axi_bi_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op93_readreq_state5 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op89_readreq_state4 == 1'b1)))) begin
        m_axi_bi_ARVALID = 1'b1;
    end else begin
        m_axi_bi_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op129_read_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op121_read_state12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_bi_RREADY = 1'b1;
    end else begin
        m_axi_bi_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o = grp_fu_571_p3;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o = mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o_ap_vld = 1'b1;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o = grp_fu_598_p3;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o = mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o_ap_vld = 1'b1;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o = grp_fu_580_p3;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o = mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o_ap_vld = 1'b1;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o = grp_fu_589_p3;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o = mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o_ap_vld = 1'b1;
    end else begin
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to8 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln22_fu_352_p2 = (zext_ln186_cast_fu_274_p1 + 17'd1);

assign add_ln23_1_fu_318_p2 = ($signed(zext_ln186_cast_fu_274_p1) + $signed(17'd131071));

assign add_ln23_2_fu_328_p2 = ($signed(sext_ln23_fu_324_p1) + $signed(add_ln23_fu_312_p2));

assign add_ln23_3_fu_370_p2 = (select_ln192_1 + addr_a0);

assign add_ln23_4_fu_376_p2 = (add_ln23_3_fu_370_p2 + zext_ln186_1_cast_fu_266_p1);

assign add_ln23_fu_312_p2 = (select_ln192_1 + addr_a0);

assign add_ln60_fu_394_p2 = ($signed(zext_ln186_cast_fu_274_p1) + $signed(17'd131071));

assign add_ln76_1_fu_428_p2 = (add_ln76_fu_424_p2 + zext_ln76_cast_reg_625);

assign add_ln76_2_fu_439_p2 = (zext_ln76_cast_reg_625 + addr_b0);

assign add_ln76_3_fu_419_p2 = (zext_ln183_1_cast_reg_620 + 17'd1);

assign add_ln76_4_fu_451_p2 = (add_ln76_5_fu_446_p2 + add_ln76_2_fu_439_p2);

assign add_ln76_5_fu_446_p2 = (zext_ln76_1_fu_443_p1 + row_off_reg_665);

assign add_ln76_fu_424_p2 = (row_off_reg_665 + addr_b0);

assign and_ln18_fu_364_p2 = (icmp_ln22_1_fu_358_p2 & icmp_ln18_fu_346_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_io)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state5_io)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage1_iter5)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage1_iter5)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter4 = ((m_axi_aw_RVALID == 1'b0) & (ap_predicate_op110_read_state10 == 1'b1));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter5 = ((m_axi_aw_RVALID == 1'b0) & (ap_predicate_op115_read_state11 == 1'b1));
end

always @ (*) begin
    ap_block_state12_pp0_stage1_iter5 = ((ap_predicate_op121_read_state12 == 1'b1) & (m_axi_bi_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp0_stage0_iter6 = ((ap_predicate_op129_read_state13 == 1'b1) & (m_axi_bi_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((m_axi_aw_ARREADY == 1'b0) & (ap_predicate_op73_readreq_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_aw_ARREADY == 1'b0) & (ap_predicate_op78_readreq_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_io = ((ap_predicate_op89_readreq_state4 == 1'b1) & (m_axi_bi_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_io = ((ap_predicate_op93_readreq_state5 == 1'b1) & (m_axi_bi_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_476 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter4_in_a_reg_212 = 8'd0;

assign ap_phi_reg_pp0_iter5_in_a_1_reg_224 = 8'd0;

always @ (*) begin
    ap_predicate_op110_read_state10 = ((icmp_ln22_reg_640_pp0_iter4_reg == 1'd1) & (icmp_ln207_reg_636_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op115_read_state11 = ((icmp_ln207_reg_636_pp0_iter4_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter4_reg));
end

always @ (*) begin
    ap_predicate_op121_read_state12 = ((icmp_ln22_reg_640_pp0_iter5_reg == 1'd1) & (icmp_ln207_reg_636_pp0_iter5_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op129_read_state13 = ((icmp_ln207_reg_636_pp0_iter5_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter5_reg));
end

always @ (*) begin
    ap_predicate_op73_readreq_state2 = ((icmp_ln22_reg_640 == 1'd1) & (icmp_ln207_reg_636 == 1'd1));
end

always @ (*) begin
    ap_predicate_op78_readreq_state3 = ((1'd1 == and_ln18_reg_650) & (icmp_ln207_reg_636 == 1'd1));
end

always @ (*) begin
    ap_predicate_op89_readreq_state4 = ((icmp_ln22_reg_640_pp0_iter1_reg == 1'd1) & (icmp_ln207_reg_636_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op93_readreq_state5 = ((icmp_ln207_reg_636_pp0_iter1_reg == 1'd1) & (1'd1 == and_ln18_reg_650_pp0_iter1_reg));
end

assign grp_fu_571_p0 = grp_fu_571_p00;

assign grp_fu_571_p00 = mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_5;

assign grp_fu_580_p0 = grp_fu_580_p00;

assign grp_fu_580_p00 = ap_phi_mux_in_b_phi_fu_240_p4;

assign grp_fu_589_p0 = grp_fu_589_p00;

assign grp_fu_589_p00 = mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_4;

assign grp_fu_598_p1 = grp_fu_598_p10;

assign grp_fu_598_p10 = ap_phi_mux_value_b_phi_fu_251_p4;

assign icmp_ln18_fu_346_p2 = ((ap_sig_allocacmp_t_2 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln207_fu_290_p2 = ((sub22 > zext_ln207_1_fu_286_p1) ? 1'b1 : 1'b0);

assign icmp_ln22_1_fu_358_p2 = ((add_ln22_fu_352_p2 > zext_ln207_1_fu_286_p1) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_306_p2 = ((ap_sig_allocacmp_t_2 < m) ? 1'b1 : 1'b0);

assign k_fu_296_p2 = (ap_sig_allocacmp_t_2 + 16'd1);

assign m_axi_aw_ARBURST = 2'd0;

assign m_axi_aw_ARCACHE = 4'd0;

assign m_axi_aw_ARID = 1'd0;

assign m_axi_aw_ARLEN = 32'd1;

assign m_axi_aw_ARLOCK = 2'd0;

assign m_axi_aw_ARPROT = 3'd0;

assign m_axi_aw_ARQOS = 4'd0;

assign m_axi_aw_ARREGION = 4'd0;

assign m_axi_aw_ARSIZE = 3'd0;

assign m_axi_aw_ARUSER = 1'd0;

assign m_axi_aw_AWADDR = 32'd0;

assign m_axi_aw_AWBURST = 2'd0;

assign m_axi_aw_AWCACHE = 4'd0;

assign m_axi_aw_AWID = 1'd0;

assign m_axi_aw_AWLEN = 32'd0;

assign m_axi_aw_AWLOCK = 2'd0;

assign m_axi_aw_AWPROT = 3'd0;

assign m_axi_aw_AWQOS = 4'd0;

assign m_axi_aw_AWREGION = 4'd0;

assign m_axi_aw_AWSIZE = 3'd0;

assign m_axi_aw_AWUSER = 1'd0;

assign m_axi_aw_AWVALID = 1'b0;

assign m_axi_aw_BREADY = 1'b0;

assign m_axi_aw_WDATA = 8'd0;

assign m_axi_aw_WID = 1'd0;

assign m_axi_aw_WLAST = 1'b0;

assign m_axi_aw_WSTRB = 1'd0;

assign m_axi_aw_WUSER = 1'd0;

assign m_axi_aw_WVALID = 1'b0;

assign m_axi_bi_ARBURST = 2'd0;

assign m_axi_bi_ARCACHE = 4'd0;

assign m_axi_bi_ARID = 1'd0;

assign m_axi_bi_ARLEN = 32'd1;

assign m_axi_bi_ARLOCK = 2'd0;

assign m_axi_bi_ARPROT = 3'd0;

assign m_axi_bi_ARQOS = 4'd0;

assign m_axi_bi_ARREGION = 4'd0;

assign m_axi_bi_ARSIZE = 3'd0;

assign m_axi_bi_ARUSER = 1'd0;

assign m_axi_bi_AWADDR = 32'd0;

assign m_axi_bi_AWBURST = 2'd0;

assign m_axi_bi_AWCACHE = 4'd0;

assign m_axi_bi_AWID = 1'd0;

assign m_axi_bi_AWLEN = 32'd0;

assign m_axi_bi_AWLOCK = 2'd0;

assign m_axi_bi_AWPROT = 3'd0;

assign m_axi_bi_AWQOS = 4'd0;

assign m_axi_bi_AWREGION = 4'd0;

assign m_axi_bi_AWSIZE = 3'd0;

assign m_axi_bi_AWUSER = 1'd0;

assign m_axi_bi_AWVALID = 1'b0;

assign m_axi_bi_BREADY = 1'b0;

assign m_axi_bi_WDATA = 8'd0;

assign m_axi_bi_WID = 1'd0;

assign m_axi_bi_WLAST = 1'b0;

assign m_axi_bi_WSTRB = 1'd0;

assign m_axi_bi_WUSER = 1'd0;

assign m_axi_bi_WVALID = 1'b0;

assign row_off_fu_414_p1 = zext_ln183_cast_reg_631;

assign sext_ln23_fu_324_p1 = $signed(add_ln23_1_fu_318_p2);

assign sub_ln23_1_fu_382_p2 = (add_ln23_4_fu_376_p2 - zext_ln207_fu_302_p1);

assign sub_ln23_fu_334_p2 = (add_ln23_2_fu_328_p2 - zext_ln207_fu_302_p1);

assign sub_ln60_fu_400_p2 = (add_ln60_fu_394_p2 - zext_ln207_1_fu_286_p1);

assign zext_ln183_1_cast_fu_258_p1 = zext_ln183_1;

assign zext_ln183_cast_fu_270_p1 = zext_ln183;

assign zext_ln186_1_cast_fu_266_p1 = zext_ln186_1;

assign zext_ln186_cast_fu_274_p1 = zext_ln186;

assign zext_ln207_1_fu_286_p1 = ap_sig_allocacmp_t_2;

assign zext_ln207_fu_302_p1 = ap_sig_allocacmp_t_2;

assign zext_ln76_1_fu_443_p1 = add_ln76_3_reg_671;

assign zext_ln76_cast_fu_262_p1 = zext_ln76;

always @ (posedge ap_clk) begin
    zext_ln183_1_cast_reg_620[16] <= 1'b0;
    zext_ln76_cast_reg_625[31:16] <= 16'b0000000000000000;
    zext_ln183_cast_reg_631[31:16] <= 16'b0000000000000000;
end

endmodule //mxm_execute_ursa_mxm_execute_ursa_Pipeline_STREAM_K
