// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mxm_execute_ursa_sa_reset (
        ap_ready,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_ap_vld,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_ap_vld,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_ap_vld,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i,
        mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_ap_vld
);


output   ap_ready;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_ap_vld;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_ap_vld;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_ap_vld;
output  [19:0] mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i;
output   mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_ap_vld;

assign ap_ready = 1'b1;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i = 20'd0;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1 = 20'd0;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_1_ap_vld = 1'b1;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2 = 20'd0;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_2_ap_vld = 1'b1;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3 = 20'd0;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_3_ap_vld = 1'b1;

assign mxm_execute_ursa_signed_char_unsigned_short_unsigned_char_unsigned_short_i_ap_vld = 1'b1;

endmodule //mxm_execute_ursa_sa_reset
