// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="shell_top_shell_top,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=5155,HLS_SYN_LUT=6245,HLS_VERSION=2023_2}" *)

module shell_top (
        s_axi_ap_AWVALID,
        s_axi_ap_AWREADY,
        s_axi_ap_AWADDR,
        s_axi_ap_WVALID,
        s_axi_ap_WREADY,
        s_axi_ap_WDATA,
        s_axi_ap_WSTRB,
        s_axi_ap_ARVALID,
        s_axi_ap_ARREADY,
        s_axi_ap_ARADDR,
        s_axi_ap_RVALID,
        s_axi_ap_RREADY,
        s_axi_ap_RDATA,
        s_axi_ap_RRESP,
        s_axi_ap_BVALID,
        s_axi_ap_BREADY,
        s_axi_ap_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        m_axi_aw_AWVALID,
        m_axi_aw_AWREADY,
        m_axi_aw_AWADDR,
        m_axi_aw_AWID,
        m_axi_aw_AWLEN,
        m_axi_aw_AWSIZE,
        m_axi_aw_AWBURST,
        m_axi_aw_AWLOCK,
        m_axi_aw_AWCACHE,
        m_axi_aw_AWPROT,
        m_axi_aw_AWQOS,
        m_axi_aw_AWREGION,
        m_axi_aw_AWUSER,
        m_axi_aw_WVALID,
        m_axi_aw_WREADY,
        m_axi_aw_WDATA,
        m_axi_aw_WSTRB,
        m_axi_aw_WLAST,
        m_axi_aw_WID,
        m_axi_aw_WUSER,
        m_axi_aw_ARVALID,
        m_axi_aw_ARREADY,
        m_axi_aw_ARADDR,
        m_axi_aw_ARID,
        m_axi_aw_ARLEN,
        m_axi_aw_ARSIZE,
        m_axi_aw_ARBURST,
        m_axi_aw_ARLOCK,
        m_axi_aw_ARCACHE,
        m_axi_aw_ARPROT,
        m_axi_aw_ARQOS,
        m_axi_aw_ARREGION,
        m_axi_aw_ARUSER,
        m_axi_aw_RVALID,
        m_axi_aw_RREADY,
        m_axi_aw_RDATA,
        m_axi_aw_RLAST,
        m_axi_aw_RID,
        m_axi_aw_RUSER,
        m_axi_aw_RRESP,
        m_axi_aw_BVALID,
        m_axi_aw_BREADY,
        m_axi_aw_BRESP,
        m_axi_aw_BID,
        m_axi_aw_BUSER,
        m_axi_bi_AWVALID,
        m_axi_bi_AWREADY,
        m_axi_bi_AWADDR,
        m_axi_bi_AWID,
        m_axi_bi_AWLEN,
        m_axi_bi_AWSIZE,
        m_axi_bi_AWBURST,
        m_axi_bi_AWLOCK,
        m_axi_bi_AWCACHE,
        m_axi_bi_AWPROT,
        m_axi_bi_AWQOS,
        m_axi_bi_AWREGION,
        m_axi_bi_AWUSER,
        m_axi_bi_WVALID,
        m_axi_bi_WREADY,
        m_axi_bi_WDATA,
        m_axi_bi_WSTRB,
        m_axi_bi_WLAST,
        m_axi_bi_WID,
        m_axi_bi_WUSER,
        m_axi_bi_ARVALID,
        m_axi_bi_ARREADY,
        m_axi_bi_ARADDR,
        m_axi_bi_ARID,
        m_axi_bi_ARLEN,
        m_axi_bi_ARSIZE,
        m_axi_bi_ARBURST,
        m_axi_bi_ARLOCK,
        m_axi_bi_ARCACHE,
        m_axi_bi_ARPROT,
        m_axi_bi_ARQOS,
        m_axi_bi_ARREGION,
        m_axi_bi_ARUSER,
        m_axi_bi_RVALID,
        m_axi_bi_RREADY,
        m_axi_bi_RDATA,
        m_axi_bi_RLAST,
        m_axi_bi_RID,
        m_axi_bi_RUSER,
        m_axi_bi_RRESP,
        m_axi_bi_BVALID,
        m_axi_bi_BREADY,
        m_axi_bi_BRESP,
        m_axi_bi_BID,
        m_axi_bi_BUSER,
        m_axi_ca_AWVALID,
        m_axi_ca_AWREADY,
        m_axi_ca_AWADDR,
        m_axi_ca_AWID,
        m_axi_ca_AWLEN,
        m_axi_ca_AWSIZE,
        m_axi_ca_AWBURST,
        m_axi_ca_AWLOCK,
        m_axi_ca_AWCACHE,
        m_axi_ca_AWPROT,
        m_axi_ca_AWQOS,
        m_axi_ca_AWREGION,
        m_axi_ca_AWUSER,
        m_axi_ca_WVALID,
        m_axi_ca_WREADY,
        m_axi_ca_WDATA,
        m_axi_ca_WSTRB,
        m_axi_ca_WLAST,
        m_axi_ca_WID,
        m_axi_ca_WUSER,
        m_axi_ca_ARVALID,
        m_axi_ca_ARREADY,
        m_axi_ca_ARADDR,
        m_axi_ca_ARID,
        m_axi_ca_ARLEN,
        m_axi_ca_ARSIZE,
        m_axi_ca_ARBURST,
        m_axi_ca_ARLOCK,
        m_axi_ca_ARCACHE,
        m_axi_ca_ARPROT,
        m_axi_ca_ARQOS,
        m_axi_ca_ARREGION,
        m_axi_ca_ARUSER,
        m_axi_ca_RVALID,
        m_axi_ca_RREADY,
        m_axi_ca_RDATA,
        m_axi_ca_RLAST,
        m_axi_ca_RID,
        m_axi_ca_RUSER,
        m_axi_ca_RRESP,
        m_axi_ca_BVALID,
        m_axi_ca_BREADY,
        m_axi_ca_BRESP,
        m_axi_ca_BID,
        m_axi_ca_BUSER
);

parameter    C_S_AXI_AP_DATA_WIDTH = 32;
parameter    C_S_AXI_AP_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_M_AXI_AW_ID_WIDTH = 1;
parameter    C_M_AXI_AW_ADDR_WIDTH = 32;
parameter    C_M_AXI_AW_DATA_WIDTH = 32;
parameter    C_M_AXI_AW_AWUSER_WIDTH = 1;
parameter    C_M_AXI_AW_ARUSER_WIDTH = 1;
parameter    C_M_AXI_AW_WUSER_WIDTH = 1;
parameter    C_M_AXI_AW_RUSER_WIDTH = 1;
parameter    C_M_AXI_AW_BUSER_WIDTH = 1;
parameter    C_M_AXI_AW_USER_VALUE = 0;
parameter    C_M_AXI_AW_PROT_VALUE = 0;
parameter    C_M_AXI_AW_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BI_ID_WIDTH = 1;
parameter    C_M_AXI_BI_ADDR_WIDTH = 32;
parameter    C_M_AXI_BI_DATA_WIDTH = 32;
parameter    C_M_AXI_BI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BI_WUSER_WIDTH = 1;
parameter    C_M_AXI_BI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BI_BUSER_WIDTH = 1;
parameter    C_M_AXI_BI_USER_VALUE = 0;
parameter    C_M_AXI_BI_PROT_VALUE = 0;
parameter    C_M_AXI_BI_CACHE_VALUE = 3;
parameter    C_M_AXI_CA_ID_WIDTH = 1;
parameter    C_M_AXI_CA_ADDR_WIDTH = 32;
parameter    C_M_AXI_CA_DATA_WIDTH = 32;
parameter    C_M_AXI_CA_AWUSER_WIDTH = 1;
parameter    C_M_AXI_CA_ARUSER_WIDTH = 1;
parameter    C_M_AXI_CA_WUSER_WIDTH = 1;
parameter    C_M_AXI_CA_RUSER_WIDTH = 1;
parameter    C_M_AXI_CA_BUSER_WIDTH = 1;
parameter    C_M_AXI_CA_USER_VALUE = 0;
parameter    C_M_AXI_CA_PROT_VALUE = 0;
parameter    C_M_AXI_CA_CACHE_VALUE = 3;

parameter C_S_AXI_AP_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_AW_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_CA_WSTRB_WIDTH = (32 / 8);

input   s_axi_ap_AWVALID;
output   s_axi_ap_AWREADY;
input  [C_S_AXI_AP_ADDR_WIDTH - 1:0] s_axi_ap_AWADDR;
input   s_axi_ap_WVALID;
output   s_axi_ap_WREADY;
input  [C_S_AXI_AP_DATA_WIDTH - 1:0] s_axi_ap_WDATA;
input  [C_S_AXI_AP_WSTRB_WIDTH - 1:0] s_axi_ap_WSTRB;
input   s_axi_ap_ARVALID;
output   s_axi_ap_ARREADY;
input  [C_S_AXI_AP_ADDR_WIDTH - 1:0] s_axi_ap_ARADDR;
output   s_axi_ap_RVALID;
input   s_axi_ap_RREADY;
output  [C_S_AXI_AP_DATA_WIDTH - 1:0] s_axi_ap_RDATA;
output  [1:0] s_axi_ap_RRESP;
output   s_axi_ap_BVALID;
input   s_axi_ap_BREADY;
output  [1:0] s_axi_ap_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   m_axi_aw_AWVALID;
input   m_axi_aw_AWREADY;
output  [C_M_AXI_AW_ADDR_WIDTH - 1:0] m_axi_aw_AWADDR;
output  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_AWID;
output  [7:0] m_axi_aw_AWLEN;
output  [2:0] m_axi_aw_AWSIZE;
output  [1:0] m_axi_aw_AWBURST;
output  [1:0] m_axi_aw_AWLOCK;
output  [3:0] m_axi_aw_AWCACHE;
output  [2:0] m_axi_aw_AWPROT;
output  [3:0] m_axi_aw_AWQOS;
output  [3:0] m_axi_aw_AWREGION;
output  [C_M_AXI_AW_AWUSER_WIDTH - 1:0] m_axi_aw_AWUSER;
output   m_axi_aw_WVALID;
input   m_axi_aw_WREADY;
output  [C_M_AXI_AW_DATA_WIDTH - 1:0] m_axi_aw_WDATA;
output  [C_M_AXI_AW_WSTRB_WIDTH - 1:0] m_axi_aw_WSTRB;
output   m_axi_aw_WLAST;
output  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_WID;
output  [C_M_AXI_AW_WUSER_WIDTH - 1:0] m_axi_aw_WUSER;
output   m_axi_aw_ARVALID;
input   m_axi_aw_ARREADY;
output  [C_M_AXI_AW_ADDR_WIDTH - 1:0] m_axi_aw_ARADDR;
output  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_ARID;
output  [7:0] m_axi_aw_ARLEN;
output  [2:0] m_axi_aw_ARSIZE;
output  [1:0] m_axi_aw_ARBURST;
output  [1:0] m_axi_aw_ARLOCK;
output  [3:0] m_axi_aw_ARCACHE;
output  [2:0] m_axi_aw_ARPROT;
output  [3:0] m_axi_aw_ARQOS;
output  [3:0] m_axi_aw_ARREGION;
output  [C_M_AXI_AW_ARUSER_WIDTH - 1:0] m_axi_aw_ARUSER;
input   m_axi_aw_RVALID;
output   m_axi_aw_RREADY;
input  [C_M_AXI_AW_DATA_WIDTH - 1:0] m_axi_aw_RDATA;
input   m_axi_aw_RLAST;
input  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_RID;
input  [C_M_AXI_AW_RUSER_WIDTH - 1:0] m_axi_aw_RUSER;
input  [1:0] m_axi_aw_RRESP;
input   m_axi_aw_BVALID;
output   m_axi_aw_BREADY;
input  [1:0] m_axi_aw_BRESP;
input  [C_M_AXI_AW_ID_WIDTH - 1:0] m_axi_aw_BID;
input  [C_M_AXI_AW_BUSER_WIDTH - 1:0] m_axi_aw_BUSER;
output   m_axi_bi_AWVALID;
input   m_axi_bi_AWREADY;
output  [C_M_AXI_BI_ADDR_WIDTH - 1:0] m_axi_bi_AWADDR;
output  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_AWID;
output  [7:0] m_axi_bi_AWLEN;
output  [2:0] m_axi_bi_AWSIZE;
output  [1:0] m_axi_bi_AWBURST;
output  [1:0] m_axi_bi_AWLOCK;
output  [3:0] m_axi_bi_AWCACHE;
output  [2:0] m_axi_bi_AWPROT;
output  [3:0] m_axi_bi_AWQOS;
output  [3:0] m_axi_bi_AWREGION;
output  [C_M_AXI_BI_AWUSER_WIDTH - 1:0] m_axi_bi_AWUSER;
output   m_axi_bi_WVALID;
input   m_axi_bi_WREADY;
output  [C_M_AXI_BI_DATA_WIDTH - 1:0] m_axi_bi_WDATA;
output  [C_M_AXI_BI_WSTRB_WIDTH - 1:0] m_axi_bi_WSTRB;
output   m_axi_bi_WLAST;
output  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_WID;
output  [C_M_AXI_BI_WUSER_WIDTH - 1:0] m_axi_bi_WUSER;
output   m_axi_bi_ARVALID;
input   m_axi_bi_ARREADY;
output  [C_M_AXI_BI_ADDR_WIDTH - 1:0] m_axi_bi_ARADDR;
output  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_ARID;
output  [7:0] m_axi_bi_ARLEN;
output  [2:0] m_axi_bi_ARSIZE;
output  [1:0] m_axi_bi_ARBURST;
output  [1:0] m_axi_bi_ARLOCK;
output  [3:0] m_axi_bi_ARCACHE;
output  [2:0] m_axi_bi_ARPROT;
output  [3:0] m_axi_bi_ARQOS;
output  [3:0] m_axi_bi_ARREGION;
output  [C_M_AXI_BI_ARUSER_WIDTH - 1:0] m_axi_bi_ARUSER;
input   m_axi_bi_RVALID;
output   m_axi_bi_RREADY;
input  [C_M_AXI_BI_DATA_WIDTH - 1:0] m_axi_bi_RDATA;
input   m_axi_bi_RLAST;
input  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_RID;
input  [C_M_AXI_BI_RUSER_WIDTH - 1:0] m_axi_bi_RUSER;
input  [1:0] m_axi_bi_RRESP;
input   m_axi_bi_BVALID;
output   m_axi_bi_BREADY;
input  [1:0] m_axi_bi_BRESP;
input  [C_M_AXI_BI_ID_WIDTH - 1:0] m_axi_bi_BID;
input  [C_M_AXI_BI_BUSER_WIDTH - 1:0] m_axi_bi_BUSER;
output   m_axi_ca_AWVALID;
input   m_axi_ca_AWREADY;
output  [C_M_AXI_CA_ADDR_WIDTH - 1:0] m_axi_ca_AWADDR;
output  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_AWID;
output  [7:0] m_axi_ca_AWLEN;
output  [2:0] m_axi_ca_AWSIZE;
output  [1:0] m_axi_ca_AWBURST;
output  [1:0] m_axi_ca_AWLOCK;
output  [3:0] m_axi_ca_AWCACHE;
output  [2:0] m_axi_ca_AWPROT;
output  [3:0] m_axi_ca_AWQOS;
output  [3:0] m_axi_ca_AWREGION;
output  [C_M_AXI_CA_AWUSER_WIDTH - 1:0] m_axi_ca_AWUSER;
output   m_axi_ca_WVALID;
input   m_axi_ca_WREADY;
output  [C_M_AXI_CA_DATA_WIDTH - 1:0] m_axi_ca_WDATA;
output  [C_M_AXI_CA_WSTRB_WIDTH - 1:0] m_axi_ca_WSTRB;
output   m_axi_ca_WLAST;
output  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_WID;
output  [C_M_AXI_CA_WUSER_WIDTH - 1:0] m_axi_ca_WUSER;
output   m_axi_ca_ARVALID;
input   m_axi_ca_ARREADY;
output  [C_M_AXI_CA_ADDR_WIDTH - 1:0] m_axi_ca_ARADDR;
output  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_ARID;
output  [7:0] m_axi_ca_ARLEN;
output  [2:0] m_axi_ca_ARSIZE;
output  [1:0] m_axi_ca_ARBURST;
output  [1:0] m_axi_ca_ARLOCK;
output  [3:0] m_axi_ca_ARCACHE;
output  [2:0] m_axi_ca_ARPROT;
output  [3:0] m_axi_ca_ARQOS;
output  [3:0] m_axi_ca_ARREGION;
output  [C_M_AXI_CA_ARUSER_WIDTH - 1:0] m_axi_ca_ARUSER;
input   m_axi_ca_RVALID;
output   m_axi_ca_RREADY;
input  [C_M_AXI_CA_DATA_WIDTH - 1:0] m_axi_ca_RDATA;
input   m_axi_ca_RLAST;
input  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_RID;
input  [C_M_AXI_CA_RUSER_WIDTH - 1:0] m_axi_ca_RUSER;
input  [1:0] m_axi_ca_RRESP;
input   m_axi_ca_BVALID;
output   m_axi_ca_BREADY;
input  [1:0] m_axi_ca_BRESP;
input  [C_M_AXI_CA_ID_WIDTH - 1:0] m_axi_ca_BID;
input  [C_M_AXI_CA_BUSER_WIDTH - 1:0] m_axi_ca_BUSER;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [7:0] ap_return;
wire   [15:0] a0_p;
wire   [15:0] b0_q;
wire   [15:0] m;
wire   [31:0] addr_a0;
wire   [31:0] addr_b0;
wire   [31:0] addr_c0;
wire    aw_AWREADY;
wire    aw_WREADY;
wire    aw_ARREADY;
wire    aw_RVALID;
wire   [7:0] aw_RDATA;
wire    aw_RLAST;
wire   [0:0] aw_RID;
wire   [9:0] aw_RFIFONUM;
wire   [0:0] aw_RUSER;
wire   [1:0] aw_RRESP;
wire    aw_BVALID;
wire    bi_AWREADY;
wire    bi_WREADY;
wire    bi_ARREADY;
wire    bi_RVALID;
wire   [7:0] bi_RDATA;
wire    bi_RLAST;
wire   [0:0] bi_RID;
wire   [9:0] bi_RFIFONUM;
wire   [0:0] bi_RUSER;
wire   [1:0] bi_RRESP;
wire    bi_BVALID;
wire    ca_AWREADY;
wire    ca_WREADY;
wire    ca_ARREADY;
wire    ca_RVALID;
wire   [31:0] ca_RDATA;
wire   [7:0] ca_RFIFONUM;
wire    ca_BVALID;
wire   [1:0] ca_BRESP;
wire   [0:0] ca_BID;
wire   [0:0] ca_BUSER;
wire    Block_entry44_proc_U0_ap_start;
wire    Block_entry44_proc_U0_ap_done;
wire    Block_entry44_proc_U0_ap_continue;
wire    Block_entry44_proc_U0_ap_idle;
wire    Block_entry44_proc_U0_ap_ready;
wire    Block_entry44_proc_U0_m_axi_aw_AWVALID;
wire   [31:0] Block_entry44_proc_U0_m_axi_aw_AWADDR;
wire   [0:0] Block_entry44_proc_U0_m_axi_aw_AWID;
wire   [31:0] Block_entry44_proc_U0_m_axi_aw_AWLEN;
wire   [2:0] Block_entry44_proc_U0_m_axi_aw_AWSIZE;
wire   [1:0] Block_entry44_proc_U0_m_axi_aw_AWBURST;
wire   [1:0] Block_entry44_proc_U0_m_axi_aw_AWLOCK;
wire   [3:0] Block_entry44_proc_U0_m_axi_aw_AWCACHE;
wire   [2:0] Block_entry44_proc_U0_m_axi_aw_AWPROT;
wire   [3:0] Block_entry44_proc_U0_m_axi_aw_AWQOS;
wire   [3:0] Block_entry44_proc_U0_m_axi_aw_AWREGION;
wire   [0:0] Block_entry44_proc_U0_m_axi_aw_AWUSER;
wire    Block_entry44_proc_U0_m_axi_aw_WVALID;
wire   [7:0] Block_entry44_proc_U0_m_axi_aw_WDATA;
wire   [0:0] Block_entry44_proc_U0_m_axi_aw_WSTRB;
wire    Block_entry44_proc_U0_m_axi_aw_WLAST;
wire   [0:0] Block_entry44_proc_U0_m_axi_aw_WID;
wire   [0:0] Block_entry44_proc_U0_m_axi_aw_WUSER;
wire    Block_entry44_proc_U0_m_axi_aw_ARVALID;
wire   [31:0] Block_entry44_proc_U0_m_axi_aw_ARADDR;
wire   [0:0] Block_entry44_proc_U0_m_axi_aw_ARID;
wire   [31:0] Block_entry44_proc_U0_m_axi_aw_ARLEN;
wire   [2:0] Block_entry44_proc_U0_m_axi_aw_ARSIZE;
wire   [1:0] Block_entry44_proc_U0_m_axi_aw_ARBURST;
wire   [1:0] Block_entry44_proc_U0_m_axi_aw_ARLOCK;
wire   [3:0] Block_entry44_proc_U0_m_axi_aw_ARCACHE;
wire   [2:0] Block_entry44_proc_U0_m_axi_aw_ARPROT;
wire   [3:0] Block_entry44_proc_U0_m_axi_aw_ARQOS;
wire   [3:0] Block_entry44_proc_U0_m_axi_aw_ARREGION;
wire   [0:0] Block_entry44_proc_U0_m_axi_aw_ARUSER;
wire    Block_entry44_proc_U0_m_axi_aw_RREADY;
wire    Block_entry44_proc_U0_m_axi_aw_BREADY;
wire    Block_entry44_proc_U0_m_axi_ca_AWVALID;
wire   [31:0] Block_entry44_proc_U0_m_axi_ca_AWADDR;
wire   [0:0] Block_entry44_proc_U0_m_axi_ca_AWID;
wire   [31:0] Block_entry44_proc_U0_m_axi_ca_AWLEN;
wire   [2:0] Block_entry44_proc_U0_m_axi_ca_AWSIZE;
wire   [1:0] Block_entry44_proc_U0_m_axi_ca_AWBURST;
wire   [1:0] Block_entry44_proc_U0_m_axi_ca_AWLOCK;
wire   [3:0] Block_entry44_proc_U0_m_axi_ca_AWCACHE;
wire   [2:0] Block_entry44_proc_U0_m_axi_ca_AWPROT;
wire   [3:0] Block_entry44_proc_U0_m_axi_ca_AWQOS;
wire   [3:0] Block_entry44_proc_U0_m_axi_ca_AWREGION;
wire   [0:0] Block_entry44_proc_U0_m_axi_ca_AWUSER;
wire    Block_entry44_proc_U0_m_axi_ca_WVALID;
wire   [31:0] Block_entry44_proc_U0_m_axi_ca_WDATA;
wire   [3:0] Block_entry44_proc_U0_m_axi_ca_WSTRB;
wire    Block_entry44_proc_U0_m_axi_ca_WLAST;
wire   [0:0] Block_entry44_proc_U0_m_axi_ca_WID;
wire   [0:0] Block_entry44_proc_U0_m_axi_ca_WUSER;
wire    Block_entry44_proc_U0_m_axi_ca_ARVALID;
wire   [31:0] Block_entry44_proc_U0_m_axi_ca_ARADDR;
wire   [0:0] Block_entry44_proc_U0_m_axi_ca_ARID;
wire   [31:0] Block_entry44_proc_U0_m_axi_ca_ARLEN;
wire   [2:0] Block_entry44_proc_U0_m_axi_ca_ARSIZE;
wire   [1:0] Block_entry44_proc_U0_m_axi_ca_ARBURST;
wire   [1:0] Block_entry44_proc_U0_m_axi_ca_ARLOCK;
wire   [3:0] Block_entry44_proc_U0_m_axi_ca_ARCACHE;
wire   [2:0] Block_entry44_proc_U0_m_axi_ca_ARPROT;
wire   [3:0] Block_entry44_proc_U0_m_axi_ca_ARQOS;
wire   [3:0] Block_entry44_proc_U0_m_axi_ca_ARREGION;
wire   [0:0] Block_entry44_proc_U0_m_axi_ca_ARUSER;
wire    Block_entry44_proc_U0_m_axi_ca_RREADY;
wire    Block_entry44_proc_U0_m_axi_ca_BREADY;
wire    Block_entry44_proc_U0_m_axi_bi_AWVALID;
wire   [31:0] Block_entry44_proc_U0_m_axi_bi_AWADDR;
wire   [0:0] Block_entry44_proc_U0_m_axi_bi_AWID;
wire   [31:0] Block_entry44_proc_U0_m_axi_bi_AWLEN;
wire   [2:0] Block_entry44_proc_U0_m_axi_bi_AWSIZE;
wire   [1:0] Block_entry44_proc_U0_m_axi_bi_AWBURST;
wire   [1:0] Block_entry44_proc_U0_m_axi_bi_AWLOCK;
wire   [3:0] Block_entry44_proc_U0_m_axi_bi_AWCACHE;
wire   [2:0] Block_entry44_proc_U0_m_axi_bi_AWPROT;
wire   [3:0] Block_entry44_proc_U0_m_axi_bi_AWQOS;
wire   [3:0] Block_entry44_proc_U0_m_axi_bi_AWREGION;
wire   [0:0] Block_entry44_proc_U0_m_axi_bi_AWUSER;
wire    Block_entry44_proc_U0_m_axi_bi_WVALID;
wire   [7:0] Block_entry44_proc_U0_m_axi_bi_WDATA;
wire   [0:0] Block_entry44_proc_U0_m_axi_bi_WSTRB;
wire    Block_entry44_proc_U0_m_axi_bi_WLAST;
wire   [0:0] Block_entry44_proc_U0_m_axi_bi_WID;
wire   [0:0] Block_entry44_proc_U0_m_axi_bi_WUSER;
wire    Block_entry44_proc_U0_m_axi_bi_ARVALID;
wire   [31:0] Block_entry44_proc_U0_m_axi_bi_ARADDR;
wire   [0:0] Block_entry44_proc_U0_m_axi_bi_ARID;
wire   [31:0] Block_entry44_proc_U0_m_axi_bi_ARLEN;
wire   [2:0] Block_entry44_proc_U0_m_axi_bi_ARSIZE;
wire   [1:0] Block_entry44_proc_U0_m_axi_bi_ARBURST;
wire   [1:0] Block_entry44_proc_U0_m_axi_bi_ARLOCK;
wire   [3:0] Block_entry44_proc_U0_m_axi_bi_ARCACHE;
wire   [2:0] Block_entry44_proc_U0_m_axi_bi_ARPROT;
wire   [3:0] Block_entry44_proc_U0_m_axi_bi_ARQOS;
wire   [3:0] Block_entry44_proc_U0_m_axi_bi_ARREGION;
wire   [0:0] Block_entry44_proc_U0_m_axi_bi_ARUSER;
wire    Block_entry44_proc_U0_m_axi_bi_RREADY;
wire    Block_entry44_proc_U0_m_axi_bi_BREADY;
wire   [1:0] Block_entry44_proc_U0_ap_return;
wire    ap_channel_done_retval_0_cast_loc_channel;
wire    retval_0_cast_loc_channel_full_n;
reg    ap_sync_reg_channel_write_retval_0_cast_loc_channel;
wire    ap_sync_channel_write_retval_0_cast_loc_channel;
wire    ap_sync_continue;
wire    Block_entry_proc_proc_U0_ap_start;
wire    Block_entry_proc_proc_U0_ap_done;
wire    Block_entry_proc_proc_U0_ap_continue;
wire    Block_entry_proc_proc_U0_ap_idle;
wire    Block_entry_proc_proc_U0_ap_ready;
wire   [1:0] Block_entry_proc_proc_U0_ap_return;
wire   [1:0] retval_0_cast_loc_channel_dout;
wire   [2:0] retval_0_cast_loc_channel_num_data_valid;
wire   [2:0] retval_0_cast_loc_channel_fifo_cap;
wire    retval_0_cast_loc_channel_empty_n;
wire    ap_sync_done;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_retval_0_cast_loc_channel = 1'b0;
end

shell_top_ap_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AP_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AP_DATA_WIDTH ))
ap_s_axi_U(
    .AWVALID(s_axi_ap_AWVALID),
    .AWREADY(s_axi_ap_AWREADY),
    .AWADDR(s_axi_ap_AWADDR),
    .WVALID(s_axi_ap_WVALID),
    .WREADY(s_axi_ap_WREADY),
    .WDATA(s_axi_ap_WDATA),
    .WSTRB(s_axi_ap_WSTRB),
    .ARVALID(s_axi_ap_ARVALID),
    .ARREADY(s_axi_ap_ARREADY),
    .ARADDR(s_axi_ap_ARADDR),
    .RVALID(s_axi_ap_RVALID),
    .RREADY(s_axi_ap_RREADY),
    .RDATA(s_axi_ap_RDATA),
    .RRESP(s_axi_ap_RRESP),
    .BVALID(s_axi_ap_BVALID),
    .BREADY(s_axi_ap_BREADY),
    .BRESP(s_axi_ap_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(ap_return),
    .a0_p(a0_p),
    .b0_q(b0_q),
    .m(m)
);

shell_top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .addr_a0(addr_a0),
    .addr_b0(addr_b0),
    .addr_c0(addr_c0)
);

shell_top_aw_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_AW_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_AW_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_AW_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_AW_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_AW_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_AW_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_AW_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_AW_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_AW_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_AW_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_AW_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 8 ),
    .NUM_WRITE_OUTSTANDING( 8 ))
aw_m_axi_U(
    .AWVALID(m_axi_aw_AWVALID),
    .AWREADY(m_axi_aw_AWREADY),
    .AWADDR(m_axi_aw_AWADDR),
    .AWID(m_axi_aw_AWID),
    .AWLEN(m_axi_aw_AWLEN),
    .AWSIZE(m_axi_aw_AWSIZE),
    .AWBURST(m_axi_aw_AWBURST),
    .AWLOCK(m_axi_aw_AWLOCK),
    .AWCACHE(m_axi_aw_AWCACHE),
    .AWPROT(m_axi_aw_AWPROT),
    .AWQOS(m_axi_aw_AWQOS),
    .AWREGION(m_axi_aw_AWREGION),
    .AWUSER(m_axi_aw_AWUSER),
    .WVALID(m_axi_aw_WVALID),
    .WREADY(m_axi_aw_WREADY),
    .WDATA(m_axi_aw_WDATA),
    .WSTRB(m_axi_aw_WSTRB),
    .WLAST(m_axi_aw_WLAST),
    .WID(m_axi_aw_WID),
    .WUSER(m_axi_aw_WUSER),
    .ARVALID(m_axi_aw_ARVALID),
    .ARREADY(m_axi_aw_ARREADY),
    .ARADDR(m_axi_aw_ARADDR),
    .ARID(m_axi_aw_ARID),
    .ARLEN(m_axi_aw_ARLEN),
    .ARSIZE(m_axi_aw_ARSIZE),
    .ARBURST(m_axi_aw_ARBURST),
    .ARLOCK(m_axi_aw_ARLOCK),
    .ARCACHE(m_axi_aw_ARCACHE),
    .ARPROT(m_axi_aw_ARPROT),
    .ARQOS(m_axi_aw_ARQOS),
    .ARREGION(m_axi_aw_ARREGION),
    .ARUSER(m_axi_aw_ARUSER),
    .RVALID(m_axi_aw_RVALID),
    .RREADY(m_axi_aw_RREADY),
    .RDATA(m_axi_aw_RDATA),
    .RLAST(m_axi_aw_RLAST),
    .RID(m_axi_aw_RID),
    .RUSER(m_axi_aw_RUSER),
    .RRESP(m_axi_aw_RRESP),
    .BVALID(m_axi_aw_BVALID),
    .BREADY(m_axi_aw_BREADY),
    .BRESP(m_axi_aw_BRESP),
    .BID(m_axi_aw_BID),
    .BUSER(m_axi_aw_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Block_entry44_proc_U0_m_axi_aw_ARVALID),
    .I_ARREADY(aw_ARREADY),
    .I_ARADDR(Block_entry44_proc_U0_m_axi_aw_ARADDR),
    .I_ARLEN(Block_entry44_proc_U0_m_axi_aw_ARLEN),
    .I_RVALID(aw_RVALID),
    .I_RREADY(Block_entry44_proc_U0_m_axi_aw_RREADY),
    .I_RDATA(aw_RDATA),
    .I_RFIFONUM(aw_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(aw_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(aw_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(aw_BVALID),
    .I_BREADY(1'b0)
);

shell_top_bi_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BI_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BI_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BI_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BI_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BI_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BI_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BI_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BI_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BI_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BI_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BI_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 8 ),
    .NUM_WRITE_OUTSTANDING( 8 ))
bi_m_axi_U(
    .AWVALID(m_axi_bi_AWVALID),
    .AWREADY(m_axi_bi_AWREADY),
    .AWADDR(m_axi_bi_AWADDR),
    .AWID(m_axi_bi_AWID),
    .AWLEN(m_axi_bi_AWLEN),
    .AWSIZE(m_axi_bi_AWSIZE),
    .AWBURST(m_axi_bi_AWBURST),
    .AWLOCK(m_axi_bi_AWLOCK),
    .AWCACHE(m_axi_bi_AWCACHE),
    .AWPROT(m_axi_bi_AWPROT),
    .AWQOS(m_axi_bi_AWQOS),
    .AWREGION(m_axi_bi_AWREGION),
    .AWUSER(m_axi_bi_AWUSER),
    .WVALID(m_axi_bi_WVALID),
    .WREADY(m_axi_bi_WREADY),
    .WDATA(m_axi_bi_WDATA),
    .WSTRB(m_axi_bi_WSTRB),
    .WLAST(m_axi_bi_WLAST),
    .WID(m_axi_bi_WID),
    .WUSER(m_axi_bi_WUSER),
    .ARVALID(m_axi_bi_ARVALID),
    .ARREADY(m_axi_bi_ARREADY),
    .ARADDR(m_axi_bi_ARADDR),
    .ARID(m_axi_bi_ARID),
    .ARLEN(m_axi_bi_ARLEN),
    .ARSIZE(m_axi_bi_ARSIZE),
    .ARBURST(m_axi_bi_ARBURST),
    .ARLOCK(m_axi_bi_ARLOCK),
    .ARCACHE(m_axi_bi_ARCACHE),
    .ARPROT(m_axi_bi_ARPROT),
    .ARQOS(m_axi_bi_ARQOS),
    .ARREGION(m_axi_bi_ARREGION),
    .ARUSER(m_axi_bi_ARUSER),
    .RVALID(m_axi_bi_RVALID),
    .RREADY(m_axi_bi_RREADY),
    .RDATA(m_axi_bi_RDATA),
    .RLAST(m_axi_bi_RLAST),
    .RID(m_axi_bi_RID),
    .RUSER(m_axi_bi_RUSER),
    .RRESP(m_axi_bi_RRESP),
    .BVALID(m_axi_bi_BVALID),
    .BREADY(m_axi_bi_BREADY),
    .BRESP(m_axi_bi_BRESP),
    .BID(m_axi_bi_BID),
    .BUSER(m_axi_bi_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Block_entry44_proc_U0_m_axi_bi_ARVALID),
    .I_ARREADY(bi_ARREADY),
    .I_ARADDR(Block_entry44_proc_U0_m_axi_bi_ARADDR),
    .I_ARLEN(Block_entry44_proc_U0_m_axi_bi_ARLEN),
    .I_RVALID(bi_RVALID),
    .I_RREADY(Block_entry44_proc_U0_m_axi_bi_RREADY),
    .I_RDATA(bi_RDATA),
    .I_RFIFONUM(bi_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(bi_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(bi_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(bi_BVALID),
    .I_BREADY(1'b0)
);

shell_top_ca_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_CA_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_CA_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_CA_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_CA_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_CA_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_CA_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_CA_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_CA_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_CA_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_CA_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_CA_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 8 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 8 ),
    .NUM_WRITE_OUTSTANDING( 8 ))
ca_m_axi_U(
    .AWVALID(m_axi_ca_AWVALID),
    .AWREADY(m_axi_ca_AWREADY),
    .AWADDR(m_axi_ca_AWADDR),
    .AWID(m_axi_ca_AWID),
    .AWLEN(m_axi_ca_AWLEN),
    .AWSIZE(m_axi_ca_AWSIZE),
    .AWBURST(m_axi_ca_AWBURST),
    .AWLOCK(m_axi_ca_AWLOCK),
    .AWCACHE(m_axi_ca_AWCACHE),
    .AWPROT(m_axi_ca_AWPROT),
    .AWQOS(m_axi_ca_AWQOS),
    .AWREGION(m_axi_ca_AWREGION),
    .AWUSER(m_axi_ca_AWUSER),
    .WVALID(m_axi_ca_WVALID),
    .WREADY(m_axi_ca_WREADY),
    .WDATA(m_axi_ca_WDATA),
    .WSTRB(m_axi_ca_WSTRB),
    .WLAST(m_axi_ca_WLAST),
    .WID(m_axi_ca_WID),
    .WUSER(m_axi_ca_WUSER),
    .ARVALID(m_axi_ca_ARVALID),
    .ARREADY(m_axi_ca_ARREADY),
    .ARADDR(m_axi_ca_ARADDR),
    .ARID(m_axi_ca_ARID),
    .ARLEN(m_axi_ca_ARLEN),
    .ARSIZE(m_axi_ca_ARSIZE),
    .ARBURST(m_axi_ca_ARBURST),
    .ARLOCK(m_axi_ca_ARLOCK),
    .ARCACHE(m_axi_ca_ARCACHE),
    .ARPROT(m_axi_ca_ARPROT),
    .ARQOS(m_axi_ca_ARQOS),
    .ARREGION(m_axi_ca_ARREGION),
    .ARUSER(m_axi_ca_ARUSER),
    .RVALID(m_axi_ca_RVALID),
    .RREADY(m_axi_ca_RREADY),
    .RDATA(m_axi_ca_RDATA),
    .RLAST(m_axi_ca_RLAST),
    .RID(m_axi_ca_RID),
    .RUSER(m_axi_ca_RUSER),
    .RRESP(m_axi_ca_RRESP),
    .BVALID(m_axi_ca_BVALID),
    .BREADY(m_axi_ca_BREADY),
    .BRESP(m_axi_ca_BRESP),
    .BID(m_axi_ca_BID),
    .BUSER(m_axi_ca_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(ca_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(ca_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(ca_RDATA),
    .I_RFIFONUM(ca_RFIFONUM),
    .I_AWVALID(Block_entry44_proc_U0_m_axi_ca_AWVALID),
    .I_AWREADY(ca_AWREADY),
    .I_AWADDR(Block_entry44_proc_U0_m_axi_ca_AWADDR),
    .I_AWLEN(Block_entry44_proc_U0_m_axi_ca_AWLEN),
    .I_WVALID(Block_entry44_proc_U0_m_axi_ca_WVALID),
    .I_WREADY(ca_WREADY),
    .I_WDATA(Block_entry44_proc_U0_m_axi_ca_WDATA),
    .I_WSTRB(Block_entry44_proc_U0_m_axi_ca_WSTRB),
    .I_BVALID(ca_BVALID),
    .I_BREADY(Block_entry44_proc_U0_m_axi_ca_BREADY)
);

shell_top_Block_entry44_proc Block_entry44_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry44_proc_U0_ap_start),
    .ap_done(Block_entry44_proc_U0_ap_done),
    .ap_continue(Block_entry44_proc_U0_ap_continue),
    .ap_idle(Block_entry44_proc_U0_ap_idle),
    .ap_ready(Block_entry44_proc_U0_ap_ready),
    .a0_p(a0_p),
    .b0_q(b0_q),
    .m(m),
    .addr_c0(addr_c0),
    .addr_a0(addr_a0),
    .m_axi_aw_AWVALID(Block_entry44_proc_U0_m_axi_aw_AWVALID),
    .m_axi_aw_AWREADY(1'b0),
    .m_axi_aw_AWADDR(Block_entry44_proc_U0_m_axi_aw_AWADDR),
    .m_axi_aw_AWID(Block_entry44_proc_U0_m_axi_aw_AWID),
    .m_axi_aw_AWLEN(Block_entry44_proc_U0_m_axi_aw_AWLEN),
    .m_axi_aw_AWSIZE(Block_entry44_proc_U0_m_axi_aw_AWSIZE),
    .m_axi_aw_AWBURST(Block_entry44_proc_U0_m_axi_aw_AWBURST),
    .m_axi_aw_AWLOCK(Block_entry44_proc_U0_m_axi_aw_AWLOCK),
    .m_axi_aw_AWCACHE(Block_entry44_proc_U0_m_axi_aw_AWCACHE),
    .m_axi_aw_AWPROT(Block_entry44_proc_U0_m_axi_aw_AWPROT),
    .m_axi_aw_AWQOS(Block_entry44_proc_U0_m_axi_aw_AWQOS),
    .m_axi_aw_AWREGION(Block_entry44_proc_U0_m_axi_aw_AWREGION),
    .m_axi_aw_AWUSER(Block_entry44_proc_U0_m_axi_aw_AWUSER),
    .m_axi_aw_WVALID(Block_entry44_proc_U0_m_axi_aw_WVALID),
    .m_axi_aw_WREADY(1'b0),
    .m_axi_aw_WDATA(Block_entry44_proc_U0_m_axi_aw_WDATA),
    .m_axi_aw_WSTRB(Block_entry44_proc_U0_m_axi_aw_WSTRB),
    .m_axi_aw_WLAST(Block_entry44_proc_U0_m_axi_aw_WLAST),
    .m_axi_aw_WID(Block_entry44_proc_U0_m_axi_aw_WID),
    .m_axi_aw_WUSER(Block_entry44_proc_U0_m_axi_aw_WUSER),
    .m_axi_aw_ARVALID(Block_entry44_proc_U0_m_axi_aw_ARVALID),
    .m_axi_aw_ARREADY(aw_ARREADY),
    .m_axi_aw_ARADDR(Block_entry44_proc_U0_m_axi_aw_ARADDR),
    .m_axi_aw_ARID(Block_entry44_proc_U0_m_axi_aw_ARID),
    .m_axi_aw_ARLEN(Block_entry44_proc_U0_m_axi_aw_ARLEN),
    .m_axi_aw_ARSIZE(Block_entry44_proc_U0_m_axi_aw_ARSIZE),
    .m_axi_aw_ARBURST(Block_entry44_proc_U0_m_axi_aw_ARBURST),
    .m_axi_aw_ARLOCK(Block_entry44_proc_U0_m_axi_aw_ARLOCK),
    .m_axi_aw_ARCACHE(Block_entry44_proc_U0_m_axi_aw_ARCACHE),
    .m_axi_aw_ARPROT(Block_entry44_proc_U0_m_axi_aw_ARPROT),
    .m_axi_aw_ARQOS(Block_entry44_proc_U0_m_axi_aw_ARQOS),
    .m_axi_aw_ARREGION(Block_entry44_proc_U0_m_axi_aw_ARREGION),
    .m_axi_aw_ARUSER(Block_entry44_proc_U0_m_axi_aw_ARUSER),
    .m_axi_aw_RVALID(aw_RVALID),
    .m_axi_aw_RREADY(Block_entry44_proc_U0_m_axi_aw_RREADY),
    .m_axi_aw_RDATA(aw_RDATA),
    .m_axi_aw_RLAST(aw_RLAST),
    .m_axi_aw_RID(aw_RID),
    .m_axi_aw_RFIFONUM(aw_RFIFONUM),
    .m_axi_aw_RUSER(aw_RUSER),
    .m_axi_aw_RRESP(aw_RRESP),
    .m_axi_aw_BVALID(1'b0),
    .m_axi_aw_BREADY(Block_entry44_proc_U0_m_axi_aw_BREADY),
    .m_axi_aw_BRESP(2'd0),
    .m_axi_aw_BID(1'd0),
    .m_axi_aw_BUSER(1'd0),
    .m_axi_ca_AWVALID(Block_entry44_proc_U0_m_axi_ca_AWVALID),
    .m_axi_ca_AWREADY(ca_AWREADY),
    .m_axi_ca_AWADDR(Block_entry44_proc_U0_m_axi_ca_AWADDR),
    .m_axi_ca_AWID(Block_entry44_proc_U0_m_axi_ca_AWID),
    .m_axi_ca_AWLEN(Block_entry44_proc_U0_m_axi_ca_AWLEN),
    .m_axi_ca_AWSIZE(Block_entry44_proc_U0_m_axi_ca_AWSIZE),
    .m_axi_ca_AWBURST(Block_entry44_proc_U0_m_axi_ca_AWBURST),
    .m_axi_ca_AWLOCK(Block_entry44_proc_U0_m_axi_ca_AWLOCK),
    .m_axi_ca_AWCACHE(Block_entry44_proc_U0_m_axi_ca_AWCACHE),
    .m_axi_ca_AWPROT(Block_entry44_proc_U0_m_axi_ca_AWPROT),
    .m_axi_ca_AWQOS(Block_entry44_proc_U0_m_axi_ca_AWQOS),
    .m_axi_ca_AWREGION(Block_entry44_proc_U0_m_axi_ca_AWREGION),
    .m_axi_ca_AWUSER(Block_entry44_proc_U0_m_axi_ca_AWUSER),
    .m_axi_ca_WVALID(Block_entry44_proc_U0_m_axi_ca_WVALID),
    .m_axi_ca_WREADY(ca_WREADY),
    .m_axi_ca_WDATA(Block_entry44_proc_U0_m_axi_ca_WDATA),
    .m_axi_ca_WSTRB(Block_entry44_proc_U0_m_axi_ca_WSTRB),
    .m_axi_ca_WLAST(Block_entry44_proc_U0_m_axi_ca_WLAST),
    .m_axi_ca_WID(Block_entry44_proc_U0_m_axi_ca_WID),
    .m_axi_ca_WUSER(Block_entry44_proc_U0_m_axi_ca_WUSER),
    .m_axi_ca_ARVALID(Block_entry44_proc_U0_m_axi_ca_ARVALID),
    .m_axi_ca_ARREADY(1'b0),
    .m_axi_ca_ARADDR(Block_entry44_proc_U0_m_axi_ca_ARADDR),
    .m_axi_ca_ARID(Block_entry44_proc_U0_m_axi_ca_ARID),
    .m_axi_ca_ARLEN(Block_entry44_proc_U0_m_axi_ca_ARLEN),
    .m_axi_ca_ARSIZE(Block_entry44_proc_U0_m_axi_ca_ARSIZE),
    .m_axi_ca_ARBURST(Block_entry44_proc_U0_m_axi_ca_ARBURST),
    .m_axi_ca_ARLOCK(Block_entry44_proc_U0_m_axi_ca_ARLOCK),
    .m_axi_ca_ARCACHE(Block_entry44_proc_U0_m_axi_ca_ARCACHE),
    .m_axi_ca_ARPROT(Block_entry44_proc_U0_m_axi_ca_ARPROT),
    .m_axi_ca_ARQOS(Block_entry44_proc_U0_m_axi_ca_ARQOS),
    .m_axi_ca_ARREGION(Block_entry44_proc_U0_m_axi_ca_ARREGION),
    .m_axi_ca_ARUSER(Block_entry44_proc_U0_m_axi_ca_ARUSER),
    .m_axi_ca_RVALID(1'b0),
    .m_axi_ca_RREADY(Block_entry44_proc_U0_m_axi_ca_RREADY),
    .m_axi_ca_RDATA(32'd0),
    .m_axi_ca_RLAST(1'b0),
    .m_axi_ca_RID(1'd0),
    .m_axi_ca_RFIFONUM(8'd0),
    .m_axi_ca_RUSER(1'd0),
    .m_axi_ca_RRESP(2'd0),
    .m_axi_ca_BVALID(ca_BVALID),
    .m_axi_ca_BREADY(Block_entry44_proc_U0_m_axi_ca_BREADY),
    .m_axi_ca_BRESP(ca_BRESP),
    .m_axi_ca_BID(ca_BID),
    .m_axi_ca_BUSER(ca_BUSER),
    .addr_b0(addr_b0),
    .m_axi_bi_AWVALID(Block_entry44_proc_U0_m_axi_bi_AWVALID),
    .m_axi_bi_AWREADY(1'b0),
    .m_axi_bi_AWADDR(Block_entry44_proc_U0_m_axi_bi_AWADDR),
    .m_axi_bi_AWID(Block_entry44_proc_U0_m_axi_bi_AWID),
    .m_axi_bi_AWLEN(Block_entry44_proc_U0_m_axi_bi_AWLEN),
    .m_axi_bi_AWSIZE(Block_entry44_proc_U0_m_axi_bi_AWSIZE),
    .m_axi_bi_AWBURST(Block_entry44_proc_U0_m_axi_bi_AWBURST),
    .m_axi_bi_AWLOCK(Block_entry44_proc_U0_m_axi_bi_AWLOCK),
    .m_axi_bi_AWCACHE(Block_entry44_proc_U0_m_axi_bi_AWCACHE),
    .m_axi_bi_AWPROT(Block_entry44_proc_U0_m_axi_bi_AWPROT),
    .m_axi_bi_AWQOS(Block_entry44_proc_U0_m_axi_bi_AWQOS),
    .m_axi_bi_AWREGION(Block_entry44_proc_U0_m_axi_bi_AWREGION),
    .m_axi_bi_AWUSER(Block_entry44_proc_U0_m_axi_bi_AWUSER),
    .m_axi_bi_WVALID(Block_entry44_proc_U0_m_axi_bi_WVALID),
    .m_axi_bi_WREADY(1'b0),
    .m_axi_bi_WDATA(Block_entry44_proc_U0_m_axi_bi_WDATA),
    .m_axi_bi_WSTRB(Block_entry44_proc_U0_m_axi_bi_WSTRB),
    .m_axi_bi_WLAST(Block_entry44_proc_U0_m_axi_bi_WLAST),
    .m_axi_bi_WID(Block_entry44_proc_U0_m_axi_bi_WID),
    .m_axi_bi_WUSER(Block_entry44_proc_U0_m_axi_bi_WUSER),
    .m_axi_bi_ARVALID(Block_entry44_proc_U0_m_axi_bi_ARVALID),
    .m_axi_bi_ARREADY(bi_ARREADY),
    .m_axi_bi_ARADDR(Block_entry44_proc_U0_m_axi_bi_ARADDR),
    .m_axi_bi_ARID(Block_entry44_proc_U0_m_axi_bi_ARID),
    .m_axi_bi_ARLEN(Block_entry44_proc_U0_m_axi_bi_ARLEN),
    .m_axi_bi_ARSIZE(Block_entry44_proc_U0_m_axi_bi_ARSIZE),
    .m_axi_bi_ARBURST(Block_entry44_proc_U0_m_axi_bi_ARBURST),
    .m_axi_bi_ARLOCK(Block_entry44_proc_U0_m_axi_bi_ARLOCK),
    .m_axi_bi_ARCACHE(Block_entry44_proc_U0_m_axi_bi_ARCACHE),
    .m_axi_bi_ARPROT(Block_entry44_proc_U0_m_axi_bi_ARPROT),
    .m_axi_bi_ARQOS(Block_entry44_proc_U0_m_axi_bi_ARQOS),
    .m_axi_bi_ARREGION(Block_entry44_proc_U0_m_axi_bi_ARREGION),
    .m_axi_bi_ARUSER(Block_entry44_proc_U0_m_axi_bi_ARUSER),
    .m_axi_bi_RVALID(bi_RVALID),
    .m_axi_bi_RREADY(Block_entry44_proc_U0_m_axi_bi_RREADY),
    .m_axi_bi_RDATA(bi_RDATA),
    .m_axi_bi_RLAST(bi_RLAST),
    .m_axi_bi_RID(bi_RID),
    .m_axi_bi_RFIFONUM(bi_RFIFONUM),
    .m_axi_bi_RUSER(bi_RUSER),
    .m_axi_bi_RRESP(bi_RRESP),
    .m_axi_bi_BVALID(1'b0),
    .m_axi_bi_BREADY(Block_entry44_proc_U0_m_axi_bi_BREADY),
    .m_axi_bi_BRESP(2'd0),
    .m_axi_bi_BID(1'd0),
    .m_axi_bi_BUSER(1'd0),
    .ap_return(Block_entry44_proc_U0_ap_return)
);

shell_top_Block_entry_proc_proc Block_entry_proc_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry_proc_proc_U0_ap_start),
    .ap_done(Block_entry_proc_proc_U0_ap_done),
    .ap_continue(Block_entry_proc_proc_U0_ap_continue),
    .ap_idle(Block_entry_proc_proc_U0_ap_idle),
    .ap_ready(Block_entry_proc_proc_U0_ap_ready),
    .p_read(retval_0_cast_loc_channel_dout),
    .ap_return(Block_entry_proc_proc_U0_ap_return)
);

shell_top_fifo_w2_d2_S retval_0_cast_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry44_proc_U0_ap_return),
    .if_full_n(retval_0_cast_loc_channel_full_n),
    .if_write(ap_channel_done_retval_0_cast_loc_channel),
    .if_dout(retval_0_cast_loc_channel_dout),
    .if_num_data_valid(retval_0_cast_loc_channel_num_data_valid),
    .if_fifo_cap(retval_0_cast_loc_channel_fifo_cap),
    .if_empty_n(retval_0_cast_loc_channel_empty_n),
    .if_read(Block_entry_proc_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_retval_0_cast_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry44_proc_U0_ap_done & Block_entry44_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_retval_0_cast_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_retval_0_cast_loc_channel <= ap_sync_channel_write_retval_0_cast_loc_channel;
        end
    end
end

assign Block_entry44_proc_U0_ap_continue = (ap_sync_continue & ap_sync_channel_write_retval_0_cast_loc_channel);

assign Block_entry44_proc_U0_ap_start = ap_start;

assign Block_entry_proc_proc_U0_ap_continue = ap_sync_done;

assign Block_entry_proc_proc_U0_ap_start = retval_0_cast_loc_channel_empty_n;

assign ap_channel_done_retval_0_cast_loc_channel = ((ap_sync_reg_channel_write_retval_0_cast_loc_channel ^ 1'b1) & Block_entry44_proc_U0_ap_done);

assign ap_done = ap_sync_done;

assign ap_idle = ((retval_0_cast_loc_channel_empty_n ^ 1'b1) & Block_entry_proc_proc_U0_ap_idle & Block_entry44_proc_U0_ap_idle);

assign ap_ready = Block_entry44_proc_U0_ap_ready;

assign ap_return = Block_entry_proc_proc_U0_ap_return;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_retval_0_cast_loc_channel = ((retval_0_cast_loc_channel_full_n & ap_channel_done_retval_0_cast_loc_channel) | ap_sync_reg_channel_write_retval_0_cast_loc_channel);

assign ap_sync_continue = ap_sync_done;

assign ap_sync_done = (Block_entry_proc_proc_U0_ap_done & Block_entry44_proc_U0_ap_done);

assign aw_RID = 1'd0;

assign aw_RLAST = 1'b0;

assign aw_RRESP = 2'd0;

assign aw_RUSER = 1'd0;

assign bi_RID = 1'd0;

assign bi_RLAST = 1'b0;

assign bi_RRESP = 2'd0;

assign bi_RUSER = 1'd0;

assign ca_BID = 1'd0;

assign ca_BRESP = 2'd0;

assign ca_BUSER = 1'd0;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "shell_top_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //shell_top

