# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrs.xdc

# XDC: new/no_scrub.xdc

# Block Designs: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/bd_8x8_bram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram || ORIG_REF_NAME==bd_8x8_bram} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_processing_system7_0_0/bd_8x8_bram_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_processing_system7_0_0 || ORIG_REF_NAME==bd_8x8_bram_processing_system7_0_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_0/bd_8x8_bram_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_xbar_0 || ORIG_REF_NAME==bd_8x8_bram_xbar_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_axi_interconnect_0_0/bd_8x8_bram_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_axi_interconnect_0_0 || ORIG_REF_NAME==bd_8x8_bram_axi_interconnect_0_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_1/bd_8x8_bram_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_xbar_1 || ORIG_REF_NAME==bd_8x8_bram_xbar_1} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_axi_interconnect_0_1/bd_8x8_bram_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_axi_interconnect_0_1 || ORIG_REF_NAME==bd_8x8_bram_axi_interconnect_0_1} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_2/bd_8x8_bram_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_xbar_2 || ORIG_REF_NAME==bd_8x8_bram_xbar_2} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_axi_interconnect_1_0/bd_8x8_bram_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_axi_interconnect_1_0 || ORIG_REF_NAME==bd_8x8_bram_axi_interconnect_1_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_axi_bram_ctrl_0_0/bd_8x8_bram_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==bd_8x8_bram_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_axi_bram_ctrl_0_1/bd_8x8_bram_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_axi_bram_ctrl_0_1 || ORIG_REF_NAME==bd_8x8_bram_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_axi_bram_ctrl_0_2/bd_8x8_bram_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_axi_bram_ctrl_0_2 || ORIG_REF_NAME==bd_8x8_bram_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_blk_mem_gen_0_0/bd_8x8_bram_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_blk_mem_gen_0_0 || ORIG_REF_NAME==bd_8x8_bram_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_blk_mem_gen_0_1/bd_8x8_bram_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_blk_mem_gen_0_1 || ORIG_REF_NAME==bd_8x8_bram_blk_mem_gen_0_1} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_blk_mem_gen_0_2/bd_8x8_bram_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_blk_mem_gen_0_2 || ORIG_REF_NAME==bd_8x8_bram_blk_mem_gen_0_2} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_rst_ps7_0_100M_0/bd_8x8_bram_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_rst_ps7_0_100M_0 || ORIG_REF_NAME==bd_8x8_bram_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_xbar_3/bd_8x8_bram_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_xbar_3 || ORIG_REF_NAME==bd_8x8_bram_xbar_3} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_auto_pc_2/bd_8x8_bram_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_auto_pc_2 || ORIG_REF_NAME==bd_8x8_bram_auto_pc_2} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_auto_pc_0/bd_8x8_bram_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_auto_pc_0 || ORIG_REF_NAME==bd_8x8_bram_auto_pc_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_auto_pc_1/bd_8x8_bram_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_auto_pc_1 || ORIG_REF_NAME==bd_8x8_bram_auto_pc_1} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_ps7_0_axi_periph_0/bd_8x8_bram_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_8x8_bram_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.srcs/sources_1/bd/bd_8x8_bram/ip/bd_8x8_bram_mxm_execute_ursa_0_6/bd_8x8_bram_mxm_execute_ursa_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8x8_bram_mxm_execute_ursa_0_6 || ORIG_REF_NAME==bd_8x8_bram_mxm_execute_ursa_0_6} -quiet] -quiet

# XDC: /home/ulisses/Projects/nn-apsoc-sa/exp_studies/ulisses/ursa/vivado/ursa.gen/sources_1/bd/bd_8x8_bram/bd_8x8_bram_ooc.xdc
