domain_path: /home/ulisses/Projects/ursa/vitis/platform_vanilla/export/platform_vanilla/sw/standalone_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
