-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mxm_execute_ursa_sa_reset is
port (
    ap_ready : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_15 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_15_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_14 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_14_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_13 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_13_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_12 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_12_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_11 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_11_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_10 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_10_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_9 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_9_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_8 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_8_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_7 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_7_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_6 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_6_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_5 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_5_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_4 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_4_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_3 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_3_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_2 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_2_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_1_ap_vld : OUT STD_LOGIC;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s : OUT STD_LOGIC_VECTOR (19 downto 0);
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mxm_execute_ursa_sa_reset is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;


begin



    ap_ready <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_1 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_10 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_10_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_11 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_11_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_12 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_12_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_13 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_13_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_14 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_14_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_15 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_15_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_1_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_2 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_2_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_3 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_3_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_4 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_4_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_5 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_5_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_6 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_6_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_7 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_7_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_8 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_8_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_9 <= ap_const_lv20_0;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_9_ap_vld <= ap_const_logic_1;
    mxm_execute_ursa_ap_uint_unsigned_short_ap_uint_unsigned_short_int_unsigned_s_ap_vld <= ap_const_logic_1;
end behav;
