domain_path: /home/ulisses/Projects/ursa/exp/output-stationary/vitis/platform-ursa-vanilla-bram/export/platform-ursa-vanilla-bram/sw/standalone_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
