// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2023.2 (lin64) Build 4029153 Fri Oct 13 20:13:54 MDT 2023
// Date        : Sun May 11 11:41:12 2025
// Host        : ulisses-thinkpad running 64-bit Ubuntu 22.04.5 LTS
// Command     : write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
//               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_bram_tmr_tmr_voter_2_1_stub.v
// Design      : bd_bram_tmr_tmr_voter_2_1
// Purpose     : Stub declaration of top-level module interface
// Device      : xc7z020clg484-1
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* x_core_info = "tmr_voter,Vivado 2023.2" *)
module decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix(Clk, S_AXI1_AWID, S_AXI1_AWADDR, S_AXI1_AWLEN, 
  S_AXI1_AWSIZE, S_AXI1_AWBURST, S_AXI1_AWLOCK, S_AXI1_AWCACHE, S_AXI1_AWPROT, S_AXI1_AWQOS, 
  S_AXI1_AWVALID, S_AXI1_AWREADY, S_AXI1_WDATA, S_AXI1_WSTRB, S_AXI1_WLAST, S_AXI1_WVALID, 
  S_AXI1_WREADY, S_AXI1_BID, S_AXI1_BRESP, S_AXI1_BVALID, S_AXI1_BREADY, S_AXI1_ARID, 
  S_AXI1_ARADDR, S_AXI1_ARLEN, S_AXI1_ARSIZE, S_AXI1_ARBURST, S_AXI1_ARLOCK, S_AXI1_ARCACHE, 
  S_AXI1_ARPROT, S_AXI1_ARQOS, S_AXI1_ARVALID, S_AXI1_ARREADY, S_AXI1_RID, S_AXI1_RDATA, 
  S_AXI1_RRESP, S_AXI1_RLAST, S_AXI1_RVALID, S_AXI1_RREADY, S_AXI2_AWID, S_AXI2_AWADDR, 
  S_AXI2_AWLEN, S_AXI2_AWSIZE, S_AXI2_AWBURST, S_AXI2_AWLOCK, S_AXI2_AWCACHE, S_AXI2_AWPROT, 
  S_AXI2_AWQOS, S_AXI2_AWVALID, S_AXI2_AWREADY, S_AXI2_WDATA, S_AXI2_WSTRB, S_AXI2_WLAST, 
  S_AXI2_WVALID, S_AXI2_WREADY, S_AXI2_BID, S_AXI2_BRESP, S_AXI2_BVALID, S_AXI2_BREADY, 
  S_AXI2_ARID, S_AXI2_ARADDR, S_AXI2_ARLEN, S_AXI2_ARSIZE, S_AXI2_ARBURST, S_AXI2_ARLOCK, 
  S_AXI2_ARCACHE, S_AXI2_ARPROT, S_AXI2_ARQOS, S_AXI2_ARVALID, S_AXI2_ARREADY, S_AXI2_RID, 
  S_AXI2_RDATA, S_AXI2_RRESP, S_AXI2_RLAST, S_AXI2_RVALID, S_AXI2_RREADY, S_AXI3_AWID, 
  S_AXI3_AWADDR, S_AXI3_AWLEN, S_AXI3_AWSIZE, S_AXI3_AWBURST, S_AXI3_AWLOCK, S_AXI3_AWCACHE, 
  S_AXI3_AWPROT, S_AXI3_AWQOS, S_AXI3_AWVALID, S_AXI3_AWREADY, S_AXI3_WDATA, S_AXI3_WSTRB, 
  S_AXI3_WLAST, S_AXI3_WVALID, S_AXI3_WREADY, S_AXI3_BID, S_AXI3_BRESP, S_AXI3_BVALID, 
  S_AXI3_BREADY, S_AXI3_ARID, S_AXI3_ARADDR, S_AXI3_ARLEN, S_AXI3_ARSIZE, S_AXI3_ARBURST, 
  S_AXI3_ARLOCK, S_AXI3_ARCACHE, S_AXI3_ARPROT, S_AXI3_ARQOS, S_AXI3_ARVALID, S_AXI3_ARREADY, 
  S_AXI3_RID, S_AXI3_RDATA, S_AXI3_RRESP, S_AXI3_RLAST, S_AXI3_RVALID, S_AXI3_RREADY, 
  M_AXI_AWID, M_AXI_AWADDR, M_AXI_AWLEN, M_AXI_AWSIZE, M_AXI_AWBURST, M_AXI_AWLOCK, 
  M_AXI_AWCACHE, M_AXI_AWPROT, M_AXI_AWQOS, M_AXI_AWVALID, M_AXI_AWREADY, M_AXI_WDATA, 
  M_AXI_WSTRB, M_AXI_WLAST, M_AXI_WVALID, M_AXI_WREADY, M_AXI_BID, M_AXI_BRESP, M_AXI_BVALID, 
  M_AXI_BREADY, M_AXI_ARID, M_AXI_ARADDR, M_AXI_ARLEN, M_AXI_ARSIZE, M_AXI_ARBURST, 
  M_AXI_ARLOCK, M_AXI_ARCACHE, M_AXI_ARPROT, M_AXI_ARQOS, M_AXI_ARVALID, M_AXI_ARREADY, 
  M_AXI_RID, M_AXI_RDATA, M_AXI_RRESP, M_AXI_RLAST, M_AXI_RVALID, M_AXI_RREADY)
/* synthesis syn_black_box black_box_pad_pin="Clk,S_AXI1_AWID[0:0],S_AXI1_AWADDR[31:0],S_AXI1_AWLEN[7:0],S_AXI1_AWSIZE[2:0],S_AXI1_AWBURST[1:0],S_AXI1_AWLOCK,S_AXI1_AWCACHE[3:0],S_AXI1_AWPROT[2:0],S_AXI1_AWQOS[3:0],S_AXI1_AWVALID,S_AXI1_AWREADY,S_AXI1_WDATA[31:0],S_AXI1_WSTRB[3:0],S_AXI1_WLAST,S_AXI1_WVALID,S_AXI1_WREADY,S_AXI1_BID[0:0],S_AXI1_BRESP[1:0],S_AXI1_BVALID,S_AXI1_BREADY,S_AXI1_ARID[0:0],S_AXI1_ARADDR[31:0],S_AXI1_ARLEN[7:0],S_AXI1_ARSIZE[2:0],S_AXI1_ARBURST[1:0],S_AXI1_ARLOCK,S_AXI1_ARCACHE[3:0],S_AXI1_ARPROT[2:0],S_AXI1_ARQOS[3:0],S_AXI1_ARVALID,S_AXI1_ARREADY,S_AXI1_RID[0:0],S_AXI1_RDATA[31:0],S_AXI1_RRESP[1:0],S_AXI1_RLAST,S_AXI1_RVALID,S_AXI1_RREADY,S_AXI2_AWID[0:0],S_AXI2_AWADDR[31:0],S_AXI2_AWLEN[7:0],S_AXI2_AWSIZE[2:0],S_AXI2_AWBURST[1:0],S_AXI2_AWLOCK,S_AXI2_AWCACHE[3:0],S_AXI2_AWPROT[2:0],S_AXI2_AWQOS[3:0],S_AXI2_AWVALID,S_AXI2_AWREADY,S_AXI2_WDATA[31:0],S_AXI2_WSTRB[3:0],S_AXI2_WLAST,S_AXI2_WVALID,S_AXI2_WREADY,S_AXI2_BID[0:0],S_AXI2_BRESP[1:0],S_AXI2_BVALID,S_AXI2_BREADY,S_AXI2_ARID[0:0],S_AXI2_ARADDR[31:0],S_AXI2_ARLEN[7:0],S_AXI2_ARSIZE[2:0],S_AXI2_ARBURST[1:0],S_AXI2_ARLOCK,S_AXI2_ARCACHE[3:0],S_AXI2_ARPROT[2:0],S_AXI2_ARQOS[3:0],S_AXI2_ARVALID,S_AXI2_ARREADY,S_AXI2_RID[0:0],S_AXI2_RDATA[31:0],S_AXI2_RRESP[1:0],S_AXI2_RLAST,S_AXI2_RVALID,S_AXI2_RREADY,S_AXI3_AWID[0:0],S_AXI3_AWADDR[31:0],S_AXI3_AWLEN[7:0],S_AXI3_AWSIZE[2:0],S_AXI3_AWBURST[1:0],S_AXI3_AWLOCK,S_AXI3_AWCACHE[3:0],S_AXI3_AWPROT[2:0],S_AXI3_AWQOS[3:0],S_AXI3_AWVALID,S_AXI3_AWREADY,S_AXI3_WDATA[31:0],S_AXI3_WSTRB[3:0],S_AXI3_WLAST,S_AXI3_WVALID,S_AXI3_WREADY,S_AXI3_BID[0:0],S_AXI3_BRESP[1:0],S_AXI3_BVALID,S_AXI3_BREADY,S_AXI3_ARID[0:0],S_AXI3_ARADDR[31:0],S_AXI3_ARLEN[7:0],S_AXI3_ARSIZE[2:0],S_AXI3_ARBURST[1:0],S_AXI3_ARLOCK,S_AXI3_ARCACHE[3:0],S_AXI3_ARPROT[2:0],S_AXI3_ARQOS[3:0],S_AXI3_ARVALID,S_AXI3_ARREADY,S_AXI3_RID[0:0],S_AXI3_RDATA[31:0],S_AXI3_RRESP[1:0],S_AXI3_RLAST,S_AXI3_RVALID,S_AXI3_RREADY,M_AXI_AWID[0:0],M_AXI_AWADDR[31:0],M_AXI_AWLEN[7:0],M_AXI_AWSIZE[2:0],M_AXI_AWBURST[1:0],M_AXI_AWLOCK,M_AXI_AWCACHE[3:0],M_AXI_AWPROT[2:0],M_AXI_AWQOS[3:0],M_AXI_AWVALID,M_AXI_AWREADY,M_AXI_WDATA[31:0],M_AXI_WSTRB[3:0],M_AXI_WLAST,M_AXI_WVALID,M_AXI_WREADY,M_AXI_BID[0:0],M_AXI_BRESP[1:0],M_AXI_BVALID,M_AXI_BREADY,M_AXI_ARID[0:0],M_AXI_ARADDR[31:0],M_AXI_ARLEN[7:0],M_AXI_ARSIZE[2:0],M_AXI_ARBURST[1:0],M_AXI_ARLOCK,M_AXI_ARCACHE[3:0],M_AXI_ARPROT[2:0],M_AXI_ARQOS[3:0],M_AXI_ARVALID,M_AXI_ARREADY,M_AXI_RID[0:0],M_AXI_RDATA[31:0],M_AXI_RRESP[1:0],M_AXI_RLAST,M_AXI_RVALID,M_AXI_RREADY" */;
  input Clk;
  input [0:0]S_AXI1_AWID;
  input [31:0]S_AXI1_AWADDR;
  input [7:0]S_AXI1_AWLEN;
  input [2:0]S_AXI1_AWSIZE;
  input [1:0]S_AXI1_AWBURST;
  input S_AXI1_AWLOCK;
  input [3:0]S_AXI1_AWCACHE;
  input [2:0]S_AXI1_AWPROT;
  input [3:0]S_AXI1_AWQOS;
  input S_AXI1_AWVALID;
  output S_AXI1_AWREADY;
  input [31:0]S_AXI1_WDATA;
  input [3:0]S_AXI1_WSTRB;
  input S_AXI1_WLAST;
  input S_AXI1_WVALID;
  output S_AXI1_WREADY;
  output [0:0]S_AXI1_BID;
  output [1:0]S_AXI1_BRESP;
  output S_AXI1_BVALID;
  input S_AXI1_BREADY;
  input [0:0]S_AXI1_ARID;
  input [31:0]S_AXI1_ARADDR;
  input [7:0]S_AXI1_ARLEN;
  input [2:0]S_AXI1_ARSIZE;
  input [1:0]S_AXI1_ARBURST;
  input S_AXI1_ARLOCK;
  input [3:0]S_AXI1_ARCACHE;
  input [2:0]S_AXI1_ARPROT;
  input [3:0]S_AXI1_ARQOS;
  input S_AXI1_ARVALID;
  output S_AXI1_ARREADY;
  output [0:0]S_AXI1_RID;
  output [31:0]S_AXI1_RDATA;
  output [1:0]S_AXI1_RRESP;
  output S_AXI1_RLAST;
  output S_AXI1_RVALID;
  input S_AXI1_RREADY;
  input [0:0]S_AXI2_AWID;
  input [31:0]S_AXI2_AWADDR;
  input [7:0]S_AXI2_AWLEN;
  input [2:0]S_AXI2_AWSIZE;
  input [1:0]S_AXI2_AWBURST;
  input S_AXI2_AWLOCK;
  input [3:0]S_AXI2_AWCACHE;
  input [2:0]S_AXI2_AWPROT;
  input [3:0]S_AXI2_AWQOS;
  input S_AXI2_AWVALID;
  output S_AXI2_AWREADY;
  input [31:0]S_AXI2_WDATA;
  input [3:0]S_AXI2_WSTRB;
  input S_AXI2_WLAST;
  input S_AXI2_WVALID;
  output S_AXI2_WREADY;
  output [0:0]S_AXI2_BID;
  output [1:0]S_AXI2_BRESP;
  output S_AXI2_BVALID;
  input S_AXI2_BREADY;
  input [0:0]S_AXI2_ARID;
  input [31:0]S_AXI2_ARADDR;
  input [7:0]S_AXI2_ARLEN;
  input [2:0]S_AXI2_ARSIZE;
  input [1:0]S_AXI2_ARBURST;
  input S_AXI2_ARLOCK;
  input [3:0]S_AXI2_ARCACHE;
  input [2:0]S_AXI2_ARPROT;
  input [3:0]S_AXI2_ARQOS;
  input S_AXI2_ARVALID;
  output S_AXI2_ARREADY;
  output [0:0]S_AXI2_RID;
  output [31:0]S_AXI2_RDATA;
  output [1:0]S_AXI2_RRESP;
  output S_AXI2_RLAST;
  output S_AXI2_RVALID;
  input S_AXI2_RREADY;
  input [0:0]S_AXI3_AWID;
  input [31:0]S_AXI3_AWADDR;
  input [7:0]S_AXI3_AWLEN;
  input [2:0]S_AXI3_AWSIZE;
  input [1:0]S_AXI3_AWBURST;
  input S_AXI3_AWLOCK;
  input [3:0]S_AXI3_AWCACHE;
  input [2:0]S_AXI3_AWPROT;
  input [3:0]S_AXI3_AWQOS;
  input S_AXI3_AWVALID;
  output S_AXI3_AWREADY;
  input [31:0]S_AXI3_WDATA;
  input [3:0]S_AXI3_WSTRB;
  input S_AXI3_WLAST;
  input S_AXI3_WVALID;
  output S_AXI3_WREADY;
  output [0:0]S_AXI3_BID;
  output [1:0]S_AXI3_BRESP;
  output S_AXI3_BVALID;
  input S_AXI3_BREADY;
  input [0:0]S_AXI3_ARID;
  input [31:0]S_AXI3_ARADDR;
  input [7:0]S_AXI3_ARLEN;
  input [2:0]S_AXI3_ARSIZE;
  input [1:0]S_AXI3_ARBURST;
  input S_AXI3_ARLOCK;
  input [3:0]S_AXI3_ARCACHE;
  input [2:0]S_AXI3_ARPROT;
  input [3:0]S_AXI3_ARQOS;
  input S_AXI3_ARVALID;
  output S_AXI3_ARREADY;
  output [0:0]S_AXI3_RID;
  output [31:0]S_AXI3_RDATA;
  output [1:0]S_AXI3_RRESP;
  output S_AXI3_RLAST;
  output S_AXI3_RVALID;
  input S_AXI3_RREADY;
  output [0:0]M_AXI_AWID;
  output [31:0]M_AXI_AWADDR;
  output [7:0]M_AXI_AWLEN;
  output [2:0]M_AXI_AWSIZE;
  output [1:0]M_AXI_AWBURST;
  output M_AXI_AWLOCK;
  output [3:0]M_AXI_AWCACHE;
  output [2:0]M_AXI_AWPROT;
  output [3:0]M_AXI_AWQOS;
  output M_AXI_AWVALID;
  input M_AXI_AWREADY;
  output [31:0]M_AXI_WDATA;
  output [3:0]M_AXI_WSTRB;
  output M_AXI_WLAST;
  output M_AXI_WVALID;
  input M_AXI_WREADY;
  input [0:0]M_AXI_BID;
  input [1:0]M_AXI_BRESP;
  input M_AXI_BVALID;
  output M_AXI_BREADY;
  output [0:0]M_AXI_ARID;
  output [31:0]M_AXI_ARADDR;
  output [7:0]M_AXI_ARLEN;
  output [2:0]M_AXI_ARSIZE;
  output [1:0]M_AXI_ARBURST;
  output M_AXI_ARLOCK;
  output [3:0]M_AXI_ARCACHE;
  output [2:0]M_AXI_ARPROT;
  output [3:0]M_AXI_ARQOS;
  output M_AXI_ARVALID;
  input M_AXI_ARREADY;
  input [0:0]M_AXI_RID;
  input [31:0]M_AXI_RDATA;
  input [1:0]M_AXI_RRESP;
  input M_AXI_RLAST;
  input M_AXI_RVALID;
  output M_AXI_RREADY;
endmodule
