-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mxm_execute_ursa_mxm_execute_ursa_Pipeline_LOAD_A is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_aw_AWVALID : OUT STD_LOGIC;
    m_axi_aw_AWREADY : IN STD_LOGIC;
    m_axi_aw_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_aw_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_aw_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_aw_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_aw_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_aw_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_aw_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_aw_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_aw_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_aw_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_WVALID : OUT STD_LOGIC;
    m_axi_aw_WREADY : IN STD_LOGIC;
    m_axi_aw_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_aw_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_aw_WLAST : OUT STD_LOGIC;
    m_axi_aw_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_ARVALID : OUT STD_LOGIC;
    m_axi_aw_ARREADY : IN STD_LOGIC;
    m_axi_aw_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_aw_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_aw_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_aw_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_aw_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_aw_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_aw_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_aw_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_aw_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_aw_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_RVALID : IN STD_LOGIC;
    m_axi_aw_RREADY : OUT STD_LOGIC;
    m_axi_aw_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_aw_RLAST : IN STD_LOGIC;
    m_axi_aw_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_aw_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_aw_BVALID : IN STD_LOGIC;
    m_axi_aw_BREADY : OUT STD_LOGIC;
    m_axi_aw_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_aw_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_aw_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    stride_a : IN STD_LOGIC_VECTOR (16 downto 0);
    sub_i28_cast : IN STD_LOGIC_VECTOR (13 downto 0);
    sext_ln106 : IN STD_LOGIC_VECTOR (28 downto 0);
    a_buf_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_7_ce0 : OUT STD_LOGIC;
    a_buf_7_we0 : OUT STD_LOGIC;
    a_buf_7_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    a_buf_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_6_ce0 : OUT STD_LOGIC;
    a_buf_6_we0 : OUT STD_LOGIC;
    a_buf_6_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    a_buf_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_5_ce0 : OUT STD_LOGIC;
    a_buf_5_we0 : OUT STD_LOGIC;
    a_buf_5_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    a_buf_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_4_ce0 : OUT STD_LOGIC;
    a_buf_4_we0 : OUT STD_LOGIC;
    a_buf_4_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    a_buf_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_3_ce0 : OUT STD_LOGIC;
    a_buf_3_we0 : OUT STD_LOGIC;
    a_buf_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    a_buf_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_2_ce0 : OUT STD_LOGIC;
    a_buf_2_we0 : OUT STD_LOGIC;
    a_buf_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    a_buf_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_1_ce0 : OUT STD_LOGIC;
    a_buf_1_we0 : OUT STD_LOGIC;
    a_buf_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    a_buf_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_buf_ce0 : OUT STD_LOGIC;
    a_buf_we0 : OUT STD_LOGIC;
    a_buf_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of mxm_execute_ursa_mxm_execute_ursa_Pipeline_LOAD_A is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln106_reg_379 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln106_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal aw_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sub_i28_cast_cast_fu_235_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_i28_cast_cast_reg_374 : STD_LOGIC_VECTOR (16 downto 0);
    signal c_3_reg_383 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln103_fu_286_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln103_reg_388 : STD_LOGIC_VECTOR (2 downto 0);
    signal aw_addr_read_reg_392 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln109_fu_337_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_92 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal r_5_fu_311_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal c_fu_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal c_5_fu_319_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal n_fu_100 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal add_ln106_fu_263_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_sig_allocacmp_n_1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln109_1_fu_290_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln110_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_fu_299_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_4_fu_305_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mxm_execute_ursa_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mxm_execute_ursa_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    c_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_96 <= ap_const_lv16_0;
                elsif (((icmp_ln106_reg_379 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    c_fu_96 <= c_5_fu_319_p3;
                end if;
            end if; 
        end if;
    end process;

    n_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln106_fu_257_p2 = ap_const_lv1_0))) then 
                    n_fu_100 <= add_ln106_fu_263_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_100 <= ap_const_lv17_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_92 <= ap_const_lv16_0;
                elsif (((icmp_ln106_reg_379 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    r_fu_92 <= r_5_fu_311_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                aw_addr_read_reg_392 <= m_axi_aw_RDATA;
                c_3_reg_383 <= c_fu_96;
                icmp_ln106_reg_379 <= icmp_ln106_fu_257_p2;
                sub_i28_cast_cast_reg_374 <= sub_i28_cast_cast_fu_235_p1;
                trunc_ln103_reg_388 <= trunc_ln103_fu_286_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_buf_1_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_1_ce0 <= ap_const_logic_1;
        else 
            a_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_1_d0 <= aw_addr_read_reg_392;

    a_buf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_1))) then 
            a_buf_1_we0 <= ap_const_logic_1;
        else 
            a_buf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_2_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_2_ce0 <= ap_const_logic_1;
        else 
            a_buf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_2_d0 <= aw_addr_read_reg_392;

    a_buf_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_2))) then 
            a_buf_2_we0 <= ap_const_logic_1;
        else 
            a_buf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_3_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_3_ce0 <= ap_const_logic_1;
        else 
            a_buf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_3_d0 <= aw_addr_read_reg_392;

    a_buf_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_3))) then 
            a_buf_3_we0 <= ap_const_logic_1;
        else 
            a_buf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_4_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_4_ce0 <= ap_const_logic_1;
        else 
            a_buf_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_4_d0 <= aw_addr_read_reg_392;

    a_buf_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_4))) then 
            a_buf_4_we0 <= ap_const_logic_1;
        else 
            a_buf_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_5_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_5_ce0 <= ap_const_logic_1;
        else 
            a_buf_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_5_d0 <= aw_addr_read_reg_392;

    a_buf_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_5))) then 
            a_buf_5_we0 <= ap_const_logic_1;
        else 
            a_buf_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_6_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_6_ce0 <= ap_const_logic_1;
        else 
            a_buf_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_6_d0 <= aw_addr_read_reg_392;

    a_buf_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_6))) then 
            a_buf_6_we0 <= ap_const_logic_1;
        else 
            a_buf_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_7_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_7_ce0 <= ap_const_logic_1;
        else 
            a_buf_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_7_d0 <= aw_addr_read_reg_392;

    a_buf_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_7))) then 
            a_buf_7_we0 <= ap_const_logic_1;
        else 
            a_buf_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_address0 <= zext_ln109_fu_337_p1(5 - 1 downto 0);

    a_buf_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            a_buf_ce0 <= ap_const_logic_1;
        else 
            a_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_buf_d0 <= aw_addr_read_reg_392;

    a_buf_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln103_reg_388)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln103_reg_388 = ap_const_lv3_0))) then 
            a_buf_we0 <= ap_const_logic_1;
        else 
            a_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln106_fu_263_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n_1) + unsigned(ap_const_lv17_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_aw_RVALID, icmp_ln106_reg_379)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln106_reg_379 = ap_const_lv1_0) and (m_axi_aw_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln106_fu_257_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln106_fu_257_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln106_reg_379, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln106_reg_379 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_n_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, n_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n_1 <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_n_1 <= n_fu_100;
        end if; 
    end process;


    aw_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_aw_RVALID, icmp_ln106_reg_379, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln106_reg_379 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            aw_blk_n_R <= m_axi_aw_RVALID;
        else 
            aw_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    c_4_fu_305_p2 <= std_logic_vector(unsigned(c_fu_96) + unsigned(ap_const_lv16_1));
    c_5_fu_319_p3 <= 
        ap_const_lv16_0 when (icmp_ln110_fu_294_p2(0) = '1') else 
        c_4_fu_305_p2;
    icmp_ln106_fu_257_p2 <= "1" when (ap_sig_allocacmp_n_1 = stride_a) else "0";
    icmp_ln110_fu_294_p2 <= "1" when (sub_i28_cast_cast_reg_374 = zext_ln109_1_fu_290_p1) else "0";
    m_axi_aw_ARADDR <= ap_const_lv32_0;
    m_axi_aw_ARBURST <= ap_const_lv2_0;
    m_axi_aw_ARCACHE <= ap_const_lv4_0;
    m_axi_aw_ARID <= ap_const_lv1_0;
    m_axi_aw_ARLEN <= ap_const_lv32_0;
    m_axi_aw_ARLOCK <= ap_const_lv2_0;
    m_axi_aw_ARPROT <= ap_const_lv3_0;
    m_axi_aw_ARQOS <= ap_const_lv4_0;
    m_axi_aw_ARREGION <= ap_const_lv4_0;
    m_axi_aw_ARSIZE <= ap_const_lv3_0;
    m_axi_aw_ARUSER <= ap_const_lv1_0;
    m_axi_aw_ARVALID <= ap_const_logic_0;
    m_axi_aw_AWADDR <= ap_const_lv32_0;
    m_axi_aw_AWBURST <= ap_const_lv2_0;
    m_axi_aw_AWCACHE <= ap_const_lv4_0;
    m_axi_aw_AWID <= ap_const_lv1_0;
    m_axi_aw_AWLEN <= ap_const_lv32_0;
    m_axi_aw_AWLOCK <= ap_const_lv2_0;
    m_axi_aw_AWPROT <= ap_const_lv3_0;
    m_axi_aw_AWQOS <= ap_const_lv4_0;
    m_axi_aw_AWREGION <= ap_const_lv4_0;
    m_axi_aw_AWSIZE <= ap_const_lv3_0;
    m_axi_aw_AWUSER <= ap_const_lv1_0;
    m_axi_aw_AWVALID <= ap_const_logic_0;
    m_axi_aw_BREADY <= ap_const_logic_0;

    m_axi_aw_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln106_reg_379, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln106_reg_379 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_aw_RREADY <= ap_const_logic_1;
        else 
            m_axi_aw_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_aw_WDATA <= ap_const_lv64_0;
    m_axi_aw_WID <= ap_const_lv1_0;
    m_axi_aw_WLAST <= ap_const_logic_0;
    m_axi_aw_WSTRB <= ap_const_lv8_0;
    m_axi_aw_WUSER <= ap_const_lv1_0;
    m_axi_aw_WVALID <= ap_const_logic_0;
    r_4_fu_299_p2 <= std_logic_vector(unsigned(r_fu_92) + unsigned(ap_const_lv16_1));
    r_5_fu_311_p3 <= 
        r_4_fu_299_p2 when (icmp_ln110_fu_294_p2(0) = '1') else 
        r_fu_92;
        sub_i28_cast_cast_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_i28_cast),17));

    trunc_ln103_fu_286_p1 <= r_fu_92(3 - 1 downto 0);
    zext_ln109_1_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_96),17));
    zext_ln109_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_3_reg_383),32));
end behav;
