-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity shell_top_sa_reset is
port (
    ap_ready : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_35 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_35_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_34 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_34_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_33 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_33_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_32 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_32_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_31 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_31_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_30 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_30_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_29 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_29_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_28 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_28_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_27 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_27_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_26 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_26_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_25 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_25_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_24 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_24_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_23 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_23_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_22 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_22_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_21 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_21_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_20 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_20_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_19 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_19_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_18 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_18_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_17 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_17_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_16 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_16_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_15 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_15_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_14 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_14_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_13 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_13_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_12 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_12_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_11 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_11_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_10 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_10_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_9 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_9_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_8 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_8_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_7 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_7_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_6 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_6_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_5 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_5_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_4 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_4_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_3 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_3_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_2 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_2_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_1_ap_vld : OUT STD_LOGIC;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un : OUT STD_LOGIC_VECTOR (19 downto 0);
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_ap_vld : OUT STD_LOGIC );
end;


architecture behav of shell_top_sa_reset is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;


begin



    ap_ready <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_1 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_10 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_10_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_11 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_11_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_12 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_12_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_13 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_13_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_14 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_14_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_15 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_15_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_16 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_16_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_17 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_17_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_18 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_18_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_19 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_19_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_1_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_2 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_20 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_20_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_21 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_21_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_22 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_22_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_23 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_23_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_24 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_24_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_25 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_25_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_26 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_26_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_27 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_27_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_28 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_28_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_29 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_29_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_2_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_3 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_30 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_30_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_31 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_31_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_32 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_32_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_33 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_33_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_34 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_34_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_35 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_35_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_3_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_4 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_4_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_5 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_5_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_6 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_6_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_7 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_7_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_8 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_8_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_9 <= ap_const_lv20_0;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_9_ap_vld <= ap_const_logic_1;
    shell_top_signed_char_unsigned_short_unsigned_char_unsigned_short_int_un_ap_vld <= ap_const_logic_1;
end behav;
